export class MultipleStatisticsTrace { constructor(){ this.steps=[]; } record(step,value,meta={}){ const r=Object.freeze({ step,value,meta:Object.freeze({ ...meta }) }); this.steps.push(r); return r; } list(){ return Object.freeze(this.steps.slice()); }}
function values(peers){ return peers.map(p=>p.multipleValue).filter(v=>Number.isFinite(v)).sort((a,b)=>a-b); }
export class MeanMultipleCalculator { calculate(peers){ const v=values(peers); return v.reduce((a,b)=>a+b,0)/v.length; }}
export class MedianMultipleCalculator { calculate(peers){ const v=values(peers); const mid=Math.floor(v.length/2); return v.length%2?v[mid]:(v[mid-1]+v[mid])/2; }}
export class TrimmedMeanCalculator { calculate(peers, trim=0.1){ const v=values(peers); const n=Math.floor(v.length*trim); const t=v.slice(n, v.length-n || v.length); return t.reduce((a,b)=>a+b,0)/t.length; }}
export class WinsorizedMultipleCalculator { calculate(peers, trim=0.1){ const v=values(peers); const n=Math.floor(v.length*trim); const low=v[n]??v[0]; const high=v[v.length-1-n]??v[v.length-1]; const w=v.map(x=>Math.max(low, Math.min(high,x))); return w.reduce((a,b)=>a+b,0)/w.length; }}
export class SelectedMultipleResolver { resolve(input, stats){ if(input.outlierPolicy==='manual') return input.selectedMultiple; if(input.statisticalMethod==='mean') return stats.mean; if(input.statisticalMethod==='trimmedMean') return stats.trimmedMean; if(input.statisticalMethod==='winsorized') return stats.winsorized; return stats.median; }}
export class MultipleStatisticsEngine { constructor(){ this.meanCalc=new MeanMultipleCalculator(); this.medianCalc=new MedianMultipleCalculator(); this.trimmedCalc=new TrimmedMeanCalculator(); this.winsorizedCalc=new WinsorizedMultipleCalculator(); this.resolver=new SelectedMultipleResolver(); }
  calculate(input){ const trace=new MultipleStatisticsTrace(); const peerMultiples=values(input.peerSet); trace.record('peer-multiples', peerMultiples); const mean=this.meanCalc.calculate(input.peerSet); const median=this.medianCalc.calculate(input.peerSet); const trimmedMean=this.trimmedCalc.calculate(input.peerSet); const winsorized=this.winsorizedCalc.calculate(input.peerSet); trace.record('mean', mean); trace.record('median', median); trace.record('trimmed-mean', trimmedMean); trace.record('winsorized', winsorized); const stats={ mean, median, trimmedMean, winsorized }; const selectedMultiple=this.resolver.resolve(input, stats); trace.record('selected-multiple', selectedMultiple, { outlierPolicy:input.outlierPolicy, statisticalMethod:input.statisticalMethod }); return Object.freeze({ peerMultiples:Object.freeze(peerMultiples), mean, median, trimmedMean, winsorized, selectedMultiple, trace:trace.list() }); }}
