import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';

export const RESEARCH_INTELLIGENCE_FEATURE_FLAG = 'research_intelligence_foundation';
export const ResearchCollaborationRole = Object.freeze({ ResearchViewer:'ResearchViewer', ResearchContributor:'ResearchContributor', ResearchReviewer:'ResearchReviewer', ResearchOwner:'ResearchOwner' });
export const ResearchIntelligenceEventType = Object.freeze({ ResearchTemplateRegistered:'ResearchTemplateRegistered', ResearchTemplateApplied:'ResearchTemplateApplied', ResearchSectionCreated:'ResearchSectionCreated', ResearchSectionUpdated:'ResearchSectionUpdated', AnalystNoteCreated:'AnalystNoteCreated', AnalystNoteUpdated:'AnalystNoteUpdated', ResearchReviewStarted:'ResearchReviewStarted', ResearchReviewSubmitted:'ResearchReviewSubmitted', ResearchReviewReturned:'ResearchReviewReturned', ResearchReviewCompleted:'ResearchReviewCompleted', ResearchChecklistItemCreated:'ResearchChecklistItemCreated', ResearchChecklistItemCompleted:'ResearchChecklistItemCompleted', ResearchCompletenessChecked:'ResearchCompletenessChecked', EvidenceCandidateCreated:'EvidenceCandidateCreated', EvidenceCandidateLinked:'EvidenceCandidateLinked', ResearchCommentAdded:'ResearchCommentAdded', ResearchCollaborationActivityRecorded:'ResearchCollaborationActivityRecorded' });
export const ResearchIntelligenceCommandType = Object.freeze({ RegisterResearchTemplate:'RegisterResearchTemplate', ApplyResearchTemplate:'ApplyResearchTemplate', CreateResearchSection:'CreateResearchSection', UpdateResearchSection:'UpdateResearchSection', CreateAnalystNote:'CreateAnalystNote', UpdateAnalystNote:'UpdateAnalystNote', StartResearchReview:'StartResearchReview', SubmitResearchReview:'SubmitResearchReview', ReturnResearchReview:'ReturnResearchReview', CompleteResearchReview:'CompleteResearchReview', CreateChecklistItem:'CreateChecklistItem', CompleteChecklistItem:'CompleteChecklistItem', RunCompletenessCheck:'RunCompletenessCheck', CreateEvidenceCandidate:'CreateEvidenceCandidate', LinkEvidenceCandidate:'LinkEvidenceCandidate', AddResearchComment:'AddResearchComment', RecordCollaborationActivity:'RecordCollaborationActivity' });
export const ResearchTemplateType = Object.freeze({ companyResearchStructure:'company-research-structure', sourceReviewStructure:'source-review-structure', meetingNoteStructure:'meeting-note-structure', diligenceQuestionStructure:'diligence-question-structure', reviewPreparationStructure:'review-preparation-structure' });
export const ResearchSectionType = Object.freeze({ overview:'overview', keyQuestions:'key-questions', sourceNotes:'source-notes', meetingNotes:'meeting-notes', openItems:'open-items', risksToInvestigate:'risks-to-investigate', references:'references', reviewNotes:'review-notes' });
export const ResearchReviewStatus = Object.freeze({ NotStarted:'NotStarted', InProgress:'InProgress', Submitted:'Submitted', Returned:'Returned', Completed:'Completed', Cancelled:'Cancelled' });
export const ResearchChecklistItemStatus = Object.freeze({ Open:'Open', InProgress:'InProgress', Completed:'Completed', Waived:'Waived', Blocked:'Blocked' });
export const EvidenceCandidateStatus = Object.freeze({ Draft:'Draft', Linked:'Linked', ReadyForReview:'ReadyForReview', Rejected:'Rejected', Archived:'Archived' });
export const ResearchCollaborationEventType = Object.freeze({ ThreadCreated:'ThreadCreated', CommentAdded:'CommentAdded', MentionRecorded:'MentionRecorded', ThreadResolved:'ThreadResolved' });

export const forbiddenIntelligenceTerms = Object.freeze(['valuation','discounted cash flow','dcf','relative valuation','factor model','stock scoring','scorecompany','companyqualityscore','investmentscore','ratingconfidence','recommendationstrength','portfoliofitscore','buy','sell','hold','recommendation','recommend','approve investment','reject investment','target price','forecast','market data','provider integration','price volume','financial statement','portfolio action','position sizing','risk calculation','decision automation','investment opinion']);
export function assertRequired(record, fields, label='record') { for (const f of fields) if (record?.[f] === undefined || record?.[f] === null || record?.[f] === '') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoInvestmentAnalysis(value, label='Research Intelligence') { const text=JSON.stringify(value||{}).toLowerCase(); for (const term of forbiddenIntelligenceTerms) if (text.includes(term)) throw new Error(`${label} contains forbidden investment analysis: ${term}`); return true; }
export function validateResearchIntelligenceCommand(type) { if (!Object.values(ResearchIntelligenceCommandType).includes(type)) throw new Error(`Unsupported Research Intelligence command: ${type}`); assertNoInvestmentAnalysis(type, 'Research Intelligence command'); return true; }
export function createResearchActionAudit({ workflowInstanceId, documentId=null, userId='system', correlationId } = {}) { assertRequired({ workflowInstanceId, userId, correlationId }, ['workflowInstanceId','userId','correlationId'], 'researchActionAudit'); return Object.freeze({ researchActionId:createOpaqueId('RACT'), workflowInstanceId, documentId, userId, correlationId, timestamp:new Date().toISOString() }); }
export function validateVersioned(record, field, label='record') { if (!record?.[field]) throw new Error(`${label}.${field} is required`); return true; }
