import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';

export const DCF_PLUGIN_ID = 'dcf-valuation-plugin';
export const DCF_FORMULA_VERSION = 'DCF_FORMULA_VERSION_1.0';
export const DCF_SNAPSHOT_SCHEMA_VERSION = 'DCF_PLUGIN_SNAPSHOT_1.0';
export const DCFPluginEventType = Object.freeze({ DCFPluginRegistered:'DCFPluginRegistered', DCFInputsValidated:'DCFInputsValidated', DCFExecutionStarted:'DCFExecutionStarted', DCFExecutionCompleted:'DCFExecutionCompleted', DCFFormulaStepRecorded:'DCFFormulaStepRecorded', DCFValuationResultCreated:'DCFValuationResultCreated', DCFAuditRecorded:'DCFAuditRecorded', DCFSnapshotCreated:'DCFSnapshotCreated', DCFReplayCompleted:'DCFReplayCompleted' });
export const DCFPluginCommandType = Object.freeze({ RegisterDCFPlugin:'RegisterDCFPlugin', ValidateDCFInputs:'ValidateDCFInputs', StartDCFExecution:'StartDCFExecution', CompleteDCFExecution:'CompleteDCFExecution', RecordDCFFormulaStep:'RecordDCFFormulaStep', CreateDCFValuationResult:'CreateDCFValuationResult', RecordDCFAudit:'RecordDCFAudit', CreateDCFSnapshot:'CreateDCFSnapshot', ReplayDCFExecution:'ReplayDCFExecution' });
export const DCFPluginStatus = Object.freeze({ draft:'draft', active:'active', deprecated:'deprecated', retired:'retired' });
export const DCFInputType = Object.freeze({ explicitCashFlow:'explicit-cash-flow' });
export const DCFAssumptionType = Object.freeze({ explicit:'explicit' });
export const DCFOutputType = Object.freeze({ valuationArtifact:'valuation-artifact' });
export const DCFValidationStatus = Object.freeze({ Passed:'Passed', Failed:'Failed' });
export const DCFPermissionAction = Object.freeze({ viewDCFPlugin:'viewDCFPlugin', runDCFDryRun:'runDCFDryRun', runDCFValidation:'runDCFValidation', runDCFCalculation:'runDCFCalculation', readDCFAudit:'readDCFAudit', replayDCFExecution:'replayDCFExecution' });
export const TerminalValueAssumptionType = Object.freeze({ perpetualGrowth:'perpetual-growth', exitMultiplePlaceholder:'exit-multiple-placeholder', explicitTerminalValue:'explicit-terminal-value' });
export const DCFErrorCode = Object.freeze({ MISSING_ASSUMPTION:'MISSING_ASSUMPTION', INVALID_DISCOUNT_RATE:'INVALID_DISCOUNT_RATE', INVALID_TERMINAL_GROWTH:'INVALID_TERMINAL_GROWTH', NEGATIVE_SHARE_COUNT:'NEGATIVE_SHARE_COUNT', DIVISION_BY_ZERO:'DIVISION_BY_ZERO', NUMERICAL_OVERFLOW:'NUMERICAL_OVERFLOW', UNSUPPORTED_TERMINAL_VALUE_ASSUMPTION:'UNSUPPORTED_TERMINAL_VALUE_ASSUMPTION' });
const forbidden = Object.freeze(['recommendation','rating','score','buy','sell','hold','portfolio action','decision automation','market data','provider integration','forecast engine','wacc calculation','cost of capital']);
export function assertRequired(record, fields, label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoInvestmentDecision(value,label='DCF'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pattern=/^[a-z ]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pattern?pattern.test(text):text.includes(term)) throw new Error(`${label} contains forbidden investment decision logic: ${term}`); } return true; }
export function validateDCFCommand(type){ if(!Object.values(DCFPluginCommandType).includes(type)) throw new Error(`Unsupported DCF command: ${type}`); assertNoInvestmentDecision(type,'DCF command'); return true; }
export function createDCFAuditIdentity({ dcfPluginId=DCF_PLUGIN_ID, dcfPluginVersion, dcfFormulaVersion=DCF_FORMULA_VERSION, valuationExecutionId, valuationInputPackageId, companyId, securityId, userId='system', correlationId }={}){ assertRequired({ dcfPluginId, dcfPluginVersion, dcfFormulaVersion, valuationExecutionId, valuationInputPackageId, userId, correlationId }, ['dcfPluginId','dcfPluginVersion','dcfFormulaVersion','valuationExecutionId','valuationInputPackageId','userId','correlationId'], 'dcfAudit'); return Object.freeze({ dcfActionId:createOpaqueId('DCFACT'), dcfPluginId, dcfPluginVersion, dcfFormulaVersion, valuationExecutionId, valuationInputPackageId, companyId, securityId, userId, correlationId, timestamp:new Date().toISOString() }); }
export function finiteNumber(value, label){ if(typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`${label} must be a finite number`); return value; }
