import { createPlatformEvent } from '../../../../../packages/shared-types/src/index.js';
import { ProductEventType, ProductHealthState, createProductTelemetry, validateProductModuleManifest } from '../contracts/index.js';

export class ProductModuleManifestValidator { validate(manifest) { return validateProductModuleManifest(manifest); } }
export class ProductModuleVersionIndex { constructor(){ this.index=new Map(); } key(id,v){ return `${id}@${v}`; } add(m){ const k=this.key(m.productModuleId,m.version); if(this.index.has(k)) throw new Error(`Product module already registered: ${k}`); this.index.set(k,m); return m; } get(id,v){ return this.index.get(this.key(id,v))||null; } list(){ return [...this.index.values()]; } }
export class ProductModuleDiagnostics { constructor({ diagnostics }={}){ this.diagnostics=diagnostics; } record(event, meta){ return this.diagnostics?.record?.(`product.${event}`, meta); } }

export class ProductModuleRegistry {
  constructor({ validator = new ProductModuleManifestValidator(), versionIndex = new ProductModuleVersionIndex(), eventBus, diagnostics } = {}) { this.validator=validator; this.versionIndex=versionIndex; this.eventBus=eventBus; this.diagnostics=new ProductModuleDiagnostics({ diagnostics }); }
  register(manifest) { this.validator.validate(manifest); const record=deepFreeze({ health: ProductHealthState.Healthy, telemetry: createProductTelemetry(), ...manifest }); this.versionIndex.add(record); this.diagnostics.record('module.registered', { productModuleId: record.productModuleId, version: record.version }); this.eventBus?.publish(createPlatformEvent({ type: ProductEventType.ProductModuleRegistered, source:'ProductModuleRegistry', payload:{ productModuleId:record.productModuleId, version:record.version } })); return record; }
  get(id, version){ if(version) return this.versionIndex.get(id, version); return this.list().filter(m=>m.productModuleId===id).sort((a,b)=>String(b.version).localeCompare(String(a.version)))[0] || null; }
  list(){ return Object.freeze(this.versionIndex.list()); }
  byStatus(status){ return Object.freeze(this.list().filter(m=>m.status===status)); }
  byWorkspaceBinding(workspaceId){ return Object.freeze(this.list().filter(m=>m.workspaceBindings.some(b=>b.workspaceId===workspaceId))); }
  byWorkflowBinding(workflowId){ return Object.freeze(this.list().filter(m=>m.workflowBindings.some(b=>b.workflowId===workflowId))); }
}

export function createPlaceholderProductModuleManifests({ workflowId='WF_PLACEHOLDER', workflowVersion='1.0.0' } = {}) {
  const defs=[['research-product-placeholder','Research Product Placeholder','research'],['portfolio-product-placeholder','Portfolio Product Placeholder','portfolio'],['decision-product-placeholder','Decision Product Placeholder','decision-center'],['watchlist-product-placeholder','Watchlist Product Placeholder','watchlists'],['methodology-product-placeholder','Methodology Product Placeholder','methodologies']];
  return Object.freeze(defs.map(([productModuleId,name,workspaceId])=>deepFreeze({ productModuleId, name, version:'1.0.0', contractVersion:'1.0', owner:'product-framework', status:'active', featureFlag:`${productModuleId}_feature`, compatibility:{ minimumPlatformVersion:'2.0.0', maximumPlatformVersion:'2.x', minimumWorkflowVersion:'1.0.0', contractVersion:'1.0' }, dependencies:[{ type:'platform', target:'event-bus' }, { type:'workflow', target:'workflow-context' }], workspaceBindings:[{ productModuleId, workspaceId, featureFlag:`${productModuleId}_feature`, mountMode:'placeholder', placeholderOnly:true }], workflowBindings:[{ productModuleId, workflowId, workflowVersion, supportedSteps:['intake','review'], contextSubscriptions:['activeWorkspace','activeStep','subject'], placeholderOnly:true }], capabilities:[{ capabilityId:`${productModuleId}.workspace`, category:'workspace' }, { capabilityId:`${productModuleId}.context`, category:'context' }], permissions:[{ action:'view', effect:'allow' }, { action:'open', effect:'allow' }, { action:'mount', effect:'allow' }, { action:'readContext', effect:'allow' }], commands:[{ commandId:`open-${productModuleId}`, label:`Open ${name}`, featureFlag:`${productModuleId}_feature`, permission:'open' }], notifications:[{ notificationId:`${productModuleId}.notification`, type:'info', permission:'receiveNotification' }], activities:[{ activityId:`${productModuleId}.activity`, type:'moduleStatus', permission:'recordActivity' }], projections:[{ projectionId:`${productModuleId}.summary`, category:'moduleStatus', snapshotCompatible:true, projectionVersion:'1.0.0' }], createdAt:new Date().toISOString(), placeholderOnly:true, businessLogic:false })));
}
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
