import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
import { EvidenceCertificationStatus } from '../../evidence/index.js';
import { DOMAIN_SCHEMA_VERSION } from '../../domain/company-security/index.js';
import { assertNoValuationLogic } from '../contracts/index.js';
export class CompanySecurityValuationInputAdapter { adapt({ company, security }){ if(!company?.companyId||!security?.securityId) throw new Error('company and security are required'); if(security.issuerCompanyId!==company.companyId) throw new Error('security issuer must match company'); assertNoValuationLogic({ company, security }, 'Company/Security valuation input'); return Object.freeze({ companyId:company.companyId, securityId:security.securityId, domainSchemaVersion:company.domainSchemaVersion||DOMAIN_SCHEMA_VERSION }); }}
export class CertifiedEvidenceValuationInputAdapter { adapt(evidence){ if(evidence.certificationStatus!==EvidenceCertificationStatus.Certified) throw new Error('Certified evidence is required'); return Object.freeze({ evidenceRecordId:evidence.evidenceRecordId, evidenceVersionId:evidence.evidenceVersionId, certificationStatus:evidence.certificationStatus }); } rejectRawResearchArtifact(){ throw new Error('Raw research artifacts are not valuation inputs'); }}
export class MethodologyValuationInputAdapter { adapt(result){ if(!result?.validationResult||!result?.sufficiencyResult) throw new Error('methodology validation/sufficiency result required'); assertNoValuationLogic(result,'Methodology valuation input'); return Object.freeze({ methodologyId:result.methodologyId, methodologyVersion:result.methodologyVersion, methodologyExecutionId:result.executionId, validationResult:result.validationResult, sufficiencyResult:result.sufficiencyResult }); }}
export class ValuationInputPackageBuilder { build({ companySecurityInput, evidenceInputs=[], methodologyInput, configurationVersion }){ const pkg=deepFreeze({ valuationInputPackageId:createOpaqueId('VINP'), companyId:companySecurityInput.companyId, securityId:companySecurityInput.securityId, domainSchemaVersion:companySecurityInput.domainSchemaVersion, methodologyId:methodologyInput.methodologyId, methodologyVersion:methodologyInput.methodologyVersion, methodologyExecutionId:methodologyInput.methodologyExecutionId, evidenceRecordIds:Object.freeze(evidenceInputs.map(e=>e.evidenceRecordId)), evidenceVersionIds:Object.freeze(evidenceInputs.map(e=>e.evidenceVersionId)), configurationVersion, createdAt:new Date().toISOString() }); assertNoValuationLogic(pkg,'Valuation input package'); return pkg; }}
export class ValuationInputSufficiencyChecker { check(pkg){ const missing=[]; for(const f of ['companyId','securityId','methodologyId','methodologyVersion','methodologyExecutionId','configurationVersion']) if(!pkg[f]) missing.push(f); if(pkg.evidenceRecordIds.length===0) missing.push('evidenceRecordIds'); return Object.freeze({ passed:missing.length===0, missing:Object.freeze(missing) }); }}
export const ValuationInputPackage=Object.freeze({});
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
