import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
import { RecommendationInputType, assertNoDecisionLogic } from '../contracts/index.js';
export class ScoreArtifactRecommendationAdapter { adapt(scoreArtifact){ if(!scoreArtifact?.scoreArtifactId||!scoreArtifact?.scoreSchemaVersion) throw new Error('score artifact is required'); assertNoDecisionLogic(scoreArtifact,'score artifact recommendation input'); return Object.freeze({ inputType:RecommendationInputType.scoreArtifact, scoreArtifactId:scoreArtifact.scoreArtifactId, aggregateScore:scoreArtifact.aggregation?.aggregateScore, components:scoreArtifact.components||[] }); } rejectRawValuationArtifact(){ throw new Error('Raw valuation artifacts are not recommendation inputs'); }}
export class EvidenceReferenceRecommendationAdapter { adapt(ref){ return Object.freeze({ inputType:RecommendationInputType.evidenceReference, ...ref }); }}
export class MethodologyReferenceRecommendationAdapter { adapt(ref){ return Object.freeze({ inputType:RecommendationInputType.methodologyReference, ...ref }); }}
export class ResearchReferenceRecommendationAdapter { adapt(ref){ return Object.freeze({ inputType:RecommendationInputType.researchReference, ...ref }); }}
export class ValuationReferenceRecommendationAdapter { adapt(ref){ return Object.freeze({ inputType:RecommendationInputType.valuationReference, ...ref }); }}
export class RecommendationInputPackage { constructor({ recommendationModelId, recommendationModelVersion, scoreInput, references=[] }){ if(!scoreInput) throw new Error('scoreInput is required'); return Object.freeze({ inputPackageId:createOpaqueId('RINP'), recommendationModelId, recommendationModelVersion, scoreInput, references:Object.freeze(references.slice()), createdAt:new Date().toISOString() }); }}
export class RecommendationInputAdapterRegistry { constructor(){ this.adapters=new Map(); } register(type, adapter){ this.adapters.set(type,adapter); return adapter; } get(type){ const a=this.adapters.get(type); if(!a) throw new Error(`Recommendation adapter not found: ${type}`); return a; }}
