import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';
import { RELATIVE_VALUATION_FORMULA_VERSION, assertNoRelativeDecisionLogic, StructuralConfidence } from '../contracts/index.js';
import { RelativeValuationInputValidator, RelativeValuationAssumptionBundle } from '../inputs/index.js';
import { MultipleStatisticsEngine } from '../statistics/index.js';
import { RelativeValuationFormulaEngine } from '../formula/index.js';
export class RelativeValuationExecutionContext { constructor({ valuationExecutionId, valuationInputPackageId, pluginVersion='1.0.0', input }){ return Object.freeze({ relativeValuationExecutionId:createOpaqueId('RVALEX'), valuationExecutionId, valuationInputPackageId, pluginVersion, formulaVersion:RELATIVE_VALUATION_FORMULA_VERSION, input, createdAt:new Date().toISOString() }); }}
export class RelativeValuationDryRunExecutor { run(context){ return Object.freeze({ relativeValuationExecutionId:context.relativeValuationExecutionId, validationResult:new RelativeValuationInputValidator().validate(context.input), auditResult:{ dryRun:true }, createdAt:new Date().toISOString() }); }}
export class RelativeValuationValidationExecutor { run(context){ return Object.freeze({ relativeValuationExecutionId:context.relativeValuationExecutionId, validationResult:new RelativeValuationInputValidator().validate(context.input), auditResult:{ validation:true }, createdAt:new Date().toISOString() }); }}
export class RelativeValuationCalculationExecutor { run(context){ const assumptions=new RelativeValuationAssumptionBundle(context.input); const stats=new MultipleStatisticsEngine().calculate(assumptions); const formula=new RelativeValuationFormulaEngine().execute(assumptions, stats.selectedMultiple); const result=Object.freeze({ relativeValuationExecutionId:context.relativeValuationExecutionId, valuationExecutionId:context.valuationExecutionId, valuationInputPackageId:context.valuationInputPackageId, pluginVersion:context.pluginVersion, formulaVersion:RELATIVE_VALUATION_FORMULA_VERSION, selectedMethod:assumptions.selectedMethod, outlierPolicy:assumptions.outlierPolicy, statisticalMethod:assumptions.statisticalMethod, selectedMultiple:stats.selectedMultiple, enterpriseValue:formula.enterpriseValue, equityValue:formula.equityValue, perShareValue:formula.perShareValue, currency:formula.currency, peerStatistics:Object.freeze({ mean:stats.mean, median:stats.median, trimmedMean:stats.trimmedMean, winsorized:stats.winsorized }), peerStatisticsTrace:stats.trace, formulaTrace:formula.formulaTrace, assumptions, structuralConfidence:assumptions.missingMetricPolicy==='manualOverride'?StructuralConfidence.manualOverride:StructuralConfidence.completeInputs, validationResult:{ status:'Passed', errors:[] }, auditResult:{ calculated:true }, createdAt:new Date().toISOString() }); assertNoRelativeDecisionLogic(result,'Relative valuation result'); return result; }}
export class RelativeValuationExecutionAdapter { constructor(){ this.dryRunExecutor=new RelativeValuationDryRunExecutor(); this.validationExecutor=new RelativeValuationValidationExecutor(); this.calculationExecutor=new RelativeValuationCalculationExecutor(); } createContext(input){ return new RelativeValuationExecutionContext(input); } dryRun(context){ return this.dryRunExecutor.run(context); } validate(context){ return this.validationExecutor.run(context); } calculate(context){ return this.calculationExecutor.run(context); }}
export const RelativeValuationExecutionResult=Object.freeze({});
