import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const RECOMMENDATION_SCHEMA_VERSION = 'RECOMMENDATION_SCHEMA_VERSION_1.0';
export const RECOMMENDATION_FRAMEWORK_FEATURE_FLAG = 'recommendation_framework_foundation';
export const RecommendationFrameworkEventType = Object.freeze({ RecommendationModelRegistered:'RecommendationModelRegistered', RecommendationConfigurationRegistered:'RecommendationConfigurationRegistered', RecommendationInputPackageCreated:'RecommendationInputPackageCreated', RecommendationPolicyRegistered:'RecommendationPolicyRegistered', RecommendationPolicyEvaluated:'RecommendationPolicyEvaluated', RecommendationRationaleCreated:'RecommendationRationaleCreated', RecommendationArtifactCreated:'RecommendationArtifactCreated', RecommendationAuditRecorded:'RecommendationAuditRecorded', RecommendationSnapshotCreated:'RecommendationSnapshotCreated', RecommendationReplayCompleted:'RecommendationReplayCompleted' });
export const RecommendationFrameworkCommandType = Object.freeze({ RegisterRecommendationModel:'RegisterRecommendationModel', RegisterRecommendationConfiguration:'RegisterRecommendationConfiguration', CreateRecommendationInputPackage:'CreateRecommendationInputPackage', RegisterRecommendationPolicy:'RegisterRecommendationPolicy', EvaluateRecommendationPolicy:'EvaluateRecommendationPolicy', CreateRecommendationRationale:'CreateRecommendationRationale', CreateRecommendationArtifact:'CreateRecommendationArtifact', RecordRecommendationAudit:'RecordRecommendationAudit', CreateRecommendationSnapshot:'CreateRecommendationSnapshot', ReplayRecommendationArtifact:'ReplayRecommendationArtifact' });
export const RecommendationModelStatus = Object.freeze({ draft:'draft', active:'active', deprecated:'deprecated', retired:'retired' });
export const RecommendationLifecycleState = Object.freeze({ Draft:'Draft', Registered:'Registered', Validated:'Validated', Active:'Active', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const RecommendationArtifactLifecycleState = Object.freeze({ Draft:'Draft', Generated:'Generated', Validated:'Validated', Published:'Published', Archived:'Archived' });
export const RecommendationExecutionStatus = Object.freeze({ Prepared:'Prepared', PolicyEvaluated:'PolicyEvaluated', RationaleCreated:'RationaleCreated', ArtifactCreated:'ArtifactCreated', Failed:'Failed' });
export const RecommendationInputType = Object.freeze({ scoreArtifact:'score-artifact', evidenceReference:'evidence-reference', methodologyReference:'methodology-reference', researchReference:'research-reference', valuationReference:'valuation-reference' });
export const RecommendationArtifactStatus = Object.freeze({ Draft:'Draft', Generated:'Generated', Validated:'Validated', Published:'Published', Archived:'Archived' });
export const RecommendationPermissionAction = Object.freeze({ viewRecommendationArtifact:'viewRecommendationArtifact', registerRecommendationModel:'registerRecommendationModel', configureRecommendationModel:'configureRecommendationModel', evaluateRecommendationPolicy:'evaluateRecommendationPolicy', createRecommendationArtifact:'createRecommendationArtifact', readRecommendationAudit:'readRecommendationAudit', replayRecommendationArtifact:'replayRecommendationArtifact' });
export const RecommendationConfidenceSignal = Object.freeze({ requiredInputsPresent:'requiredInputsPresent', policyEvaluationCompleted:'policyEvaluationCompleted', rationaleComplete:'rationaleComplete', replayVerified:'replayVerified', auditComplete:'auditComplete' });
export const RecommendationDirection = Object.freeze({ constructive:'constructive', neutral:'neutral', cautious:'cautious', avoid:'avoid', insufficientInformation:'insufficient-information' });
const forbidden=Object.freeze(['buy','sell','hold','approve','reject','trade','rebalance','portfolio','position sizing','order','execution','capital allocation','mandate compliance','decision automation','final approval','score calculation','valuation calculation']);
export function assertRequired(record, fields, label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoDecisionLogic(value,label='recommendation'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z ]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden decision/execution logic: ${term}`); } return true; }
export function validateRecommendationCommand(type){ if(!Object.values(RecommendationFrameworkCommandType).includes(type)) throw new Error(`Unsupported recommendation command: ${type}`); assertNoDecisionLogic(type,'recommendation command'); return true; }
export function createRecommendationAuditIdentity({ recommendationArtifactId=null, recommendationModelId, recommendationModelVersion, userId='system', correlationId }={}){ assertRequired({ recommendationModelId, recommendationModelVersion, userId, correlationId }, ['recommendationModelId','recommendationModelVersion','userId','correlationId'], 'recommendationAudit'); return Object.freeze({ recommendationActionId:createOpaqueId('RACT'), recommendationArtifactId, recommendationModelId, recommendationModelVersion, userId, correlationId, timestamp:new Date().toISOString() }); }
