import { TerminalValueAssumptionType, DCFErrorCode, assertNoInvestmentDecision, finiteNumber } from '../contracts/index.js';
export class DCFValidationError extends Error { constructor(code, message){ super(message); this.code=code; } }
export class DCFInputValidator { validate(input){ const errors=[]; if(!input) errors.push(error(DCFErrorCode.MISSING_ASSUMPTION,'DCF input is required')); if(!Array.isArray(input?.forecastCashFlows)||input.forecastCashFlows.length===0) errors.push(error(DCFErrorCode.MISSING_ASSUMPTION,'forecastCashFlows are required')); for(const cf of input?.forecastCashFlows||[]){ if(!cf.period||cf.cashFlow===undefined||!cf.currency||!cf.periodEndDate) errors.push(error(DCFErrorCode.MISSING_ASSUMPTION,'cash-flow period/cashFlow/currency/periodEndDate required')); if(cf.cashFlow!==undefined && (!Number.isFinite(cf.cashFlow))) errors.push(error(DCFErrorCode.NUMERICAL_OVERFLOW,'cashFlow must be finite')); }
 if(typeof input?.discountRate!=='number'||!Number.isFinite(input.discountRate)||input.discountRate<=-1) errors.push(error(DCFErrorCode.INVALID_DISCOUNT_RATE,'discountRate must be finite and greater than -100%')); const tv=input?.terminalValueAssumption; if(!tv?.type||!Object.values(TerminalValueAssumptionType).includes(tv.type)) errors.push(error(DCFErrorCode.UNSUPPORTED_TERMINAL_VALUE_ASSUMPTION,'unsupported terminal assumption')); if(tv?.type===TerminalValueAssumptionType.perpetualGrowth && (typeof tv.terminalGrowthRate!=='number'||tv.terminalGrowthRate>=input.discountRate)) errors.push(error(DCFErrorCode.INVALID_TERMINAL_GROWTH,'terminal growth must be below discount rate')); if(input?.dilutedSharesOutstanding!==undefined && input.dilutedSharesOutstanding<=0) errors.push(error(DCFErrorCode.NEGATIVE_SHARE_COUNT,'share count must be positive')); for(const forbidden of ['marketData','providerData','financialStatements','generatedForecast']) if(input?.[forbidden]!==undefined) errors.push(error(DCFErrorCode.MISSING_ASSUMPTION,`Forbidden generated/input field: ${forbidden}`)); assertNoInvestmentDecision(input,'DCF input'); return Object.freeze({ status:errors.length?'Failed':'Passed', errors:Object.freeze(errors) }); }}
export class DCFAssumptionSet { constructor(input){ const normalized=new DCFInputNormalizer().normalize(input); const validation=new DCFInputValidator().validate(normalized); if(validation.status==='Failed') throw new DCFValidationError(validation.errors[0].code, validation.errors[0].message); return deepFreeze(normalized); } }
export class DCFInputNormalizer { normalize(input){ return { valuationInputPackageId:input.valuationInputPackageId, companyId:input.companyId, securityId:input.securityId, currency:input.currency, forecastCashFlows:[...(input.forecastCashFlows||[])], discountRate:input.discountRate, terminalValueAssumption:{ ...(input.terminalValueAssumption||{}) }, netDebt:input.netDebt||0, minorityInterest:input.minorityInterest||0, investmentsAndCash:input.investmentsAndCash||0, dilutedSharesOutstanding:input.dilutedSharesOutstanding, assumptionsVersion:input.assumptionsVersion||'DCF_ASSUMPTIONS_1.0', createdAt:input.createdAt||new Date().toISOString() }; }}
export const DCFInputPackage = DCFAssumptionSet;
function error(code,message){ return Object.freeze({ code, message }); }
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
