import { FlagStatus } from '../../../../packages/feature-flags/src/index.js';
import { InMemorySnapshotStore } from '../../../../packages/snapshot-engine/src/index.js';
import { METHODOLOGY_FRAMEWORK_FEATURE_FLAG } from './contracts/index.js';
import { MethodologyDefinitionRegistry, MethodologyVersionRegistry } from './definitions/index.js';
import { MethodologyFrameworkRegistryAdapter } from './registry/index.js';
import { MethodologyLifecycleManager } from './lifecycle/index.js';
import { MethodologyConfigurationRegistry } from './configuration/index.js';
import { EvidenceRequirementEngine, EvidenceSufficiencyChecker, CertifiedEvidenceInputAdapter } from './evidence-inputs/index.js';
import { MethodologyExecutionRuntime } from './execution/index.js';
import { MethodologyAuditTrail } from './audit/index.js';
import { MethodologySnapshotAdapter } from './snapshots/index.js';
import { MethodologyReplayAdapter } from './replay/index.js';
import { MethodologyPermissionRegistry, MethodologyPermissionGate, registerDefaultMethodologyPermissions } from './permissions/index.js';
import { MethodologyContributionRegistry } from './contributions/index.js';
import { MethodologyProjectionRegistry } from './projections/index.js';
import { MethodologyDiagnostics } from './diagnostics/index.js';
import { MethodologyIntegrationHarness } from './testing/index.js';

export function createMethodologyFrameworkFoundation({ app } = {}) {
  const container=app.container;
  const flags=container.resolve('featureFlagRegistry');
  if(!flags.get(METHODOLOGY_FRAMEWORK_FEATURE_FLAG)) flags.register({ flag_id:METHODOLOGY_FRAMEWORK_FEATURE_FLAG, default_enabled:true, owner:'methodology-framework', status:FlagStatus.active });
  const diagnostics=new MethodologyDiagnostics({ diagnostics:container.resolve('diagnostics') });
  const definitionRegistry=new MethodologyDefinitionRegistry({ diagnostics });
  const versionRegistry=new MethodologyVersionRegistry();
  const registryAdapter=new MethodologyFrameworkRegistryAdapter({ methodologyRegistry:container.resolve('methodologyRegistry'), diagnostics });
  const lifecycleManager=new MethodologyLifecycleManager({ diagnostics });
  const configurationRegistry=new MethodologyConfigurationRegistry();
  const requirementEngine=new EvidenceRequirementEngine();
  const sufficiencyChecker=new EvidenceSufficiencyChecker();
  const evidenceInputAdapter=new CertifiedEvidenceInputAdapter();
  const executionRuntime=new MethodologyExecutionRuntime({ lifecycleManager, sufficiencyChecker });
  const auditTrail=new MethodologyAuditTrail();
  const snapshotStore=new InMemorySnapshotStore();
  const snapshotAdapter=new MethodologySnapshotAdapter({ snapshotStore });
  const replayAdapter=new MethodologyReplayAdapter();
  const permissionRegistry=registerDefaultMethodologyPermissions(new MethodologyPermissionRegistry());
  const permissionGate=new MethodologyPermissionGate({ registry:permissionRegistry });
  const contributionRegistry=new MethodologyContributionRegistry({ featureFlagRegistry:flags, permissionGate });
  contributionRegistry.register({ contributionId:'register-methodology', permission:'registerMethodology' });
  contributionRegistry.register({ contributionId:'run-methodology-dry-run', permission:'runMethodologyDryRun' });
  contributionRegistry.register({ contributionId:'run-methodology-validation', permission:'runMethodologyValidation' });
  const projectionRegistry=new MethodologyProjectionRegistry().registerDefaults();
  const runtime=Object.freeze({ diagnostics, definitionRegistry, versionRegistry, registryAdapter, lifecycleManager, configurationRegistry, requirementEngine, sufficiencyChecker, evidenceInputAdapter, executionRuntime, auditTrail, snapshotStore, snapshotAdapter, replayAdapter, permissionRegistry, permissionGate, contributionRegistry, projectionRegistry });
  const methodologyTestHarness=new MethodologyIntegrationHarness({ runtime });
  const full=Object.freeze({ ...runtime, methodologyTestHarness });
  for(const [key,value] of Object.entries(full)) if(!container.has(key)) container.register(key,value);
  return full;
}
