import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';
import { ResearchDocumentType, ResearchLifecycleState, assertNoResearchIntelligence, validateSubject } from '../contracts/index.js';
export class ResearchDocumentOutline { constructor(sections=[]){ this.sections=Object.freeze(sections.slice()); } }
export class ResearchDocumentSection { constructor({ sectionId, title, notes='' }){ if(!sectionId||!title) throw new Error('sectionId and title are required'); assertNoResearchIntelligence({ title, notes }, 'Research document section'); return Object.freeze({ sectionId, title, notes }); } }
export class ResearchDocumentLifecycle { transition(from,to){ if(!Object.values(ResearchLifecycleState).includes(to)) throw new Error(`Invalid document status: ${to}`); if(from===ResearchLifecycleState.Archived) throw new Error('Archived documents cannot transition'); return to; } }
export class ResearchDocumentRegistry { constructor({ diagnostics }={}){ this.documents=new Map(); this.lifecycle=new ResearchDocumentLifecycle(); this.diagnostics=diagnostics; }
  create({ documentType, title, workflowInstanceId, subject=null, outline=[] } = {}){ if(!Object.values(ResearchDocumentType).includes(documentType)) throw new Error(`Invalid research document type: ${documentType}`); validateSubject(subject); assertNoResearchIntelligence({ documentType, title, subject, outline }, 'Research document'); const now=new Date().toISOString(); const doc=deepFreeze({ researchDocumentId:createOpaqueId('RDOC'), researchDocumentVersion:1, documentType, title, workflowInstanceId, subject, outline:Object.freeze(outline.slice()), artifactIds:Object.freeze([]), status:ResearchLifecycleState.Draft, createdAt:now, updatedAt:now }); this.documents.set(doc.researchDocumentId, doc); this.diagnostics?.record?.('documentCreates', { researchDocumentId:doc.researchDocumentId }); return doc; }
  updateOutline(id, outline){ const doc=this.get(id); assertNoResearchIntelligence(outline, 'Research document outline'); const next=deepFreeze({ ...doc, researchDocumentVersion:doc.researchDocumentVersion+1, outline:Object.freeze(outline.slice()), updatedAt:new Date().toISOString(), status:ResearchLifecycleState.Active }); this.documents.set(id,next); return next; }
  archive(id){ const doc=this.get(id); const status=this.lifecycle.transition(doc.status, ResearchLifecycleState.Archived); const next=deepFreeze({ ...doc, status, updatedAt:new Date().toISOString() }); this.documents.set(id,next); return next; }
  linkArtifact(id, artifactId){ const doc=this.get(id); const next=deepFreeze({ ...doc, researchDocumentVersion:doc.researchDocumentVersion+1, artifactIds:Object.freeze([...doc.artifactIds, artifactId]), updatedAt:new Date().toISOString() }); this.documents.set(id,next); return next; }
  get(id){ const doc=this.documents.get(id); if(!doc) throw new Error(`Research document not found: ${id}`); return doc; }
  byWorkflow(workflowInstanceId){ return Object.freeze([...this.documents.values()].filter(d=>d.workflowInstanceId===workflowInstanceId)); }
  bySubject(subjectId){ return Object.freeze([...this.documents.values()].filter(d=>d.subject?.id===subjectId)); }}
export const ResearchDocument = Object.freeze({});
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
