import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
import { MethodologyDefinitionStatus, MethodologyCapability, assertNoInvestmentAnalysis, assertRequired } from '../contracts/index.js';

const allowedOutputs = new Set(['validationResult','sufficiencyResult','auditResult','replayResult']);
export class MethodologyManifestValidator { validate(manifest){ assertRequired(manifest,['methodologyId','methodologyVersion','name','owner','status','contractVersion','minimumPlatformVersion','evidenceRequirements','configurationSchema','validationRules','outputContract','capabilities','analysisExtensions','createdAt'],'methodologyManifest'); if(!Object.values(MethodologyDefinitionStatus).includes(manifest.status)) throw new Error(`Invalid methodology status: ${manifest.status}`); for(const cap of manifest.capabilities) if(!Object.values(MethodologyCapability).includes(cap)) throw new Error(`Unsupported capability: ${cap}`); if(manifest.analysisExtensions.length>0) throw new Error('analysisExtensions must remain empty in Sprint 7'); for(const output of manifest.outputContract) if(!allowedOutputs.has(output)) throw new Error(`Forbidden methodology output: ${output}`); assertNoInvestmentAnalysis(manifest,'Methodology manifest'); return true; } }
export class MethodologyDefinitionRegistry { constructor({ diagnostics }={}){ this.definitions=new Map(); this.validator=new MethodologyManifestValidator(); this.diagnostics=diagnostics; this.active=new Set(); }
  register(manifest){ const record=deepFreeze({ description:'', ...manifest }); this.validator.validate(record); const key=this.key(record.methodologyId,record.methodologyVersion); if(this.definitions.has(key)) throw new Error(`Methodology version already registered: ${key}`); this.definitions.set(key,record); this.diagnostics?.record?.('methodology.definition.registered',{ methodologyId:record.methodologyId }); return record; }
  activate(id,version){ const m=this.get(id,version); this.active.add(this.key(id,version)); return m; }
  update(id,version,patch){ if(this.active.has(this.key(id,version))) throw new Error('Active methodology definition is immutable'); const m=this.get(id,version); const next=deepFreeze({ ...m, ...patch }); this.validator.validate(next); this.definitions.set(this.key(id,version),next); return next; }
  get(id,version){ const m=this.definitions.get(this.key(id,version)); if(!m) throw new Error(`Methodology not found: ${id}@${version}`); return m; } key(id,v){ return `${id}@${v}`; } list(){ return Object.freeze([...this.definitions.values()]); }}
export class MethodologyVersionRegistry { constructor(){ this.versions=new Map(); } add(manifest){ const list=this.versions.get(manifest.methodologyId)||[]; list.push(manifest.methodologyVersion); this.versions.set(manifest.methodologyId,Object.freeze([...new Set(list)])); return this.versions.get(manifest.methodologyId); } list(id){ return this.versions.get(id)||Object.freeze([]); }}
export function createPlaceholderMethodologyManifest(overrides={}){ return deepFreeze({ methodologyId:'MTH_FRAMEWORK_PLACEHOLDER', methodologyVersion:'1.0.0', name:'Framework Placeholder Methodology', description:'Governance-only methodology shell.', owner:'methodology-framework', status:'draft', contractVersion:'1.0', minimumPlatformVersion:'2.0.0', evidenceRequirements:[], configurationSchema:{ required:[] }, validationRules:[], outputContract:['validationResult','sufficiencyResult','auditResult','replayResult'], capabilities:['validation','sufficiency','replay','audit'], analysisExtensions:[], createdAt:new Date().toISOString(), ...overrides }); }
export const MethodologyDefinition = Object.freeze({}); export const MethodologyManifest = Object.freeze({});
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
