import { assertNoInvestmentAnalysis } from '../contracts/index.js';
class BaseProjection { constructor({ projectionId, supportedEvents }){ this.definition=Object.freeze({ projectionId, snapshotCompatible:true, projectionVersion:'1.0.0', supportedEvents:Object.freeze(supportedEvents) }); this.state=Object.freeze({}); } apply(event){ if(!this.definition.supportedEvents.includes(event.type)) throw new Error(`Unsupported Research Intelligence event: ${event.type}`); assertNoInvestmentAnalysis(event,'Research Intelligence projection event'); this.state=deepFreeze({ ...this.state, lastEventType:event.type, payload:event.payload||{}, updatedAt:new Date().toISOString() }); return this.state; } snapshot(){ return deepFreeze({ definition:this.definition, state:this.state }); }}
export class ResearchTemplateProjection extends BaseProjection { constructor(){ super({ projectionId:'ri.templates', supportedEvents:['ResearchTemplateRegistered','ResearchTemplateApplied'] }); }}
export class ResearchSectionProjection extends BaseProjection { constructor(){ super({ projectionId:'ri.sections', supportedEvents:['ResearchSectionCreated','ResearchSectionUpdated','AnalystNoteCreated','AnalystNoteUpdated'] }); }}
export class ResearchReviewProjection extends BaseProjection { constructor(){ super({ projectionId:'ri.review', supportedEvents:['ResearchReviewStarted','ResearchReviewSubmitted','ResearchReviewReturned','ResearchReviewCompleted'] }); }}
export class ResearchChecklistProjection extends BaseProjection { constructor(){ super({ projectionId:'ri.checklist', supportedEvents:['ResearchChecklistItemCreated','ResearchChecklistItemCompleted'] }); }}
export class ResearchCompletenessProjection extends BaseProjection { constructor(){ super({ projectionId:'ri.completeness', supportedEvents:['ResearchCompletenessChecked'] }); }}
export class ResearchEvidenceCandidateProjection extends BaseProjection { constructor(){ super({ projectionId:'ri.evidenceCandidates', supportedEvents:['EvidenceCandidateCreated','EvidenceCandidateLinked'] }); }}
export class ResearchCollaborationProjection extends BaseProjection { constructor(){ super({ projectionId:'ri.collaboration', supportedEvents:['ResearchCommentAdded','ResearchCollaborationActivityRecorded'] }); }}
export class ResearchIntelligenceProjectionRegistry { constructor(){ this.projections=new Map(); } register(p){ if(this.projections.has(p.definition.projectionId)) throw new Error(`Projection exists: ${p.definition.projectionId}`); this.projections.set(p.definition.projectionId,p); return p; } registerDefaults(){ [new ResearchTemplateProjection(),new ResearchSectionProjection(),new ResearchReviewProjection(),new ResearchChecklistProjection(),new ResearchCompletenessProjection(),new ResearchEvidenceCandidateProjection(),new ResearchCollaborationProjection()].forEach(p=>{ if(!this.projections.has(p.definition.projectionId)) this.register(p); }); return this; } update(id,event){ return this.get(id).apply(event); } get(id){ const p=this.projections.get(id); if(!p) throw new Error(`Projection not found: ${id}`); return p; }}
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
