import { RELATIVE_VALUATION_FORMULA_VERSION, RelativeValuationMethod } from '../contracts/index.js';
import { RelativeValuationMethodRegistry } from '../methods/index.js';
export class RelativeValuationFormulaTrace { constructor(){ this.steps=[]; } record(step,value,meta={}){ const r=Object.freeze({ step,value,meta:Object.freeze({ ...meta }) }); this.steps.push(r); return r; } list(){ return Object.freeze(this.steps.slice()); }}
export class EnterpriseValueFromMultipleCalculator { calculate(metric, multiple){ return metric*multiple; }}
export class EquityValueFromMultipleCalculator { calculate(metric, multiple){ return metric*multiple; }}
export class RelativeEquityBridge { calculate({ enterpriseValue, netDebt=0, minorityInterest=0, investmentsAndCash=0 }){ return enterpriseValue==null?null:enterpriseValue-netDebt-minorityInterest+investmentsAndCash; }}
export class RelativePerShareValueCalculator { calculate(equityValue, shares){ if(shares===undefined||equityValue==null) return null; if(shares<=0) throw new Error('share count must be positive'); return equityValue/shares; }}
export class RelativeValuationFormulaEngine { constructor(){ this.methods=new RelativeValuationMethodRegistry(); this.evCalc=new EnterpriseValueFromMultipleCalculator(); this.eqCalc=new EquityValueFromMultipleCalculator(); this.bridge=new RelativeEquityBridge(); this.perShare=new RelativePerShareValueCalculator(); }
  execute(input, selectedMultiple){ const def=this.methods.get(input.selectedMethod); const trace=new RelativeValuationFormulaTrace(); trace.record('selected-method', input.selectedMethod, { valuationBasis:def.valuationBasis }); trace.record('selected-multiple', selectedMultiple); let enterpriseValue=null; let equityValue=null; if(def.valuationBasis==='enterprise'){ enterpriseValue=this.evCalc.calculate(input.companyMetric, selectedMultiple); trace.record('enterprise-value', enterpriseValue); equityValue=this.bridge.calculate({ enterpriseValue, netDebt:input.customInputs.netDebt||0, minorityInterest:input.customInputs.minorityInterest||0, investmentsAndCash:input.customInputs.investmentsAndCash||0 }); trace.record('equity-value', equityValue); } else { equityValue=this.eqCalc.calculate(input.companyMetric, selectedMultiple); trace.record('equity-value', equityValue); } const perShareValue=this.perShare.calculate(equityValue, input.shareCount); trace.record('per-share-value', perShareValue); return Object.freeze({ formulaVersion:RELATIVE_VALUATION_FORMULA_VERSION, selectedMethod:input.selectedMethod, selectedMultiple, enterpriseValue, equityValue, perShareValue, currency:input.currency, formulaTrace:trace.list() }); }}
