import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const VALUATION_NORMALIZATION_VERSION='VALUATION_NORMALIZATION_VERSION_1.0';
export const CANONICAL_VALUATION_SCHEMA_VERSION='CANONICAL_VALUATION_SCHEMA_1.0';
export const ValuationNormalizationEventType=Object.freeze({ ValuationResultNormalized:'ValuationResultNormalized', ValuationContributionAdded:'ValuationContributionAdded', ValuationContributionValidated:'ValuationContributionValidated', ValuationResultVersionCreated:'ValuationResultVersionCreated', ValuationResultAudited:'ValuationResultAudited', ValuationResultSnapshotCreated:'ValuationResultSnapshotCreated', ValuationResultReplayCompleted:'ValuationResultReplayCompleted', ValuationComparisonCreated:'ValuationComparisonCreated' });
export const ValuationNormalizationCommandType=Object.freeze({ NormalizeValuationArtifact:'NormalizeValuationArtifact', AddValuationContribution:'AddValuationContribution', ValidateValuationContribution:'ValidateValuationContribution', CreateValuationResultVersion:'CreateValuationResultVersion', RecordValuationResultAudit:'RecordValuationResultAudit', CreateValuationResultSnapshot:'CreateValuationResultSnapshot', ReplayValuationResult:'ReplayValuationResult', CreateValuationComparison:'CreateValuationComparison' });
export const ValuationResultStatus=Object.freeze({ Draft:'Draft', Active:'Active', Archived:'Archived' });
export const ValuationContributionType=Object.freeze({ DCF:'DCF', RelativeValuation:'RelativeValuation', Future:'Future' });
export const ValuationArtifactSourceType=Object.freeze({ DCF:'DCF', RelativeValuation:'RelativeValuation' });
export const ValuationNormalizationStatus=Object.freeze({ Normalized:'Normalized', Failed:'Failed' });
export const ValuationNormalizationPermissionAction=Object.freeze({ viewValuationResult:'viewValuationResult', normalizeValuationArtifact:'normalizeValuationArtifact', createValuationResultVersion:'createValuationResultVersion', readValuationResultAudit:'readValuationResultAudit', replayValuationResult:'replayValuationResult' });
export const ValuationConfidenceSignal=Object.freeze({ allRequiredInputsPresent:'allRequiredInputsPresent', replaySuccessful:'replaySuccessful', auditComplete:'auditComplete', assumptionsComplete:'assumptionsComplete', methodologyValidated:'methodologyValidated' });
const forbidden=Object.freeze(['consensus','weighted average','preferred method','score','rating','recommendation','recommendations','buy','sell','hold','portfolio','decision automation','investment conviction','probability of success']);
export function assertRequired(r,fields,label='record'){ for(const f of fields) if(r?.[f]===undefined||r?.[f]===null||r?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoInvestmentDecision(v,label='normalization'){ const text=JSON.stringify(v||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z ]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden decision/consensus logic: ${term}`); } return true; }
export function validateNormalizationCommand(type){ if(!Object.values(ValuationNormalizationCommandType).includes(type)) throw new Error(`Unsupported normalization command: ${type}`); assertNoInvestmentDecision(type,'normalization command'); return true; }
export function createNormalizationAuditIdentity({ valuationResultId=null, valuationArtifactId=null, userId='system', correlationId }={}){ assertRequired({ userId, correlationId }, ['userId','correlationId'], 'normalizationAudit'); return Object.freeze({ normalizationActionId:createOpaqueId('VNORM'), valuationResultId, valuationArtifactId, userId, correlationId, timestamp:new Date().toISOString() }); }
export function checksum(value){ const text=JSON.stringify(value); let h=0; for(let i=0;i<text.length;i++) h=(Math.imul(31,h)+text.charCodeAt(i))|0; return `CHK_${(h>>>0).toString(16).toUpperCase()}`; }
