import { assertNoInvestmentLogic } from '../contracts/index.js';
import { createPlaceholderProductModuleManifests } from '../registry/index.js';
import { ProductLifecycleState } from '../lifecycle/index.js';
export class ProductGuardrailAssertions { assertNoValuationLogic(v){ return assertNoInvestmentLogic(v,'valuation guardrail'); } assertNoScoringLogic(v){ return assertNoInvestmentLogic(v,'scoring guardrail'); } assertNoPortfolioCalculation(v){ return assertNoInvestmentLogic(v,'portfolio guardrail'); } assertNoMarketDataIntegration(v){ return assertNoInvestmentLogic(v,'market data guardrail'); } assertNoInvestmentRecommendation(v){ return assertNoInvestmentLogic(v,'recommendation guardrail'); } assertNoDecisionAutomation(v){ return assertNoInvestmentLogic(v,'decision automation guardrail'); } assertNoMethodologyImplementation(v){ return assertNoInvestmentLogic(v,'methodology guardrail'); } }
export class ProductManifestFixtureFactory { create(overrides={}){ return Object.freeze({ ...createPlaceholderProductModuleManifests()[0], ...overrides }); } }
export class ProductModuleTestHarness {
  constructor({ productRuntime }={}){ this.productRuntime=productRuntime; this.fixtures=new ProductManifestFixtureFactory(); this.guardrails=new ProductGuardrailAssertions(); }
  createFixture(overrides={}){ return this.fixtures.create(overrides); }
  registerModule(manifest){ this.guardrails.assertNoValuationLogic(manifest); return this.productRuntime.productModuleRegistry.register(manifest); }
  runLifecycle(productModuleId){ const lm=this.productRuntime.productLifecycleManager; lm.discover(productModuleId); lm.transition(productModuleId, ProductLifecycleState.Validated); lm.transition(productModuleId, ProductLifecycleState.Registered); lm.transition(productModuleId, ProductLifecycleState.Bound); lm.transition(productModuleId, ProductLifecycleState.Enabled); return lm.transition(productModuleId, ProductLifecycleState.Mounted); }
  bindModule(manifest){ const wb=this.productRuntime.productWorkspaceBinder.register(manifest.workspaceBindings[0]); const fb=this.productRuntime.productWorkflowBinder.register(manifest.workflowBindings[0]); return Object.freeze({ workspaceBinding:wb, workflowBinding:fb }); }
  assertNoForbiddenInvestmentLogic(value){ this.guardrails.assertNoValuationLogic(value); this.guardrails.assertNoScoringLogic(value); this.guardrails.assertNoPortfolioCalculation(value); this.guardrails.assertNoMarketDataIntegration(value); this.guardrails.assertNoInvestmentRecommendation(value); this.guardrails.assertNoDecisionAutomation(value); this.guardrails.assertNoMethodologyImplementation(value); return true; }
}
export class ProductIntegrationHarness extends ProductModuleTestHarness { runShellWorkflowProductIntegration({ manifest, workflowContext }){ const registered=this.registerModule(manifest); const bindings=this.bindModule(manifest); const mounted=this.productRuntime.productWorkspaceBinder.mountPlaceholder(bindings.workspaceBinding, workflowContext); const productContext=this.productRuntime.productContextBridge.project({ productModuleId:manifest.productModuleId, workflowContext, permissions:manifest.permissions }); return Object.freeze({ registered, bindings, mounted, productContext }); } }
