import { ResearchEventType, assertNoResearchIntelligence } from '../contracts/index.js';
export const ResearchProjectionCategory = Object.freeze({ workspaceSummary:'workspaceSummary', documentSummary:'documentSummary', artifactSummary:'artifactSummary', activitySummary:'activitySummary', contextSummary:'contextSummary' });
class BaseResearchProjection { constructor({ projectionId, category, supportedEvents }){ this.definition=Object.freeze({ projectionId, category, snapshotCompatible:true, projectionVersion:'1.0.0', supportedEvents:Object.freeze(supportedEvents) }); this.state=Object.freeze({}); }
  apply(event){ if(!this.definition.supportedEvents.includes(event.type)) throw new Error(`Unsupported Research projection event: ${event.type}`); assertNoResearchIntelligence(event, 'Research projection event'); this.state=deepFreeze({ ...this.state, lastEventType:event.type, updatedAt:new Date().toISOString(), payload:event.payload||{} }); return this.state; }
  snapshot(){ return deepFreeze({ definition:this.definition, state:this.state }); }}
export class ResearchWorkspaceProjection extends BaseResearchProjection { constructor(){ super({ projectionId:'research.workspace', category:ResearchProjectionCategory.workspaceSummary, supportedEvents:[ResearchEventType.ResearchWorkspaceOpened, ResearchEventType.ResearchContextProjected] }); }}
export class ResearchDocumentProjection extends BaseResearchProjection { constructor(){ super({ projectionId:'research.documents', category:ResearchProjectionCategory.documentSummary, supportedEvents:[ResearchEventType.ResearchDocumentCreated, ResearchEventType.ResearchDocumentUpdated] }); }}
export class ResearchArtifactProjection extends BaseResearchProjection { constructor(){ super({ projectionId:'research.artifacts', category:ResearchProjectionCategory.artifactSummary, supportedEvents:[ResearchEventType.ResearchArtifactRegistered, ResearchEventType.ResearchArtifactLinked, ResearchEventType.ResearchArtifactArchived] }); }}
export class ResearchActivityProjection extends BaseResearchProjection { constructor(){ super({ projectionId:'research.activity', category:ResearchProjectionCategory.activitySummary, supportedEvents:[ResearchEventType.ResearchActivityRecorded] }); }}
export class ResearchProjectionRegistry { constructor(){ this.projections=new Map(); }
  register(projection){ if(this.projections.has(projection.definition.projectionId)) throw new Error(`Research projection already registered: ${projection.definition.projectionId}`); this.projections.set(projection.definition.projectionId, projection); return projection; }
  registerDefaults(){ [new ResearchWorkspaceProjection(), new ResearchDocumentProjection(), new ResearchArtifactProjection(), new ResearchActivityProjection()].forEach(p=>{ if(!this.projections.has(p.definition.projectionId)) this.register(p); }); return this; }
  update(id,event){ const p=this.get(id); return p.apply(event); }
  get(id){ const p=this.projections.get(id); if(!p) throw new Error(`Research projection not found: ${id}`); return p; }}
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
