import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';

export const VALUATION_FRAMEWORK_FEATURE_FLAG = 'valuation_framework_foundation';
export const VALUATION_FRAMEWORK_SCHEMA_VERSION = 'VALUATION_FRAMEWORK_SCHEMA_1.0';
export const VALUATION_EXECUTION_ENVIRONMENT_VERSION = 'VALUATION_EXECUTION_ENVIRONMENT_1.0';
export const ValuationFrameworkEventType = Object.freeze({ ValuationModelRegistered:'ValuationModelRegistered', ValuationVersionCreated:'ValuationVersionCreated', ValuationModelActivated:'ValuationModelActivated', ValuationModelDeprecated:'ValuationModelDeprecated', ValuationModelRetired:'ValuationModelRetired', ValuationConfigurationRegistered:'ValuationConfigurationRegistered', ValuationInputPackageCreated:'ValuationInputPackageCreated', ValuationDryRunStarted:'ValuationDryRunStarted', ValuationDryRunCompleted:'ValuationDryRunCompleted', ValuationValidationStarted:'ValuationValidationStarted', ValuationValidationCompleted:'ValuationValidationCompleted', ValuationExecutionAudited:'ValuationExecutionAudited', ValuationSnapshotCreated:'ValuationSnapshotCreated', ValuationReplayCompleted:'ValuationReplayCompleted' });
export const ValuationFrameworkCommandType = Object.freeze({ RegisterValuationModel:'RegisterValuationModel', CreateValuationVersion:'CreateValuationVersion', ActivateValuationModel:'ActivateValuationModel', DeprecateValuationModel:'DeprecateValuationModel', RetireValuationModel:'RetireValuationModel', RegisterValuationConfiguration:'RegisterValuationConfiguration', CreateValuationInputPackage:'CreateValuationInputPackage', StartValuationDryRun:'StartValuationDryRun', CompleteValuationDryRun:'CompleteValuationDryRun', StartValuationValidation:'StartValuationValidation', CompleteValuationValidation:'CompleteValuationValidation', RecordValuationAudit:'RecordValuationAudit', CreateValuationSnapshot:'CreateValuationSnapshot', ReplayValuationExecution:'ReplayValuationExecution' });
export const ValuationModelStatus = Object.freeze({ draft:'draft', active:'active', deprecated:'deprecated', retired:'retired' });
export const ValuationLifecycleState = Object.freeze({ Draft:'Draft', Registered:'Registered', Validated:'Validated', Active:'Active', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const ValuationExecutionStatus = Object.freeze({ Prepared:'Prepared', DryRunStarted:'DryRunStarted', DryRunCompleted:'DryRunCompleted', ValidationStarted:'ValidationStarted', ValidationCompleted:'ValidationCompleted', Failed:'Failed' });
export const ValuationInputType = Object.freeze({ companySecurity:'company-security', certifiedEvidence:'certified-evidence', methodologyResult:'methodology-result' });
export const ValuationValidationStatus = Object.freeze({ NotRun:'NotRun', Passed:'Passed', Failed:'Failed' });
export const ValuationPermissionAction = Object.freeze({ viewValuationFramework:'viewValuationFramework', registerValuationModel:'registerValuationModel', activateValuationModel:'activateValuationModel', deprecateValuationModel:'deprecateValuationModel', retireValuationModel:'retireValuationModel', configureValuationModel:'configureValuationModel', createValuationInputPackage:'createValuationInputPackage', runValuationDryRun:'runValuationDryRun', runValuationValidation:'runValuationValidation', readValuationAudit:'readValuationAudit', replayValuationExecution:'replayValuationExecution' });
export const ValuationConfigurationScope = Object.freeze({ global:'global', model:'model', workflow:'workflow', user:'user', execution:'execution' });
export const ValuationModelCategory = Object.freeze({ frameworkPlaceholder:'framework-placeholder', dcf:'dcf', multiples:'multiples', residualIncome:'residual-income', dividendDiscount:'dividend-discount', other:'other' });
export const ValuationCapability = Object.freeze({ inputPackaging:'inputPackaging', validation:'validation', dryRun:'dryRun', replay:'replay', audit:'audit' });
const forbidden = Object.freeze(['discounted cash flow','dcf','multiple','residual income','dividend discount','intrinsic value','fair value','target price','margin of safety','upside','downside','terminal value','cost of capital','wacc','discount rate','forecast','financial statement','price','volume','score','rating','buy','sell','hold','recommendation','portfolio','decision automation','investment opinion']);
export function assertRequired(record, fields, label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoValuationLogic(value,label='Valuation Framework'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pattern=/^[a-z ]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pattern?pattern.test(text):text.includes(term)) throw new Error(`${label} contains forbidden valuation or investment logic: ${term}`); } return true; }
export function validateValuationCommand(type){ if(!Object.values(ValuationFrameworkCommandType).includes(type)) throw new Error(`Unsupported valuation command: ${type}`); assertNoValuationLogic(type,'Valuation command'); return true; }
export function createValuationAuditIdentity({ valuationModelId, valuationModelVersion, valuationExecutionId=null, companyId=null, securityId=null, methodologyId=null, methodologyVersion=null, evidenceRecordIds=[], userId='system', correlationId }={}){ assertRequired({ valuationModelId, valuationModelVersion, userId, correlationId }, ['valuationModelId','valuationModelVersion','userId','correlationId'], 'valuationAudit'); return Object.freeze({ valuationActionId:createOpaqueId('VACT'), valuationModelId, valuationModelVersion, valuationExecutionId, companyId, securityId, methodologyId, methodologyVersion, evidenceRecordIds:Object.freeze(evidenceRecordIds.slice()), userId, correlationId, timestamp:new Date().toISOString() }); }
export function stableValuationFingerprint({ valuationModelVersion, configurationVersion, companyId, securityId, methodologyVersion, evidenceVersionIds=[], valuationExecutionEnvironmentVersion=VALUATION_EXECUTION_ENVIRONMENT_VERSION }={}){ const text=JSON.stringify({ valuationModelVersion, configurationVersion, companyId, securityId, methodologyVersion, evidenceVersionIds:evidenceVersionIds.slice().sort(), valuationExecutionEnvironmentVersion }); let h=0; for(let i=0;i<text.length;i++) h=(Math.imul(31,h)+text.charCodeAt(i))|0; return `VFPR_${(h>>>0).toString(16).toUpperCase().padStart(8,'0')}`; }
