import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const DECISION_SCHEMA_VERSION = 'DECISION_SCHEMA_VERSION_1.0';
export const DECISION_FRAMEWORK_FEATURE_FLAG = 'decision_framework_foundation';
export const DecisionFrameworkEventType = Object.freeze({ DecisionModelRegistered:'DecisionModelRegistered', DecisionConfigurationRegistered:'DecisionConfigurationRegistered', DecisionInputPackageCreated:'DecisionInputPackageCreated', DecisionPolicyRegistered:'DecisionPolicyRegistered', ApprovalPolicyRegistered:'ApprovalPolicyRegistered', DecisionPolicyEvaluated:'DecisionPolicyEvaluated', ApprovalPolicyEvaluated:'ApprovalPolicyEvaluated', DecisionRationaleCreated:'DecisionRationaleCreated', DecisionArtifactCreated:'DecisionArtifactCreated', DecisionAuditRecorded:'DecisionAuditRecorded', DecisionSnapshotCreated:'DecisionSnapshotCreated', DecisionReplayCompleted:'DecisionReplayCompleted' });
export const DecisionFrameworkCommandType = Object.freeze({ RegisterDecisionModel:'RegisterDecisionModel', RegisterDecisionConfiguration:'RegisterDecisionConfiguration', CreateDecisionInputPackage:'CreateDecisionInputPackage', RegisterDecisionPolicy:'RegisterDecisionPolicy', RegisterApprovalPolicy:'RegisterApprovalPolicy', EvaluateDecisionPolicy:'EvaluateDecisionPolicy', EvaluateApprovalPolicy:'EvaluateApprovalPolicy', CreateDecisionRationale:'CreateDecisionRationale', CreateDecisionArtifact:'CreateDecisionArtifact', RecordDecisionAudit:'RecordDecisionAudit', CreateDecisionSnapshot:'CreateDecisionSnapshot', ReplayDecisionArtifact:'ReplayDecisionArtifact' });
export const DecisionModelStatus = Object.freeze({ draft:'draft', active:'active', deprecated:'deprecated', retired:'retired' });
export const DecisionLifecycleState = Object.freeze({ Draft:'Draft', Registered:'Registered', Validated:'Validated', Active:'Active', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const DecisionArtifactLifecycleState = Object.freeze({ Draft:'Draft', Registered:'Registered', Validated:'Validated', Active:'Active', Retired:'Retired' });
export const DecisionExecutionStatus = Object.freeze({ Prepared:'Prepared', PolicyEvaluated:'PolicyEvaluated', ApprovalEvaluated:'ApprovalEvaluated', RationaleCreated:'RationaleCreated', ArtifactCreated:'ArtifactCreated', Failed:'Failed' });
export const DecisionInputType = Object.freeze({ recommendationArtifact:'recommendation-artifact', evidenceReference:'evidence-reference', methodologyReference:'methodology-reference', scoringReference:'scoring-reference', valuationReference:'valuation-reference' });
export const DecisionArtifactStatus = Object.freeze({ Draft:'Draft', Created:'Created', Validated:'Validated', Archived:'Archived' });
export const DecisionPermissionAction = Object.freeze({ viewDecisionArtifact:'viewDecisionArtifact', registerDecisionModel:'registerDecisionModel', configureDecisionModel:'configureDecisionModel', evaluateDecisionPolicy:'evaluateDecisionPolicy', evaluateApprovalPolicy:'evaluateApprovalPolicy', createDecisionArtifact:'createDecisionArtifact', readDecisionAudit:'readDecisionAudit', replayDecisionArtifact:'replayDecisionArtifact' });
export const DecisionConfidenceSignal = Object.freeze({ requiredInputsPresent:'requiredInputsPresent', policyEvaluationCompleted:'policyEvaluationCompleted', approvalEvaluationCompleted:'approvalEvaluationCompleted', replayVerified:'replayVerified', auditComplete:'auditComplete' });
export const DecisionDisposition = Object.freeze({ proceedToReview:'proceed-to-review', returnForRevision:'return-for-revision', pause:'pause', closeNoAction:'close-no-action', insufficientInformation:'insufficient-information' });
export const ApprovalDisposition = Object.freeze({ approvalNotRequired:'approval-not-required', approvalRequired:'approval-required', approvalDeferred:'approval-deferred' });
const forbidden=Object.freeze(['portfolio','position sizing','order','trade','broker','capital allocation','capital deployment','rebalance','mandate compliance','execution instruction','buy','sell','hold','valuation calculation','score calculation','recommendation generation']);
export function assertRequired(record, fields, label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoExecutionLogic(value,label='decision'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z ]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden portfolio/execution logic: ${term}`); } return true; }
export function validateDecisionCommand(type){ if(!Object.values(DecisionFrameworkCommandType).includes(type)) throw new Error(`Unsupported decision command: ${type}`); assertNoExecutionLogic(type,'decision command'); return true; }
export function createDecisionAuditIdentity({ decisionArtifactId=null, decisionModelId, decisionModelVersion, userId='system', correlationId }={}){ assertRequired({ decisionModelId, decisionModelVersion, userId, correlationId }, ['decisionModelId','decisionModelVersion','userId','correlationId'], 'decisionAudit'); return Object.freeze({ decisionActionId:createOpaqueId('DCACT'), decisionArtifactId, decisionModelId, decisionModelVersion, userId, correlationId, timestamp:new Date().toISOString() }); }
