import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';

export const EVIDENCE_FEATURE_FLAG = 'evidence_governance_foundation';
export const EvidenceEventType = Object.freeze({ EvidenceCandidateAccepted:'EvidenceCandidateAccepted', EvidenceRecordCreated:'EvidenceRecordCreated', EvidenceSubmittedForReview:'EvidenceSubmittedForReview', EvidenceReviewStarted:'EvidenceReviewStarted', EvidenceApproved:'EvidenceApproved', EvidenceRejected:'EvidenceRejected', EvidenceCertified:'EvidenceCertified', EvidenceCorrectionRequested:'EvidenceCorrectionRequested', EvidenceVersionCreated:'EvidenceVersionCreated', EvidenceArchived:'EvidenceArchived', EvidenceSnapshotCreated:'EvidenceSnapshotCreated', EvidenceTraceLinked:'EvidenceTraceLinked', EvidenceAuditRecorded:'EvidenceAuditRecorded' });
export const EvidenceCommandType = Object.freeze({ AcceptEvidenceCandidate:'AcceptEvidenceCandidate', CreateEvidenceRecord:'CreateEvidenceRecord', SubmitEvidenceForReview:'SubmitEvidenceForReview', StartEvidenceReview:'StartEvidenceReview', ApproveEvidence:'ApproveEvidence', RejectEvidence:'RejectEvidence', CertifyEvidence:'CertifyEvidence', RequestEvidenceCorrection:'RequestEvidenceCorrection', CreateEvidenceVersion:'CreateEvidenceVersion', ArchiveEvidence:'ArchiveEvidence', CreateEvidenceSnapshot:'CreateEvidenceSnapshot', LinkEvidenceTrace:'LinkEvidenceTrace', RecordEvidenceAudit:'RecordEvidenceAudit' });
export const EvidenceRecordStatus = Object.freeze({ Draft:'Draft', InReview:'InReview', Approved:'Approved', Rejected:'Rejected', Certified:'Certified', Archived:'Archived' });
export const EvidenceCertificationStatus = Object.freeze({ Uncertified:'Uncertified', Submitted:'Submitted', UnderReview:'UnderReview', Approved:'Approved', Rejected:'Rejected', Certified:'Certified', Revoked:'Revoked' });
export const EvidenceReviewStatus = Object.freeze({ NotStarted:'NotStarted', InProgress:'InProgress', Approved:'Approved', Rejected:'Rejected', CorrectionRequested:'CorrectionRequested', Completed:'Completed' });
export const EvidenceSourceType = Object.freeze({ researchArtifact:'research-artifact', researchDocument:'research-document', evidenceCandidate:'evidence-candidate', manualReference:'manual-reference', externalReferenceMetadata:'external-reference-metadata' });
export const EvidencePermissionAction = Object.freeze({ viewEvidence:'viewEvidence', createEvidenceRecord:'createEvidenceRecord', submitEvidenceReview:'submitEvidenceReview', approveEvidenceCertification:'approveEvidenceCertification', rejectEvidenceCertification:'rejectEvidenceCertification', certifyEvidence:'certifyEvidence', createEvidenceVersion:'createEvidenceVersion', archiveEvidence:'archiveEvidence', readEvidenceAudit:'readEvidenceAudit' });
export const EvidenceCorrectionReason = Object.freeze({ sourceCorrection:'source-correction', metadataCorrection:'metadata-correction', provenanceCorrection:'provenance-correction', reviewCorrection:'review-correction' });
export const EvidenceTraceLinkType = Object.freeze({ candidateToArtifact:'candidate-to-artifact', candidateDoc:'candidate-to-doc', evidenceToCandidate:'evidence-to-candidate', evidenceToArtifact:'evidence-to-artifact', evidenceDoc:'evidence-to-doc', evidenceToWorkflow:'evidence-to-workflow', evidenceToSnapshot:'evidence-to-snapshot' });

export const forbiddenEvidenceTerms = Object.freeze(['valuation','discounted cash flow','dcf','relative valuation','factor model','stock scoring','scorecompany','rating','buy','sell','hold','recommendation','recommend','approve investment','reject investment','target price','forecast','market data','provider integration','financial statement','portfolio','position sizing','risk calculation','decision automation','investment thesis','investment opinion']);
export function assertRequired(record, fields, label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoInvestmentAnalysis(value,label='Evidence'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbiddenEvidenceTerms) if(text.includes(term)) throw new Error(`${label} contains forbidden investment analysis: ${term}`); return true; }
export function validateEvidenceCommand(type){ if(!Object.values(EvidenceCommandType).includes(type)) throw new Error(`Unsupported Evidence command: ${type}`); assertNoInvestmentAnalysis(type,'Evidence command'); return true; }
export function createEvidenceAuditIdentity({ evidenceRecordId=null, evidenceVersionId=null, workflowInstanceId, sourceArtifactId=null, researchDocumentId=null, userId='system', correlationId }={}){ assertRequired({ workflowInstanceId, userId, correlationId }, ['workflowInstanceId','userId','correlationId'], 'evidenceAudit'); return Object.freeze({ evidenceActionId:createOpaqueId('EACT'), evidenceRecordId, evidenceVersionId, workflowInstanceId, sourceArtifactId, researchDocumentId, userId, correlationId, timestamp:new Date().toISOString() }); }
export function stableHash(value){ const text=JSON.stringify(value, Object.keys(value||{}).sort()); let h=0; for(let i=0;i<text.length;i++) h=(Math.imul(31,h)+text.charCodeAt(i))|0; return `HASH_${(h>>>0).toString(16).toUpperCase().padStart(8,'0')}`; }
