import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const INTEGRATION_SCHEMA_VERSION='INTEGRATION_SCHEMA_VERSION_1.0';
export const INTEGRATION_FEATURE_FLAG='broker_exchange_integration_foundation';
export const PROVIDER_INTERFACE_VERSION='PROVIDER_INTERFACE_VERSION_1.0';
export const IntegrationFrameworkEventType=Object.freeze({ ProviderRegistered:'ProviderRegistered', ProviderCompatibilityValidated:'ProviderCompatibilityValidated', ProviderEnabled:'ProviderEnabled', ProviderDisabled:'ProviderDisabled', ExecutionArtifactAdapted:'ExecutionArtifactAdapted', BrokerRequestEnvelopeCreated:'BrokerRequestEnvelopeCreated', ExchangeRequestEnvelopeCreated:'ExchangeRequestEnvelopeCreated', DryRunSimulationStarted:'DryRunSimulationStarted', DryRunSimulationCompleted:'DryRunSimulationCompleted', IntegrationArtifactCreated:'IntegrationArtifactCreated', IntegrationAuditRecorded:'IntegrationAuditRecorded', IntegrationSnapshotCreated:'IntegrationSnapshotCreated', IntegrationReplayCompleted:'IntegrationReplayCompleted' });
export const IntegrationFrameworkCommandType=Object.freeze({ RegisterProvider:'RegisterProvider', ValidateProviderCompatibility:'ValidateProviderCompatibility', EnableProvider:'EnableProvider', DisableProvider:'DisableProvider', AdaptExecutionArtifact:'AdaptExecutionArtifact', CreateBrokerRequestEnvelope:'CreateBrokerRequestEnvelope', CreateExchangeRequestEnvelope:'CreateExchangeRequestEnvelope', StartDryRunSimulation:'StartDryRunSimulation', CompleteDryRunSimulation:'CompleteDryRunSimulation', CreateIntegrationArtifact:'CreateIntegrationArtifact', RecordIntegrationAudit:'RecordIntegrationAudit', CreateIntegrationSnapshot:'CreateIntegrationSnapshot', ReplayIntegrationArtifact:'ReplayIntegrationArtifact' });
export const ProviderType=Object.freeze({ broker:'broker', exchange:'exchange', simulation:'simulation' });
export const ProviderState=Object.freeze({ Registered:'Registered', Enabled:'Enabled', Disabled:'Disabled', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const RequestState=Object.freeze({ Created:'Created', Validated:'Validated', Simulated:'Simulated', Completed:'Completed', Failed:'Failed' });
export const TransportType=Object.freeze({ REST:'REST', FIX:'FIX', WebSocket:'WebSocket', FileDrop:'FileDrop', CustomAdapter:'CustomAdapter', SimulationOnly:'SimulationOnly' });
export const ProviderCapability=Object.freeze({ supportsAuthentication:'supportsAuthentication', supportsDryRun:'supportsDryRun', supportsOrderAcknowledgement:'supportsOrderAcknowledgement', supportsExecutionReports:'supportsExecutionReports', supportsCancelRequests:'supportsCancelRequests', supportsReplaceRequests:'supportsReplaceRequests', supportsSimulation:'supportsSimulation' });
export const IntegrationPermissionAction=Object.freeze({ viewIntegrationArtifact:'viewIntegrationArtifact', registerProvider:'registerProvider', validateProviderCompatibility:'validateProviderCompatibility', createRequestEnvelope:'createRequestEnvelope', runDryRunSimulation:'runDryRunSimulation', readIntegrationAudit:'readIntegrationAudit', replayIntegrationArtifact:'replayIntegrationArtifact' });
export const IntegrationArtifactStatus=Object.freeze({ Created:'Created', Simulated:'Simulated', Archived:'Archived' });
const forbidden=Object.freeze(['live trading','production order','real broker','live endpoint','credential','secret','account number','live fix','exchange routing','settlement','clearing','custody','market data','capital allocation','capital deployment','real-money','venue routing','order transmission']);
export function assertRequired(r,fields,label='record'){ for(const f of fields) if(r?.[f]===undefined||r?.[f]===null||r?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoLiveIntegration(v,label='integration'){ const text=JSON.stringify(v||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z -]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden live integration data: ${term}`); } return true; }
export function validateIntegrationCommand(type){ if(!Object.values(IntegrationFrameworkCommandType).includes(type)) throw new Error(`Unsupported integration command: ${type}`); assertNoLiveIntegration(type,'integration command'); return true; }
export function createIntegrationAuditIdentity({ integrationArtifactId=null, providerId=null, requestEnvelopeId=null, executionArtifactId=null, userId='system', correlationId }={}){ assertRequired({ userId, correlationId },['userId','correlationId'],'integrationAudit'); return Object.freeze({ integrationActionId:createOpaqueId('IACT'), integrationArtifactId, providerId, requestEnvelopeId, executionArtifactId, userId, correlationId, timestamp:new Date().toISOString() }); }
export function stableProviderFingerprint(manifest){ const text=JSON.stringify({ providerId:manifest.providerId, providerVersion:manifest.providerVersion, capabilities:manifest.capabilities, supportedTransports:manifest.supportedTransports, compatibility:manifest.compatibility }); let h=0; for(let i=0;i<text.length;i++) h=(Math.imul(31,h)+text.charCodeAt(i))|0; return `PFP_${(h>>>0).toString(16).toUpperCase()}`; }
