import { FlagStatus } from '../../../../packages/feature-flags/src/index.js';
import { InMemorySnapshotStore } from '../../../../packages/snapshot-engine/src/index.js';
import { VALUATION_FRAMEWORK_FEATURE_FLAG } from './contracts/index.js';
import { ValuationModelRegistry, ValuationVersionRegistry } from './models/index.js';
import { ValuationLifecycleManager } from './lifecycle/index.js';
import { ValuationConfigurationRegistry } from './configuration/index.js';
import { CompanySecurityValuationInputAdapter, CertifiedEvidenceValuationInputAdapter, MethodologyValuationInputAdapter, ValuationInputPackageBuilder, ValuationInputSufficiencyChecker } from './inputs/index.js';
import { ValuationExecutionRuntime } from './execution/index.js';
import { ValuationAuditTrail } from './audit/index.js';
import { ValuationSnapshotAdapter } from './snapshots/index.js';
import { ValuationReplayAdapter } from './replay/index.js';
import { ValuationPermissionRegistry, ValuationPermissionGate, registerDefaultValuationPermissions } from './permissions/index.js';
import { ValuationContributionRegistry } from './contributions/index.js';
import { ValuationProjectionRegistry } from './projections/index.js';
import { ValuationDiagnostics } from './diagnostics/index.js';
import { ValuationIntegrationHarness } from './testing/index.js';

export function createValuationFrameworkFoundation({ app }={}){
  const c=app.container;
  const flags=c.resolve('featureFlagRegistry');
  if(!flags.get(VALUATION_FRAMEWORK_FEATURE_FLAG)) flags.register({ flag_id:VALUATION_FRAMEWORK_FEATURE_FLAG, default_enabled:true, owner:'valuation-framework', status:FlagStatus.active });
  const diagnostics=new ValuationDiagnostics({ diagnostics:c.resolve('diagnostics') });
  const modelRegistry=new ValuationModelRegistry();
  const versionRegistry=new ValuationVersionRegistry();
  const lifecycleManager=new ValuationLifecycleManager();
  const configurationRegistry=new ValuationConfigurationRegistry();
  const companySecurityAdapter=new CompanySecurityValuationInputAdapter();
  const evidenceAdapter=new CertifiedEvidenceValuationInputAdapter();
  const methodologyAdapter=new MethodologyValuationInputAdapter();
  const inputPackageBuilder=new ValuationInputPackageBuilder();
  const sufficiencyChecker=new ValuationInputSufficiencyChecker();
  const executionRuntime=new ValuationExecutionRuntime({ lifecycleManager, sufficiencyChecker });
  const auditTrail=new ValuationAuditTrail();
  const snapshotStore=new InMemorySnapshotStore();
  const snapshotAdapter=new ValuationSnapshotAdapter({ snapshotStore });
  const replayAdapter=new ValuationReplayAdapter();
  const permissionRegistry=registerDefaultValuationPermissions(new ValuationPermissionRegistry());
  const permissionGate=new ValuationPermissionGate({ registry:permissionRegistry });
  const contributionRegistry=new ValuationContributionRegistry({ featureFlagRegistry:flags, permissionGate });
  contributionRegistry.register({ contributionId:'register-valuation-model', permission:'registerValuationModel' });
  contributionRegistry.register({ contributionId:'run-valuation-dry-run', permission:'runValuationDryRun' });
  contributionRegistry.register({ contributionId:'run-valuation-validation', permission:'runValuationValidation' });
  const projectionRegistry=new ValuationProjectionRegistry().registerDefaults();
  const runtime=Object.freeze({ diagnostics, modelRegistry, versionRegistry, lifecycleManager, configurationRegistry, companySecurityAdapter, evidenceAdapter, methodologyAdapter, inputPackageBuilder, sufficiencyChecker, executionRuntime, auditTrail, snapshotStore, snapshotAdapter, replayAdapter, permissionRegistry, permissionGate, contributionRegistry, projectionRegistry });
  const valuationTestHarness=new ValuationIntegrationHarness({ runtime });
  const full=Object.freeze({ ...runtime, valuationTestHarness });
  for(const [key,value] of Object.entries(full)) if(!c.has(key)) c.register(key,value);
  return full;
}
