import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../src/bootstrap/createApp.js';
import { createApplicationShell } from '../src/shell/index.js';
import { createWorkflowPlatform } from '../src/workflow/index.js';
import { createProductModuleFramework } from '../src/product/index.js';
import { createResearchModuleFoundation } from '../src/product-modules/research/index.js';
import { createResearchIntelligenceFoundation } from '../src/product-modules/research-intelligence/index.js';
import { createEvidenceGovernanceFoundation } from '../src/evidence/index.js';
import { createMethodologyFrameworkFoundation } from '../src/methodology-framework/index.js';
import { createCompanySecurityDomainFoundation } from '../src/domain/company-security/index.js';
import { createValuationFrameworkFoundation } from '../src/valuation-framework/index.js';
import { createValuationPluginFoundation } from '../src/valuation-plugins/index.js';
import { createDCFPlugin } from '../src/valuation-plugins/dcf/index.js';
import { createRelativeValuationPlugin } from '../src/valuation-plugins/relative/index.js';
import { createValuationNormalization } from '../src/valuation-normalization/index.js';
import { createScoringFramework } from '../src/scoring-framework/index.js';
import { createRecommendationFramework } from '../src/recommendation-framework/index.js';
import { createDecisionFramework } from '../src/decision-framework/index.js';
import { createPortfolioFramework } from '../src/portfolio-framework/index.js';
import { createExecutionFramework } from '../src/execution-framework/index.js';
import { createIntegrationFramework } from '../src/integration-framework/index.js';
import { LIVE_ENABLEMENT_SCHEMA_VERSION, ReadinessFrameworkEventType, ReadinessFrameworkCommandType, AuthorizationLevel, validateReadinessCommand, createReadinessAuditIdentity, decisionHash, ReadinessDecisionRegistry, IntegrationArtifactReadinessAdapter, ExecutionArtifactReadinessAdapter, ReadinessInputPackage, ReadinessCheckRegistry, ReadinessValidationPipeline, ReadinessGateRegistry, ReadinessGateEvaluator, AuthorizationRecord, TransmissionApprovalRegistry, KillSwitchRegistry, KillSwitchEvaluator, ReadinessPermissionRegistry, ReadinessPermissionGate, registerDefaultReadinessPermissions, ReadinessDiagnostics, ReadinessTelemetry, ReadinessProjectionRegistry, createLiveReadiness } from '../src/live-readiness/index.js';
function runtime(){ const app=createApp({ env:{ NODE_ENV:'test' } }); const shellRuntime=createApplicationShell({ app }); const workflowRuntime=createWorkflowPlatform({ app, shellRuntime }); const productRuntime=createProductModuleFramework({ app, workflowRuntime }); const researchRuntime=createResearchModuleFoundation({ app, productRuntime, workflowRuntime }); const researchIntelligenceRuntime=createResearchIntelligenceFoundation({ app, researchRuntime }); const evidenceRuntime=createEvidenceGovernanceFoundation({ app, researchIntelligenceRuntime }); const methodologyRuntime=createMethodologyFrameworkFoundation({ app, evidenceRuntime }); const companySecurityRuntime=createCompanySecurityDomainFoundation({ app, methodologyRuntime }); const valuationRuntime=createValuationFrameworkFoundation({ app, companySecurityRuntime, methodologyRuntime, evidenceRuntime }); const valuationPluginRuntime=createValuationPluginFoundation({ app, valuationRuntime }); const dcfRuntime=createDCFPlugin({ app, valuationRuntime, valuationPluginRuntime }); const relativeValuationRuntime=createRelativeValuationPlugin({ app, valuationRuntime, valuationPluginRuntime }); const valuationNormalizationRuntime=createValuationNormalization({ app, dcfRuntime, relativeValuationRuntime }); const scoringRuntime=createScoringFramework({ app, valuationNormalizationRuntime }); const recommendationRuntime=createRecommendationFramework({ app, scoringRuntime }); const decisionRuntime=createDecisionFramework({ app, recommendationRuntime }); const portfolioRuntime=createPortfolioFramework({ app, decisionRuntime }); const executionRuntime=createExecutionFramework({ app, portfolioRuntime }); const integrationRuntime=createIntegrationFramework({ app, executionRuntime }); const liveReadinessRuntime=createLiveReadiness({ app, integrationRuntime }); return { app, shellRuntime, liveReadinessRuntime }; }
function integrationArtifact(){ return { integrationArtifactId:'IART_1', integrationSchemaVersion:'INTEGRATION_SCHEMA_VERSION_1.0', providerId:'SIM_PROVIDER', requestEnvelope:{ executionArtifactId:'EART_1', dryRun:true }, simulationResult:{ acknowledgement:{ status:'ACKNOWLEDGED_SIMULATION' } } }; }
function executionArtifact(){ return { executionArtifactId:'EART_1', executionSchemaVersion:'EXECUTION_SCHEMA_VERSION_1.0' }; }
test('Readiness contracts define schema, commands, audit, and deterministic hash', () => { assert.equal(LIVE_ENABLEMENT_SCHEMA_VERSION,'LIVE_ENABLEMENT_SCHEMA_VERSION_1.0'); assert.equal(ReadinessFrameworkEventType.ReadinessEvaluationCompleted,'ReadinessEvaluationCompleted'); assert.equal(validateReadinessCommand(ReadinessFrameworkCommandType.CompleteReadinessEvaluation), true); assert.throws(()=>validateReadinessCommand('TransmitOrder')); const audit=createReadinessAuditIdentity({ readinessId:'READY_1', integrationArtifactId:'IART_1', executionArtifactId:'EART_1', userId:'u1', correlationId:'CORR_1' }); assert.match(audit.readinessActionId,/^RDACT_/); assert.equal(decisionHash({ b:2, a:1 }), decisionHash({ a:1, b:2 })); });
test('Readiness artifact model is structured and not boolean-only', () => { const registry=new ReadinessDecisionRegistry(); const r=registry.create({ integrationArtifactId:'IART_1', executionArtifactId:'EART_1', eligible:true, reasons:['ok'], failedChecks:[], warnings:[] }); assert.match(r.readinessId,/^READY_/); assert.equal(r.schemaVersion,LIVE_ENABLEMENT_SCHEMA_VERSION); assert.throws(()=>registry.create({ eligible:true })); });
test('Artifact readiness adapters and input package work', () => { const integrationInput=new IntegrationArtifactReadinessAdapter().adapt(integrationArtifact()); const executionInput=new ExecutionArtifactReadinessAdapter().adapt(executionArtifact()); assert.equal(integrationInput.dryRun,true); assert.throws(()=>new IntegrationArtifactReadinessAdapter().rejectRawRequestEnvelope()); assert.throws(()=>new ExecutionArtifactReadinessAdapter().adapt({})); const pkg=new ReadinessInputPackage({ integrationInput, executionInput }); assert.match(pkg.readinessInputPackageId,/^RDINP_/); });
test('Readiness checks and feature gates evaluate deterministically', () => { const integrationInput=new IntegrationArtifactReadinessAdapter().adapt(integrationArtifact()); const executionInput=new ExecutionArtifactReadinessAdapter().adapt(executionArtifact()); const pkg=new ReadinessInputPackage({ integrationInput, executionInput }); const gateRegistry=new ReadinessGateRegistry().registerDefaults(); const gates=new ReadinessGateEvaluator().evaluate(gateRegistry.gates); const checks=new ReadinessValidationPipeline({ checks:new ReadinessCheckRegistry().defaults().checks }).evaluate({ inputPackage:pkg, gateResults:gates, killSwitchClear:true }); assert.equal(checks.every(c=>c.status==='Passed'), true); gateRegistry.gates[0]=Object.freeze({ gateType:'platform', enabled:false }); const failedGateResults=new ReadinessGateEvaluator().evaluate(gateRegistry.gates); const failedChecks=new ReadinessValidationPipeline().evaluate({ inputPackage:pkg, gateResults:failedGateResults, killSwitchClear:true }); assert.equal(failedChecks.some(c=>c.checkId==='all-gates-enabled'&&c.status==='Failed'), true); });
test('Authorization records and approval artifacts preserve provenance and hash', () => { const record=new AuthorizationRecord({ readinessId:'READY_1', integrationArtifactId:'IART_1', executionArtifactId:'EART_1', level:AuthorizationLevel.technical, approved:true }); assert.match(record.authorizationRecordId,/^AUTHREC_/); const approval=new TransmissionApprovalRegistry().create({ readinessId:'READY_1', authorizationLevels:[record] }); assert.match(approval.approvalArtifactId,/^APPROV_/); assert.equal(approval.decisionHash, new TransmissionApprovalRegistry().create({ readinessId:'READY_1', authorizationLevels:[record] }).decisionHash); });
test('Kill switch hierarchy blocks readiness', () => { const registry=new KillSwitchRegistry(); assert.equal(new KillSwitchEvaluator().isClear(registry), true); registry.activate({ scope:'platform', reason:'test' }); assert.equal(new KillSwitchEvaluator().isClear(registry), false); registry.release({ scope:'platform' }); assert.equal(new KillSwitchEvaluator().isClear(registry), false); });
test('Readiness audit, snapshot and replay work', () => { const { liveReadinessRuntime }=runtime(); const flow=liveReadinessRuntime.readinessTestHarness.runFlow(); assert.match(flow.audit.readinessActionId,/^RDACT_/); assert.equal(flow.snapshot.readinessManifest.schemaVersion,LIVE_ENABLEMENT_SCHEMA_VERSION); assert.equal(flow.replay.readinessId, flow.readiness.readinessId); assert.equal(JSON.stringify(flow.snapshot).toLowerCase().includes('credential'), false); });
test('Readiness permissions, diagnostics and projections are governed', () => { const registry=registerDefaultReadinessPermissions(new ReadinessPermissionRegistry()); const gate=new ReadinessPermissionGate({ registry }); assert.equal(gate.require('evaluateReadiness'), true); assert.throws(()=>gate.require('missing')); assert.throws(()=>registry.register({ action:'transmitOrder' })); const diagnostics=new ReadinessDiagnostics({ telemetry:new ReadinessTelemetry() }); diagnostics.record('readinessEvaluationsCompleted'); diagnostics.record('approvalsCreated'); assert.equal(diagnostics.health().status,'Healthy'); assert.throws(()=>diagnostics.record('ordersTransmitted')); const projections=new ReadinessProjectionRegistry().registerDefaults(); assert.equal(projections.update('readiness.evaluation', { type:ReadinessFrameworkEventType.ReadinessEvaluationCompleted, payload:{ readinessId:'READY_1' } }).lastEventType, ReadinessFrameworkEventType.ReadinessEvaluationCompleted); });
test('Sprint 20 integrated flow evaluates readiness without live trading', () => { const { shellRuntime, liveReadinessRuntime }=runtime(); assert.equal(shellRuntime.shell.start('/').status,'mounted'); const flow=liveReadinessRuntime.readinessTestHarness.runFlow(); assert.equal(flow.readiness.eligible,true); const blocked=liveReadinessRuntime.readinessTestHarness.runFlow({ killSwitch:true }); assert.equal(blocked.readiness.eligible,false); liveReadinessRuntime.projectionRegistry.update('readiness.approval', { type:ReadinessFrameworkEventType.ApprovalArtifactCreated, payload:{ approvalArtifactId:flow.approval.approvalArtifactId } }); assert.equal(liveReadinessRuntime.readinessTestHarness.assertNoForbiddenReadinessLogic(flow), true); const serialized=JSON.stringify(flow).toLowerCase(); for(const forbidden of ['real broker','credential','order transmission','real-money','settlement','capital deployment','production go-live']) assert.equal(serialized.includes(forbidden), false); });
