import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../src/bootstrap/createApp.js';
import { createApplicationShell } from '../src/shell/index.js';
import { createWorkflowPlatform } from '../src/workflow/index.js';
import { createProductModuleFramework } from '../src/product/index.js';
import { createResearchModuleFoundation } from '../src/product-modules/research/index.js';
import { createResearchIntelligenceFoundation } from '../src/product-modules/research-intelligence/index.js';
import { createEvidenceGovernanceFoundation } from '../src/evidence/index.js';
import { createMethodologyFrameworkFoundation } from '../src/methodology-framework/index.js';
import { createCompanySecurityDomainFoundation } from '../src/domain/company-security/index.js';
import { createValuationFrameworkFoundation } from '../src/valuation-framework/index.js';
import { createValuationPluginFoundation } from '../src/valuation-plugins/index.js';
import { createDCFPlugin } from '../src/valuation-plugins/dcf/index.js';
import { createRelativeValuationPlugin } from '../src/valuation-plugins/relative/index.js';
import { createValuationNormalization } from '../src/valuation-normalization/index.js';
import { createScoringFramework } from '../src/scoring-framework/index.js';
import { createRecommendationFramework } from '../src/recommendation-framework/index.js';
import { DECISION_SCHEMA_VERSION, DecisionFrameworkEventType, DecisionFrameworkCommandType, DecisionDisposition, ApprovalDisposition, validateDecisionCommand, createDecisionAuditIdentity, createDecisionArtifact, DecisionModelRegistry, createPlaceholderDecisionManifest, DecisionLifecycleManager, DecisionConfigurationRegistry, RecommendationArtifactDecisionAdapter, DecisionInputPackage, DecisionPolicyRegistry, DecisionPolicyEvaluator, ApprovalPolicyRegistry, ApprovalPolicyEvaluator, DecisionRationaleBuilder, DecisionArtifactRegistry, DecisionAuditTrail, DecisionSnapshotAdapter, DecisionReplayAdapter, DecisionPermissionRegistry, DecisionPermissionGate, registerDefaultDecisionPermissions, DecisionDiagnostics, DecisionTelemetry, DecisionProjectionRegistry, createDecisionFramework } from '../src/decision-framework/index.js';
function runtime(){ const app=createApp({ env:{ NODE_ENV:'test' } }); const shellRuntime=createApplicationShell({ app }); const workflowRuntime=createWorkflowPlatform({ app, shellRuntime }); const productRuntime=createProductModuleFramework({ app, workflowRuntime }); const researchRuntime=createResearchModuleFoundation({ app, productRuntime, workflowRuntime }); const researchIntelligenceRuntime=createResearchIntelligenceFoundation({ app, researchRuntime }); const evidenceRuntime=createEvidenceGovernanceFoundation({ app, researchIntelligenceRuntime }); const methodologyRuntime=createMethodologyFrameworkFoundation({ app, evidenceRuntime }); const companySecurityRuntime=createCompanySecurityDomainFoundation({ app, methodologyRuntime }); const valuationRuntime=createValuationFrameworkFoundation({ app, companySecurityRuntime, methodologyRuntime, evidenceRuntime }); const valuationPluginRuntime=createValuationPluginFoundation({ app, valuationRuntime }); const dcfRuntime=createDCFPlugin({ app, valuationRuntime, valuationPluginRuntime }); const relativeValuationRuntime=createRelativeValuationPlugin({ app, valuationRuntime, valuationPluginRuntime }); const valuationNormalizationRuntime=createValuationNormalization({ app, dcfRuntime, relativeValuationRuntime }); const scoringRuntime=createScoringFramework({ app, valuationNormalizationRuntime }); const recommendationRuntime=createRecommendationFramework({ app, scoringRuntime }); const decisionRuntime=createDecisionFramework({ app, recommendationRuntime }); return { app, shellRuntime, recommendationRuntime, decisionRuntime }; }
function recommendationArtifact(){ return { recommendationArtifactId:'RECART_1', recommendationSchemaVersion:'RECOMMENDATION_SCHEMA_VERSION_1.0', recommendationDirection:'constructive', rationale:{ rationaleId:'RATL_1' } }; }
test('Decision contracts define schema, commands, dispositions and audit', () => { assert.equal(DECISION_SCHEMA_VERSION,'DECISION_SCHEMA_VERSION_1.0'); assert.equal(DecisionFrameworkEventType.DecisionArtifactCreated,'DecisionArtifactCreated'); assert.equal(validateDecisionCommand(DecisionFrameworkCommandType.CreateDecisionArtifact), true); assert.throws(()=>validateDecisionCommand('PlaceOrder')); const audit=createDecisionAuditIdentity({ decisionArtifactId:'DART_1', decisionModelId:'DM_1', decisionModelVersion:'1.0.0', userId:'u1', correlationId:'CORR_1' }); assert.match(audit.decisionActionId,/^DCACT_/); });
test('Decision artifact schema validates dispositions and rejects execution fields', () => { const rationale={ rationaleId:'DRAT_1', recommendationArtifact:{}, policiesEvaluated:[], approvalEvaluation:{}, rationaleItems:[] }; const artifact=createDecisionArtifact({ decisionModelId:'DM_1', decisionModelVersion:'1.0.0', inputPackageId:'DINP_1', decisionDisposition:DecisionDisposition.proceedToReview, approvalDisposition:ApprovalDisposition.approvalRequired, rationale, confidence:{ auditComplete:true }, provenance:{} }); assert.match(artifact.decisionArtifactId,/^DART_/); assert.equal(artifact.decisionSchemaVersion,DECISION_SCHEMA_VERSION); assert.throws(()=>createDecisionArtifact({ decisionModelId:'DM_1', decisionModelVersion:'1.0.0', inputPackageId:'DINP_1', decisionDisposition:'execute-trade', approvalDisposition:ApprovalDisposition.approvalRequired, rationale, confidence:{}, provenance:{} })); assert.throws(()=>createDecisionArtifact({ decisionModelId:'DM_1', decisionModelVersion:'1.0.0', inputPackageId:'DINP_1', decisionDisposition:DecisionDisposition.pause, approvalDisposition:ApprovalDisposition.approvalNotRequired, rationale, confidence:{}, provenance:{}, order:'BUY' })); });
test('Decision model registry, lifecycle and configuration work', () => { const registry=new DecisionModelRegistry(); const manifest=createPlaceholderDecisionManifest(); registry.register(manifest); assert.throws(()=>registry.register(manifest)); registry.update(manifest.decisionModelId, manifest.decisionModelVersion, { name:'Updated Decision Placeholder' }); registry.activate(manifest.decisionModelId, manifest.decisionModelVersion); assert.throws(()=>registry.update(manifest.decisionModelId, manifest.decisionModelVersion, { name:'No' })); const lifecycle=new DecisionLifecycleManager(); lifecycle.initialize('DM_1'); lifecycle.transition('DM_1','Registered'); lifecycle.transition('DM_1','Validated'); lifecycle.transition('DM_1','Active'); assert.equal(lifecycle.status('DM_1').state,'Active'); const config=new DecisionConfigurationRegistry().register({ decisionModelId:'DM_1', decisionModelVersion:'1.0.0', policySettings:{ approvalRequired:true } }); assert.match(config.decisionConfigurationId,/^DCFG_/); assert.throws(()=>new DecisionConfigurationRegistry().register({ decisionModelId:'DM_2', decisionModelVersion:'1.0.0', policySettings:{ orderGeneration:true } })); });
test('Decision input adapter consumes recommendation artifacts and rejects raw artifacts', () => { const adapter=new RecommendationArtifactDecisionAdapter(); const input=adapter.adapt(recommendationArtifact()); assert.equal(input.inputType,'recommendation-artifact'); assert.equal(input.recommendationArtifactId,'RECART_1'); assert.throws(()=>adapter.adapt({ scoreArtifactId:'SART_1' })); assert.throws(()=>adapter.rejectRawScoreArtifact()); assert.throws(()=>adapter.rejectRawValuationArtifact()); const pkg=new DecisionInputPackage({ decisionModelId:'DM_1', decisionModelVersion:'1.0.0', recommendationInput:input }); assert.match(pkg.inputPackageId,/^DINP_/); });
test('Decision and approval policies evaluate dispositions', () => { const decisionPolicy=new DecisionPolicyRegistry().register({ decisionPolicyVersion:'1.0.0', policyName:'Decision Policy', inputType:'recommendation-artifact', allowedDispositions:[DecisionDisposition.proceedToReview, DecisionDisposition.pause, DecisionDisposition.insufficientInformation], provenance:{ owner:'test' }, evaluationRules:{} }); const approvalPolicy=new ApprovalPolicyRegistry().register({ approvalPolicyVersion:'1.0.0', policyName:'Approval Policy', inputType:'decision-disposition', allowedApprovalDispositions:[ApprovalDisposition.approvalRequired, ApprovalDisposition.approvalNotRequired], provenance:{ owner:'test' }, evaluationRules:{} }); const input=new RecommendationArtifactDecisionAdapter().adapt(recommendationArtifact()); const pkg=new DecisionInputPackage({ decisionModelId:'DM_1', decisionModelVersion:'1.0.0', recommendationInput:input }); const decision=new DecisionPolicyEvaluator().evaluate({ policy:decisionPolicy, inputPackage:pkg }); assert.equal(decision.decisionDisposition, DecisionDisposition.proceedToReview); const approval=new ApprovalPolicyEvaluator().evaluate({ policy:approvalPolicy, decisionEvaluation:decision }); assert.equal(approval.evaluationOutcome, ApprovalDisposition.approvalRequired); assert.match(approval.approvalEvaluationId,/^AEVAL_/); });
test('Decision rationale, artifact, audit, snapshot and replay work', () => { const { decisionRuntime }=runtime(); const flow=decisionRuntime.decisionTestHarness.runFlow(); assert.match(flow.rationale.rationaleId,/^DRAT_/); assert.match(flow.artifact.decisionArtifactId,/^DART_/); assert.match(flow.audit.decisionActionId,/^DCACT_/); assert.equal(flow.snapshot.decisionManifest.decisionSchemaVersion,DECISION_SCHEMA_VERSION); assert.equal(flow.replay.decisionDisposition, flow.artifact.decisionDisposition); assert.equal(JSON.stringify(flow.snapshot).toLowerCase().includes('trade'), false); });
test('Decision permissions, diagnostics and projections are governed', () => { const registry=registerDefaultDecisionPermissions(new DecisionPermissionRegistry()); const gate=new DecisionPermissionGate({ registry }); assert.equal(gate.require('createDecisionArtifact'), true); assert.throws(()=>gate.require('missing')); assert.throws(()=>registry.register({ action:'executeTrade' })); const diagnostics=new DecisionDiagnostics({ telemetry:new DecisionTelemetry() }); diagnostics.record('decisionArtifactsCreated'); diagnostics.record('decisionPoliciesEvaluated'); assert.equal(diagnostics.health().status,'Healthy'); assert.throws(()=>diagnostics.record('ordersGenerated')); const projections=new DecisionProjectionRegistry().registerDefaults(); assert.equal(projections.update('decision.artifact', { type:DecisionFrameworkEventType.DecisionArtifactCreated, payload:{ decisionArtifactId:'DART_1' } }).lastEventType, DecisionFrameworkEventType.DecisionArtifactCreated); });
test('Sprint 16 integrated flow creates decision artifact without execution behavior', () => { const { shellRuntime, decisionRuntime }=runtime(); assert.equal(shellRuntime.shell.start('/').status,'mounted'); const flow=decisionRuntime.decisionTestHarness.runFlow(); decisionRuntime.projectionRegistry.update('decision.policy', { type:DecisionFrameworkEventType.DecisionPolicyEvaluated, payload:{ decisionPolicyId:flow.decisionPolicy.decisionPolicyId } }); decisionRuntime.projectionRegistry.update('decision.policy', { type:DecisionFrameworkEventType.ApprovalPolicyEvaluated, payload:{ approvalPolicyId:flow.approvalPolicy.approvalPolicyId } }); decisionRuntime.projectionRegistry.update('decision.rationale', { type:DecisionFrameworkEventType.DecisionRationaleCreated, payload:{ rationaleId:flow.rationale.rationaleId } }); decisionRuntime.projectionRegistry.update('decision.artifact', { type:DecisionFrameworkEventType.DecisionArtifactCreated, payload:{ decisionArtifactId:flow.artifact.decisionArtifactId } }); assert.equal(flow.artifact.decisionDisposition, DecisionDisposition.proceedToReview); assert.equal(decisionRuntime.decisionTestHarness.assertNoForbiddenDecisionLogic(flow), true); const serialized=JSON.stringify(flow).toLowerCase(); for(const forbidden of ['order generation','trade execution','position sizing','capital allocation','broker integration','rebalance']) assert.equal(serialized.includes(forbidden), false); });
