import { assertNoInvestmentAnalysis } from '../contracts/index.js';
class BaseProjection { constructor({ projectionId, supportedEvents }){ this.definition=Object.freeze({ projectionId, snapshotCompatible:true, projectionVersion:'1.0.0', supportedEvents:Object.freeze(supportedEvents) }); this.state=Object.freeze({}); } apply(event){ if(!this.definition.supportedEvents.includes(event.type)) throw new Error(`Unsupported methodology event: ${event.type}`); assertNoInvestmentAnalysis(event,'Methodology projection'); this.state=deepFreeze({ ...this.state, lastEventType:event.type, payload:event.payload||{}, updatedAt:new Date().toISOString() }); return this.state; } snapshot(){ return deepFreeze({ definition:this.definition, state:this.state }); }}
export class MethodologyRegistryProjection extends BaseProjection { constructor(){ super({ projectionId:'methodology.registry', supportedEvents:['MethodologyDefinitionRegistered','MethodologyVersionCreated'] }); }}
export class MethodologyLifecycleProjection extends BaseProjection { constructor(){ super({ projectionId:'methodology.lifecycle', supportedEvents:['MethodologyActivated','MethodologyDeprecated','MethodologyRetired'] }); }}
export class MethodologyExecutionProjection extends BaseProjection { constructor(){ super({ projectionId:'methodology.execution', supportedEvents:['MethodologyDryRunCompleted','MethodologyValidationCompleted'] }); }}
export class MethodologyEvidenceRequirementProjection extends BaseProjection { constructor(){ super({ projectionId:'methodology.evidenceRequirements', supportedEvents:['MethodologyEvidenceRequirementDeclared','MethodologyEvidenceLinked'] }); }}
export class MethodologyAuditProjection extends BaseProjection { constructor(){ super({ projectionId:'methodology.audit', supportedEvents:['MethodologyExecutionAudited'] }); }}
export class MethodologyProjectionRegistry { constructor(){ this.projections=new Map(); } register(p){ if(this.projections.has(p.definition.projectionId)) throw new Error(`Projection exists: ${p.definition.projectionId}`); this.projections.set(p.definition.projectionId,p); return p; } registerDefaults(){ [new MethodologyRegistryProjection(),new MethodologyLifecycleProjection(),new MethodologyExecutionProjection(),new MethodologyEvidenceRequirementProjection(),new MethodologyAuditProjection()].forEach(p=>{ if(!this.projections.has(p.definition.projectionId)) this.register(p); }); return this; } get(id){ const p=this.projections.get(id); if(!p) throw new Error(`Projection not found: ${id}`); return p; } update(id,event){ return this.get(id).apply(event); }}
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
