import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const EXECUTION_SCHEMA_VERSION='EXECUTION_SCHEMA_VERSION_1.0';
export const EXECUTION_FRAMEWORK_FEATURE_FLAG='execution_framework_foundation';
export const ExecutionFrameworkEventType=Object.freeze({ ExecutionIntentCreated:'ExecutionIntentCreated', ExecutionPlanCreated:'ExecutionPlanCreated', ExecutionPolicyRegistered:'ExecutionPolicyRegistered', ExecutionPolicyEvaluated:'ExecutionPolicyEvaluated', ExecutionStrategyRegistered:'ExecutionStrategyRegistered', ExecutionInstructionCreated:'ExecutionInstructionCreated', ExecutionConstraintEvaluated:'ExecutionConstraintEvaluated', ExecutionArtifactCreated:'ExecutionArtifactCreated', ExecutionAuditRecorded:'ExecutionAuditRecorded', ExecutionSnapshotCreated:'ExecutionSnapshotCreated', ExecutionReplayCompleted:'ExecutionReplayCompleted' });
export const ExecutionFrameworkCommandType=Object.freeze({ CreateExecutionIntent:'CreateExecutionIntent', CreateExecutionPlan:'CreateExecutionPlan', RegisterExecutionPolicy:'RegisterExecutionPolicy', EvaluateExecutionPolicy:'EvaluateExecutionPolicy', RegisterExecutionStrategy:'RegisterExecutionStrategy', CreateExecutionInstruction:'CreateExecutionInstruction', EvaluateExecutionConstraint:'EvaluateExecutionConstraint', CreateExecutionArtifact:'CreateExecutionArtifact', RecordExecutionAudit:'RecordExecutionAudit', CreateExecutionSnapshot:'CreateExecutionSnapshot', ReplayExecutionArtifact:'ReplayExecutionArtifact' });
export const ExecutionIntentStatus=Object.freeze({ Draft:'Draft', Active:'Active', Cancelled:'Cancelled', Archived:'Archived' });
export const ExecutionPlanStatus=Object.freeze({ Planned:'Planned', PendingReview:'PendingReview', Approved:'Approved', Cancelled:'Cancelled', Archived:'Archived' });
export const ExecutionLifecycleState=Object.freeze({ Draft:'Draft', Registered:'Registered', Active:'Active', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const ExecutionArtifactStatus=Object.freeze({ Draft:'Draft', Created:'Created', Archived:'Archived' });
export const ExecutionStrategyType=Object.freeze({ manualReview:'manual-review', stagedPlaceholder:'staged-placeholder', singleStepPlaceholder:'single-step-placeholder' });
export const ExecutionPermissionAction=Object.freeze({ viewExecutionArtifact:'viewExecutionArtifact', createExecutionIntent:'createExecutionIntent', createExecutionPlan:'createExecutionPlan', registerExecutionPolicy:'registerExecutionPolicy', evaluateExecutionPolicy:'evaluateExecutionPolicy', registerExecutionStrategy:'registerExecutionStrategy', createExecutionInstruction:'createExecutionInstruction', readExecutionAudit:'readExecutionAudit', replayExecutionArtifact:'replayExecutionArtifact' });
export const ExecutionConstraintSeverity=Object.freeze({ info:'info', warning:'warning', block:'block' });
const forbidden=Object.freeze(['broker','exchange','fix','websocket','rest','order transmission','real-money','live market','market data','settlement','clearing','custdn','venue','oms','ems','transaction cost','smart order','vwap','twap','pov','liquidity-seeking','implementation-shortfall','pathinstruction','fixmsg','settlementinstruction','tradeinstruction']);
export function assertRequired(r,fields,label='record'){ for(const f of fields) if(r?.[f]===undefined||r?.[f]===null||r?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoExternalExecution(value,label='execution'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z -]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden external execution logic: ${term}`); } return true; }
export function validateExecutionCommand(type){ if(!Object.values(ExecutionFrameworkCommandType).includes(type)) throw new Error(`Unsupported execution command: ${type}`); assertNoExternalExecution(type,'execution command'); return true; }
export function createExecutionAuditIdentity({ executionArtifactId=null, executionPlanId=null, portfolioChangeProposalId=null, userId='system', correlationId }={}){ assertRequired({ userId, correlationId },['userId','correlationId'],'executionAudit'); return Object.freeze({ executionActionId:createOpaqueId('EXACT'), executionArtifactId, executionPlanId, portfolioChangeProposalId, userId, correlationId, timestamp:new Date().toISOString() }); }
