import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const SCORING_SCHEMA_VERSION = 'SCORING_SCHEMA_VERSION_1.0';
export const SCORING_FRAMEWORK_FEATURE_FLAG = 'scoring_framework_foundation';
export const ScoringFrameworkEventType = Object.freeze({ ScoringModelRegistered:'ScoringModelRegistered', ScoringConfigurationRegistered:'ScoringConfigurationRegistered', ScoringInputPackageCreated:'ScoringInputPackageCreated', ScoringRuleRegistered:'ScoringRuleRegistered', ScoreComponentCreated:'ScoreComponentCreated', ScoreAggregationCompleted:'ScoreAggregationCompleted', ScoreArtifactCreated:'ScoreArtifactCreated', ScoreAuditRecorded:'ScoreAuditRecorded', ScoreSnapshotCreated:'ScoreSnapshotCreated', ScoreReplayCompleted:'ScoreReplayCompleted' });
export const ScoringFrameworkCommandType = Object.freeze({ RegisterScoringModel:'RegisterScoringModel', RegisterScoringConfiguration:'RegisterScoringConfiguration', CreateScoringInputPackage:'CreateScoringInputPackage', RegisterScoringRule:'RegisterScoringRule', CreateScoreComponent:'CreateScoreComponent', AggregateScoreComponents:'AggregateScoreComponents', CreateScoreArtifact:'CreateScoreArtifact', RecordScoreAudit:'RecordScoreAudit', CreateScoreSnapshot:'CreateScoreSnapshot', ReplayScoreArtifact:'ReplayScoreArtifact' });
export const ScoringModelStatus = Object.freeze({ draft:'draft', active:'active', deprecated:'deprecated', retired:'retired' });
export const ScoringLifecycleState = Object.freeze({ Draft:'Draft', Registered:'Registered', Validated:'Validated', Active:'Active', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const ScoringExecutionStatus = Object.freeze({ Prepared:'Prepared', ComponentsCreated:'ComponentsCreated', Aggregated:'Aggregated', Failed:'Failed' });
export const ScoringInputType = Object.freeze({ normalizedValuationResult:'normalized-valuation-result', evidenceReference:'evidence-reference', methodologyReference:'methodology-reference', researchReference:'research-reference' });
export const ScoringComponentType = Object.freeze({ valuation:'valuation', evidence:'evidence', methodology:'methodology', research:'research', composite:'composite' });
export const ScoringAggregationStatus = Object.freeze({ Completed:'Completed', Failed:'Failed' });
export const ScoringPermissionAction = Object.freeze({ viewScoreArtifact:'viewScoreArtifact', registerScoringModel:'registerScoringModel', configureScoringModel:'configureScoringModel', createScoreComponent:'createScoreComponent', aggregateScoreComponents:'aggregateScoreComponents', readScoreAudit:'readScoreAudit', replayScoreArtifact:'replayScoreArtifact' });
export const ScoringConfidenceSignal = Object.freeze({ allRequiredInputsPresent:'allRequiredInputsPresent', allConfiguredRulesExecuted:'allConfiguredRulesExecuted', aggregationCompleted:'aggregationCompleted', replayVerified:'replayVerified', auditComplete:'auditComplete' });
const forbidden = Object.freeze(['recommendation','rating','buy','sell','hold','target action','portfolio','position sizing','decision','analyst opinion','trade signal','valuation calculation']);
export function assertRequired(record, fields, label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoRecommendationLogic(value,label='scoring'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z ]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden recommendation/decision logic: ${term}`); } return true; }
export function validateScoringCommand(type){ if(!Object.values(ScoringFrameworkCommandType).includes(type)) throw new Error(`Unsupported scoring command: ${type}`); assertNoRecommendationLogic(type,'scoring command'); return true; }
export function createScoringAuditIdentity({ scoreArtifactId=null, scoringModelId, scoringModelVersion, userId='system', correlationId }={}){ assertRequired({ scoringModelId, scoringModelVersion, userId, correlationId }, ['scoringModelId','scoringModelVersion','userId','correlationId'], 'scoringAudit'); return Object.freeze({ scoringActionId:createOpaqueId('SACT'), scoreArtifactId, scoringModelId, scoringModelVersion, userId, correlationId, timestamp:new Date().toISOString() }); }
