import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';
import { ResearchChecklistItemStatus } from '../contracts/index.js';
export class ResearchChecklistItem { constructor({ researchDocumentId, label, required=false, version='1.0.0' }){ if(!researchDocumentId||!label) throw new Error('researchDocumentId and label are required'); return Object.freeze({ checklistItemId:createOpaqueId('RCHK'), researchDocumentId, label, required, status:ResearchChecklistItemStatus.Open, ResearchChecklistVersion:version, createdAt:new Date().toISOString(), completedAt:null }); } }
export class ResearchChecklistService { constructor({ diagnostics }={}){ this.items=new Map(); this.diagnostics=diagnostics; }
  createItem(input){ const item=new ResearchChecklistItem(input); this.items.set(item.checklistItemId,item); return item; }
  completeItem(id){ const item=this.get(id); const next=Object.freeze({ ...item, status:ResearchChecklistItemStatus.Completed, completedAt:new Date().toISOString() }); this.items.set(id,next); this.diagnostics?.record?.('researchIntelligence.checklist.completed', { checklistItemId:id }); return next; }
  byDocument(id){ return Object.freeze([...this.items.values()].filter(i=>i.researchDocumentId===id)); } get(id){ const i=this.items.get(id); if(!i) throw new Error(`Checklist item not found: ${id}`); return i; }}
export class ResearchCompletenessCheck { constructor({ ResearchCompletenessRuleVersion='1.0.0' }={}){ this.ResearchCompletenessRuleVersion=ResearchCompletenessRuleVersion; }
  run({ researchDocumentId, sections=[], artifacts=[], checklistItems=[], review=null }={}){ const missing=[]; if(sections.length===0) missing.push('requiredSections'); if(artifacts.length===0) missing.push('artifactCoverage'); if(checklistItems.some(i=>i.required && i.status!==ResearchChecklistItemStatus.Completed)) missing.push('requiredChecklistItems'); if(!review || review.status!=='Completed') missing.push('reviewStatus'); return Object.freeze({ researchDocumentId, ResearchCompletenessRuleVersion:this.ResearchCompletenessRuleVersion, dimensions:Object.freeze({ documentStructure:sections.length>0, requiredSections:sections.length, artifactCoverage:artifacts.length, openQuestions:checklistItems.filter(i=>i.status!==ResearchChecklistItemStatus.Completed).length, reviewStatus:review?.status||'NotStarted', sourceReferences:artifacts.length }), missing:Object.freeze(missing), processComplete:missing.length===0 }); }}
export const ResearchChecklist = Object.freeze({});
export const ResearchCompletenessResult = Object.freeze({});
