import { assertNoResearchIntelligence, ResearchDocumentType, ResearchArtifactType } from '../contracts/index.js';
import { createResearchModuleManifest } from '../manifest/index.js';
export class ResearchGuardrailAssertions { assertNoValuation(v){ return assertNoResearchIntelligence(v,'valuation guardrail'); } assertNoScoring(v){ return assertNoResearchIntelligence(v,'scoring guardrail'); } assertNoRatings(v){ return assertNoResearchIntelligence(v,'ratings guardrail'); } assertNoRecommendations(v){ return assertNoResearchIntelligence(v,'recommendations guardrail'); } assertNoMarketData(v){ return assertNoResearchIntelligence(v,'market data guardrail'); } assertNoMethodologyCalculations(v){ return assertNoResearchIntelligence(v,'methodology guardrail'); } assertNoPortfolioLogic(v){ return assertNoResearchIntelligence(v,'portfolio guardrail'); } assertNoDecisionAutomation(v){ return assertNoResearchIntelligence(v,'decision automation guardrail'); } }
export class ResearchFixtureFactory { manifest(overrides={}){ return Object.freeze({ ...createResearchModuleManifest(), ...overrides }); } subject(){ return Object.freeze({ type:'subject', id:'SUB_1', label:'Placeholder Subject' }); } }
export class ResearchModuleTestHarness { constructor({ researchRuntime }={}){ this.researchRuntime=researchRuntime; this.fixtures=new ResearchFixtureFactory(); this.guardrails=new ResearchGuardrailAssertions(); }
  registerResearchModule(manifest=this.fixtures.manifest()){ return this.researchRuntime.researchRegistration.register(manifest); }
  createDocument(workflowInstanceId='WFI_RESEARCH'){ return this.researchRuntime.researchDocumentRegistry.create({ documentType:ResearchDocumentType.researchNote, title:'Research note', workflowInstanceId, subject:this.fixtures.subject() }); }
  registerArtifact(workflowInstanceId='WFI_RESEARCH'){ return this.researchRuntime.researchArtifactRegistry.register({ artifactType:ResearchArtifactType.sourceReference, title:'Source metadata', description:'Reference metadata only', workflowInstanceId, sourceReference:{ sourceId:'SRC_1', label:'Reference' } }); }
  assertNoForbiddenResearchLogic(value){ this.guardrails.assertNoValuation(value); this.guardrails.assertNoScoring(value); this.guardrails.assertNoRatings(value); this.guardrails.assertNoRecommendations(value); this.guardrails.assertNoMarketData(value); this.guardrails.assertNoMethodologyCalculations(value); this.guardrails.assertNoPortfolioLogic(value); this.guardrails.assertNoDecisionAutomation(value); return true; }}
export class ResearchIntegrationHarness extends ResearchModuleTestHarness { runFoundationFlow({ workflowContext }){ const manifest=this.fixtures.manifest({ workflowBindings:[{ ...this.fixtures.manifest().workflowBindings[0], workflowId:workflowContext.workflowId }] }); const registered=this.registerResearchModule(manifest); const workspace=this.researchRuntime.researchWorkspace.mount({ context:workflowContext }); const doc=this.createDocument(workflowContext.workflowInstanceId); const artifact=this.registerArtifact(workflowContext.workflowInstanceId); const linked=this.researchRuntime.researchArtifactRegistry.link(artifact.researchArtifactId, doc.researchDocumentId); return Object.freeze({ registered, workspace, doc, artifact:linked }); }}
