import { EvidenceCertificationStatus, EvidenceRecordStatus, assertRequired } from '../contracts/index.js';
export class EvidenceCertificationLifecycle { transition(from,to){ const allowed={ Uncertified:['Submitted'], Submitted:['UnderReview','Rejected'], UnderReview:['Approved','Rejected'], Approved:['Certified'], Rejected:[], Certified:['Revoked'], Revoked:[] }; if(!(allowed[from]||[]).includes(to)) throw new Error(`Invalid certification transition: ${from} -> ${to}`); return to; } }
export class EvidenceCertificationPolicy { validateForCertification({ evidence, reviewDecision, certificationAuthorityId, certificationPolicyVersion }){ assertRequired({ certificationAuthorityId, certificationPolicyVersion }, ['certificationAuthorityId','certificationPolicyVersion'], 'certification'); if(!evidence.provenance) throw new Error('Provenance is required'); if(reviewDecision!=='approve-evidence-certification') throw new Error('Approval is required before certification'); return true; } }
export class EvidenceCertificationService { constructor({ registry, policy=new EvidenceCertificationPolicy(), diagnostics }={}){ this.registry=registry; this.policy=policy; this.lifecycle=new EvidenceCertificationLifecycle(); this.statuses=new Map(); this.diagnostics=diagnostics; }
  submit(id){ const e=this.registry.get(id); this.lifecycle.transition(e.certificationStatus, EvidenceCertificationStatus.Submitted); return this.registry.update(id,{ status:EvidenceRecordStatus.InReview, certificationStatus:EvidenceCertificationStatus.Submitted }); }
  startReview(id){ const e=this.registry.get(id); this.lifecycle.transition(e.certificationStatus, EvidenceCertificationStatus.UnderReview); return this.registry.update(id,{ certificationStatus:EvidenceCertificationStatus.UnderReview }); }
  approve(id){ const e=this.registry.get(id); this.lifecycle.transition(e.certificationStatus, EvidenceCertificationStatus.Approved); return this.registry.update(id,{ status:EvidenceRecordStatus.Approved, certificationStatus:EvidenceCertificationStatus.Approved }); }
  reject(id){ return this.registry.update(id,{ status:EvidenceRecordStatus.Rejected, certificationStatus:EvidenceCertificationStatus.Rejected }); }
  certify(id,{ reviewDecision, certificationAuthorityId, certificationPolicyVersion='1.0.0' }={}){ const e=this.registry.get(id); this.policy.validateForCertification({ evidence:e, reviewDecision, certificationAuthorityId, certificationPolicyVersion }); this.lifecycle.transition(e.certificationStatus, EvidenceCertificationStatus.Certified); const certified=this.registry.markCertified(id); this.diagnostics?.record?.('evidence.certified',{ evidenceRecordId:id, certificationAuthorityId, certificationPolicyVersion }); return Object.freeze({ ...certified, certificationAuthorityId, certificationPolicyVersion }); }}
export const EvidenceCertificationResult = Object.freeze({});
