import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';
import { DCF_PLUGIN_ID, DCF_FORMULA_VERSION, assertNoInvestmentDecision } from '../contracts/index.js';
import { DCFInputValidator, DCFAssumptionSet } from '../inputs/index.js';
import { DCFFormulaEngine } from '../formula/index.js';
export class DCFExecutionContext { constructor({ valuationExecutionId, valuationInputPackageId, dcfPluginVersion='1.0.0', input }){ return Object.freeze({ dcfExecutionId:createOpaqueId('DCFEX'), valuationExecutionId, valuationInputPackageId, dcfPluginVersion, dcfFormulaVersion:DCF_FORMULA_VERSION, input, createdAt:new Date().toISOString() }); } }
export class DCFDryRunExecutor { run(context){ const validation=new DCFInputValidator().validate(context.input); return Object.freeze({ dcfExecutionId:context.dcfExecutionId, validationResult:validation, auditResult:{ dryRun:true }, createdAt:new Date().toISOString() }); }}
export class DCFValidationExecutor { run(context){ const validation=new DCFInputValidator().validate(context.input); return Object.freeze({ dcfExecutionId:context.dcfExecutionId, validationResult:validation, auditResult:{ validation:true }, createdAt:new Date().toISOString() }); }}
export class DCFCalculationExecutor { run(context){ const assumptions=new DCFAssumptionSet(context.input); const formula=new DCFFormulaEngine().execute(assumptions); const result=Object.freeze({ dcfExecutionId:context.dcfExecutionId, valuationExecutionId:context.valuationExecutionId, valuationInputPackageId:context.valuationInputPackageId, dcfPluginVersion:context.dcfPluginVersion, dcfFormulaVersion:DCF_FORMULA_VERSION, enterpriseValue:formula.enterpriseValue, equityValue:formula.equityValue, perShareValue:formula.perShareValue, currency:formula.currency, assumptions, formulaTrace:formula.formulaTrace, validationResult:{ status:'Passed', errors:[] }, auditResult:{ calculated:true }, createdAt:new Date().toISOString() }); assertNoInvestmentDecision(result,'DCF execution result'); return result; }}
export class DCFExecutionAdapter { constructor(){ this.dryRunExecutor=new DCFDryRunExecutor(); this.validationExecutor=new DCFValidationExecutor(); this.calculationExecutor=new DCFCalculationExecutor(); } createContext(input){ return new DCFExecutionContext(input); } dryRun(context){ return this.dryRunExecutor.run(context); } validate(context){ return this.validationExecutor.run(context); } calculate(context){ return this.calculationExecutor.run(context); }}
export const DCFExecutionResult=Object.freeze({});
