import { assertNoInvestmentAnalysis } from '../contracts/index.js';
class BaseProjection { constructor({ projectionId, supportedEvents }){ this.definition=Object.freeze({ projectionId, snapshotCompatible:true, projectionVersion:'1.0.0', supportedEvents:Object.freeze(supportedEvents) }); this.state=Object.freeze({}); } apply(event){ if(!this.definition.supportedEvents.includes(event.type)) throw new Error(`Unsupported domain event: ${event.type}`); assertNoInvestmentAnalysis(event,'Domain projection'); this.state=deepFreeze({ ...this.state, lastEventType:event.type, payload:event.payload||{}, updatedAt:new Date().toISOString() }); return this.state; } snapshot(){ return deepFreeze({ definition:this.definition, state:this.state }); }}
export class CompanyProjection extends BaseProjection{ constructor(){ super({ projectionId:'domain.company', supportedEvents:['CompanyRegistered','CompanyUpdated','CompanyStatusChanged'] }); }}
export class SecurityProjection extends BaseProjection{ constructor(){ super({ projectionId:'domain.security', supportedEvents:['SecurityRegistered','SecurityUpdated','SecurityStatusChanged'] }); }}
export class ListingProjection extends BaseProjection{ constructor(){ super({ projectionId:'domain.listing', supportedEvents:['ExchangeRegistered','ListingRegistered','ListingStatusChanged'] }); }}
export class IdentifierProjection extends BaseProjection{ constructor(){ super({ projectionId:'domain.identifier', supportedEvents:['IdentifierRegistered','IdentifierMapped'] }); }}
export class ClassificationProjection extends BaseProjection{ constructor(){ super({ projectionId:'domain.classification', supportedEvents:['ClassificationAssigned'] }); }}
export class CorporateActionProjection extends BaseProjection{ constructor(){ super({ projectionId:'domain.corporateAction', supportedEvents:['CorporateActionMetadataRecorded'] }); }}
export class CompanySecurityProjectionRegistry { constructor(){ this.projections=new Map(); } register(p){ this.projections.set(p.definition.projectionId,p); return p; } registerDefaults(){ [new CompanyProjection(),new SecurityProjection(),new ListingProjection(),new IdentifierProjection(),new ClassificationProjection(),new CorporateActionProjection()].forEach(p=>this.register(p)); return this; } get(id){ const p=this.projections.get(id); if(!p) throw new Error(`Projection not found: ${id}`); return p; } update(id,event){ return this.get(id).apply(event); }}
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
