import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const VALUATION_PLUGIN_FEATURE_FLAG='valuation_model_plugin_foundation';
export const VALUATION_PLUGIN_API_VERSION='VALUATION_PLUGIN_API_1.0';
export const ValuationPluginEventType=Object.freeze({ ValuationPluginDiscovered:'ValuationPluginDiscovered', ValuationPluginValidated:'ValuationPluginValidated', ValuationPluginRegistered:'ValuationPluginRegistered', ValuationPluginLoaded:'ValuationPluginLoaded', ValuationPluginEnabled:'ValuationPluginEnabled', ValuationPluginDisabled:'ValuationPluginDisabled', ValuationPluginExecutionPrepared:'ValuationPluginExecutionPrepared', ValuationPluginDryRunCompleted:'ValuationPluginDryRunCompleted', ValuationPluginValidationCompleted:'ValuationPluginValidationCompleted', ValuationPluginExecutionAudited:'ValuationPluginExecutionAudited', ValuationPluginSnapshotCreated:'ValuationPluginSnapshotCreated', ValuationPluginReplayCompleted:'ValuationPluginReplayCompleted' });
export const ValuationPluginCommandType=Object.freeze({ DiscoverValuationPlugin:'DiscoverValuationPlugin', ValidateValuationPlugin:'ValidateValuationPlugin', RegisterValuationPlugin:'RegisterValuationPlugin', LoadValuationPlugin:'LoadValuationPlugin', EnableValuationPlugin:'EnableValuationPlugin', DisableValuationPlugin:'DisableValuationPlugin', PrepareValuationPluginExecution:'PrepareValuationPluginExecution', RunValuationPluginDryRun:'RunValuationPluginDryRun', RunValuationPluginValidation:'RunValuationPluginValidation', RecordValuationPluginAudit:'RecordValuationPluginAudit', CreateValuationPluginSnapshot:'CreateValuationPluginSnapshot', ReplayValuationPluginExecution:'ReplayValuationPluginExecution' });
export const ValuationPluginStatus=Object.freeze({ draft:'draft', active:'active', deprecated:'deprecated', retired:'retired' });
export const ValuationPluginLifecycleState=Object.freeze({ Discovered:'Discovered', Validated:'Validated', Registered:'Registered', Loaded:'Loaded', Enabled:'Enabled', Disabled:'Disabled', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const ValuationPluginExecutionStatus=Object.freeze({ Prepared:'Prepared', DryRunCompleted:'DryRunCompleted', ValidationCompleted:'ValidationCompleted', Failed:'Failed' });
export const ValuationPluginCapability=Object.freeze({ inputAdapter:'inputAdapter', validation:'validation', dryRun:'dryRun', replay:'replay', snapshot:'snapshot', diagnostics:'diagnostics' });
export const ValuationPluginInputType=Object.freeze({ valuationInputPackage:'valuation-input-package' });
export const ValuationPluginOutputType=Object.freeze({ structural:'structural' });
export const ValuationPluginPermissionAction=Object.freeze({ viewValuationPlugin:'viewValuationPlugin', registerValuationPlugin:'registerValuationPlugin', loadValuationPlugin:'loadValuationPlugin', enableValuationPlugin:'enableValuationPlugin', disableValuationPlugin:'disableValuationPlugin', runValuationPluginDryRun:'runValuationPluginDryRun', runValuationPluginValidation:'runValuationPluginValidation', readValuationPluginAudit:'readValuationPluginAudit', replayValuationPlugin:'replayValuationPlugin' });
export const ValuationPluginCompatibilityStatus=Object.freeze({ Compatible:'Compatible', Incompatible:'Incompatible' });
const forbidden=Object.freeze(['multiple','residual income','dividend discount','nav','sum-of-the-parts','intrinsic value','fair value','target price','margin of safety','valuation range','upside','downside','score','rating','buy','sell','hold','recommendation','portfolio','decision automation']);
export function assertRequired(r,fields,label='record'){ for(const f of fields) if(r?.[f]===undefined||r?.[f]===null||r?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoPluginMath(v,label='valuation plugin'){ const text=JSON.stringify(v||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z -]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden valuation logic: ${term}`); } return true; }
export function validateValuationPluginCommand(type){ if(!Object.values(ValuationPluginCommandType).includes(type)) throw new Error(`Unsupported valuation plugin command: ${type}`); assertNoPluginMath(type,'valuation plugin command'); return true; }
export function createValuationPluginAuditIdentity({ valuationPluginId, valuationPluginVersion, valuationModelId=null, valuationModelVersion=null, valuationExecutionId=null, valuationInputPackageId=null, userId='system', correlationId }={}){ assertRequired({ valuationPluginId, valuationPluginVersion, userId, correlationId }, ['valuationPluginId','valuationPluginVersion','userId','correlationId'],'valuationPluginAudit'); return Object.freeze({ valuationPluginActionId:createOpaqueId('VPACT'), valuationPluginId, valuationPluginVersion, valuationModelId, valuationModelVersion, valuationExecutionId, valuationInputPackageId, userId, correlationId, timestamp:new Date().toISOString() }); }
