import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
import { DecisionInputType, assertNoExecutionLogic } from '../contracts/index.js';
export class RecommendationArtifactDecisionAdapter { adapt(rec){ if(!rec?.recommendationArtifactId||!rec?.recommendationSchemaVersion) throw new Error('recommendation artifact is required'); assertNoExecutionLogic(rec,'recommendation decision input'); return Object.freeze({ inputType:DecisionInputType.recommendationArtifact, recommendationArtifactId:rec.recommendationArtifactId, recommendationDirection:rec.recommendationDirection, rationale:rec.rationale }); } rejectRawScoreArtifact(){ throw new Error('Raw score artifacts are not decision inputs'); } rejectRawValuationArtifact(){ throw new Error('Raw valuation artifacts are not decision inputs'); }}
export class EvidenceReferenceDecisionAdapter { adapt(ref){ return Object.freeze({ inputType:DecisionInputType.evidenceReference, ...ref }); }}
export class MethodologyReferenceDecisionAdapter { adapt(ref){ return Object.freeze({ inputType:DecisionInputType.methodologyReference, ...ref }); }}
export class ScoringReferenceDecisionAdapter { adapt(ref){ return Object.freeze({ inputType:DecisionInputType.scoringReference, ...ref }); }}
export class ValuationReferenceDecisionAdapter { adapt(ref){ return Object.freeze({ inputType:DecisionInputType.valuationReference, ...ref }); }}
export class DecisionInputPackage { constructor({ decisionModelId, decisionModelVersion, recommendationInput, references=[] }){ if(!recommendationInput) throw new Error('recommendationInput is required'); return Object.freeze({ inputPackageId:createOpaqueId('DINP'), decisionModelId, decisionModelVersion, recommendationInput, references:Object.freeze(references.slice()), createdAt:new Date().toISOString() }); }}
export class DecisionInputAdapterRegistry { constructor(){ this.adapters=new Map(); } register(type, adapter){ this.adapters.set(type,adapter); return adapter; } get(type){ const a=this.adapters.get(type); if(!a) throw new Error(`Decision adapter not found: ${type}`); return a; }}
