import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
import { EvidenceRecordStatus, EvidenceCertificationStatus, assertNoInvestmentAnalysis, assertRequired, stableHash } from '../contracts/index.js';
export class EvidenceRecordValidator { validate(record){ assertRequired(record,['evidenceRecordId','evidenceVersionId','evidenceType','title','source','provenance','workflowInstanceId','status','certificationStatus','version','createdBy','createdAt'],'evidenceRecord'); assertNoInvestmentAnalysis({ evidenceType: record.evidenceType, title: record.title, description: record.description, source: record.source, provenance: record.provenance, status: record.status, certificationStatus: record.certificationStatus },'Evidence record'); return true; } }
export class EvidenceVersionRegistry { constructor(){ this.versions=new Map(); } add(record){ const list=this.versions.get(record.evidenceRecordId)||[]; list.push(record); this.versions.set(record.evidenceRecordId,list); return record; } byRecord(id){ return Object.freeze((this.versions.get(id)||[]).slice()); } get(id,version){ return (this.versions.get(id)||[]).find(v=>v.version===version)||null; } }
export class EvidenceRegistry { constructor({ diagnostics }={}){ this.records=new Map(); this.versionRegistry=new EvidenceVersionRegistry(); this.validator=new EvidenceRecordValidator(); this.diagnostics=diagnostics; }
  create({ evidenceType='research-source', title, description='', source, provenance, workflowInstanceId, researchDocumentId=null, sourceArtifactId=null, evidenceCandidateId=null, createdBy='system' }={}){ const now=new Date().toISOString(); const record=deepFreeze({ evidenceRecordId:createOpaqueId('EVID'), evidenceVersionId:createOpaqueId('EVIDV'), evidenceType, title, description, source, provenance, workflowInstanceId, researchDocumentId, sourceArtifactId, evidenceCandidateId, status:EvidenceRecordStatus.Draft, certificationStatus:EvidenceCertificationStatus.Uncertified, version:1, contentHash:null, createdBy, createdAt:now, updatedAt:now }); this.validator.validate(record); this.records.set(record.evidenceRecordId,record); this.versionRegistry.add(record); this.diagnostics?.record?.('evidence.record.created',{ evidenceRecordId:record.evidenceRecordId }); return record; }
  update(id, patch){ const current=this.get(id); if(current.status===EvidenceRecordStatus.Certified) throw new Error('Certified evidence is immutable'); const next=deepFreeze({ ...current, ...patch, updatedAt:new Date().toISOString() }); this.validator.validate(next); this.records.set(id,next); return next; }
  markCertified(id){ const current=this.get(id); const hash=stableHash({ title:current.title, description:current.description, source:current.source, provenance:current.provenance, version:current.version }); const next=deepFreeze({ ...current, status:EvidenceRecordStatus.Certified, certificationStatus:EvidenceCertificationStatus.Certified, contentHash:hash, updatedAt:new Date().toISOString() }); this.records.set(id,next); this.versionRegistry.add(next); return next; }
  createVersion(id,{ correctionReason, patch={}, createdBy='system' }={}){ if(!correctionReason) throw new Error('correctionReason is required'); const current=this.get(id); const next=deepFreeze({ ...current, ...patch, evidenceVersionId:createOpaqueId('EVIDV'), version:current.version+1, status:EvidenceRecordStatus.Draft, certificationStatus:EvidenceCertificationStatus.Uncertified, contentHash:null, correctionReason, createdBy, updatedAt:new Date().toISOString() }); this.validator.validate(next); this.records.set(id,next); this.versionRegistry.add(next); return next; }
  get(id){ const r=this.records.get(id); if(!r) throw new Error(`Evidence not found: ${id}`); return r; } byWorkflow(id){ return Object.freeze([...this.records.values()].filter(r=>r.workflowInstanceId===id)); } byDocument(id){ return Object.freeze([...this.records.values()].filter(r=>r.researchDocumentId===id)); } byArtifact(id){ return Object.freeze([...this.records.values()].filter(r=>r.sourceArtifactId===id)); } byCandidate(id){ return Object.freeze([...this.records.values()].filter(r=>r.evidenceCandidateId===id)); }}
export class EvidenceRecordFactory { createFromCandidate({ candidate, provenance, registry, title='Evidence record' }){ return registry.create({ title, source:{ candidateId:candidate.evidenceCandidateId }, provenance, workflowInstanceId:candidate.workflowInstanceId, researchDocumentId:candidate.researchDocumentId, sourceArtifactId:candidate.sourceArtifactId, evidenceCandidateId:candidate.evidenceCandidateId, createdBy:candidate.preparedByUserId }); } }
export const EvidenceRecord = Object.freeze({});
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
