export const ResearchModuleStatus = Object.freeze({ draft:'draft', active:'active', deprecated:'deprecated', retired:'retired' });
export const ResearchEventType = Object.freeze({ ResearchModuleRegistered:'ResearchModuleRegistered', ResearchWorkspaceOpened:'ResearchWorkspaceOpened', ResearchDocumentCreated:'ResearchDocumentCreated', ResearchDocumentUpdated:'ResearchDocumentUpdated', ResearchArtifactRegistered:'ResearchArtifactRegistered', ResearchArtifactLinked:'ResearchArtifactLinked', ResearchArtifactArchived:'ResearchArtifactArchived', ResearchContextProjected:'ResearchContextProjected', ResearchActivityRecorded:'ResearchActivityRecorded' });
export const ResearchCommandType = Object.freeze({ OpenResearchWorkspace:'OpenResearchWorkspace', CreateResearchDocument:'CreateResearchDocument', UpdateResearchDocumentOutline:'UpdateResearchDocumentOutline', RegisterResearchArtifact:'RegisterResearchArtifact', LinkResearchArtifact:'LinkResearchArtifact', ArchiveResearchArtifact:'ArchiveResearchArtifact', ProjectResearchContext:'ProjectResearchContext', RecordResearchActivity:'RecordResearchActivity' });
export const ResearchPermissionAction = Object.freeze({ viewResearch:'viewResearch', openResearchWorkspace:'openResearchWorkspace', createResearchDocument:'createResearchDocument', updateResearchDocumentOutline:'updateResearchDocumentOutline', registerResearchArtifact:'registerResearchArtifact', linkResearchArtifact:'linkResearchArtifact', archiveResearchArtifact:'archiveResearchArtifact', readResearchContext:'readResearchContext' });
export const ResearchArtifactType = Object.freeze({ note:'note', sourceReference:'source-reference', question:'question', attachmentReference:'attachment-reference', meetingReference:'meeting-reference', internalComment:'internal-comment' });
export const ResearchDocumentType = Object.freeze({ researchNote:'research-note', meetingNote:'meeting-note', sourceSummary:'source-summary', questionList:'question-list', diligenceOutline:'diligence-outline' });
export const ResearchLifecycleState = Object.freeze({ Draft:'Draft', Active:'Active', Archived:'Archived' });

export const forbiddenResearchTerms = Object.freeze(['valuation','score','scoring','rating','recommendation','recommend','market data','provider','forecast','discounted cash flow','dcf','relative valuation','factor model','portfolio','risk calculation','decision automation','investment opinion','conclusion','ticker','marketcap','revenue','price']);
export function assertNoResearchIntelligence(value, label='research') { const text=JSON.stringify(value||{}).toLowerCase(); for (const term of forbiddenResearchTerms) if (text.includes(term)) throw new Error(`${label} contains forbidden research intelligence: ${term}`); return true; }
export function assertRequired(record, fields, label='record') { for (const f of fields) if (record?.[f]===undefined || record?.[f]===null || record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function validateResearchCommand(type) { if (!Object.values(ResearchCommandType).includes(type)) throw new Error(`Unsupported Research command: ${type}`); assertNoResearchIntelligence(type, 'Research command'); return true; }
export function validateSubject(subject) { if (!subject) return true; assertRequired(subject, ['type','id','label'], 'subject'); for (const forbidden of ['ticker','marketCap','revenue','price','securityId','companyId','portfolioId']) if (subject[forbidden] !== undefined) throw new Error(`Forbidden Sprint 4 subject field: ${forbidden}`); return true; }
export function createResearchActivityEvent({ activityId, workflowInstanceId, researchDocumentId=null, userId='system', correlationId, type=ResearchEventType.ResearchActivityRecorded, payload={} } = {}) { assertRequired({ activityId, workflowInstanceId, userId, correlationId }, ['activityId','workflowInstanceId','userId','correlationId'], 'researchActivity'); return Object.freeze({ type, payload:Object.freeze(payload), metadata:Object.freeze({ activityId, workflowInstanceId, researchDocumentId, userId, timestamp:new Date().toISOString(), correlationId }) }); }
