import { assertNoValuationLogic } from '../contracts/index.js';
class BaseProjection { constructor({ projectionId, supportedEvents }){ this.definition=Object.freeze({ projectionId, snapshotCompatible:true, projectionVersion:'1.0.0', supportedEvents:Object.freeze(supportedEvents) }); this.state=Object.freeze({}); } apply(event){ if(!this.definition.supportedEvents.includes(event.type)) throw new Error(`Unsupported valuation event: ${event.type}`); assertNoValuationLogic(event,'Valuation projection'); this.state=deepFreeze({ ...this.state, lastEventType:event.type, payload:event.payload||{}, updatedAt:new Date().toISOString() }); return this.state; } snapshot(){ return deepFreeze({ definition:this.definition, state:this.state }); }}
export class ValuationModelProjection extends BaseProjection { constructor(){ super({ projectionId:'valuation.model', supportedEvents:['ValuationModelRegistered','ValuationVersionCreated'] }); }}
export class ValuationLifecycleProjection extends BaseProjection { constructor(){ super({ projectionId:'valuation.lifecycle', supportedEvents:['ValuationModelActivated','ValuationModelDeprecated','ValuationModelRetired'] }); }}
export class ValuationExecutionProjection extends BaseProjection { constructor(){ super({ projectionId:'valuation.execution', supportedEvents:['ValuationDryRunCompleted','ValuationValidationCompleted'] }); }}
export class ValuationInputPackageProjection extends BaseProjection { constructor(){ super({ projectionId:'valuation.inputPackage', supportedEvents:['ValuationInputPackageCreated'] }); }}
export class ValuationAuditProjection extends BaseProjection { constructor(){ super({ projectionId:'valuation.audit', supportedEvents:['ValuationExecutionAudited'] }); }}
export class ValuationProjectionRegistry { constructor(){ this.projections=new Map(); } register(p){ this.projections.set(p.definition.projectionId,p); return p; } registerDefaults(){ [new ValuationModelProjection(),new ValuationLifecycleProjection(),new ValuationExecutionProjection(),new ValuationInputPackageProjection(),new ValuationAuditProjection()].forEach(p=>this.register(p)); return this; } get(id){ const p=this.projections.get(id); if(!p) throw new Error(`Projection not found: ${id}`); return p; } update(id,event){ return this.get(id).apply(event); }}
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
