import { FlagStatus } from '../../../../packages/feature-flags/src/index.js';
import { InMemorySnapshotStore } from '../../../../packages/snapshot-engine/src/index.js';
import { RECOMMENDATION_FRAMEWORK_FEATURE_FLAG } from './contracts/index.js';
import { createPlaceholderRecommendationManifest } from './models/index.js';
import { RecommendationModelRegistry, RecommendationModelVersionRegistry } from './registry/index.js';
import { RecommendationLifecycleManager } from './lifecycle/index.js';
import { RecommendationConfigurationRegistry } from './configuration/index.js';
import { RecommendationInputPackage, RecommendationInputAdapterRegistry, ScoreArtifactRecommendationAdapter, EvidenceReferenceRecommendationAdapter, MethodologyReferenceRecommendationAdapter, ResearchReferenceRecommendationAdapter, ValuationReferenceRecommendationAdapter } from './inputs/index.js';
import { RecommendationPolicyRegistry, RecommendationPolicyEvaluator } from './policies/index.js';
import { RecommendationRationaleBuilder } from './rationale/index.js';
import { RecommendationArtifactRegistry, RecommendationArtifactVersionRegistry } from './artifacts/index.js';
import { RecommendationAuditTrail } from './audit/index.js';
import { RecommendationSnapshotAdapter } from './snapshots/index.js';
import { RecommendationReplayAdapter } from './replay/index.js';
import { RecommendationPermissionRegistry, RecommendationPermissionGate, registerDefaultRecommendationPermissions } from './permissions/index.js';
import { RecommendationDiagnostics } from './diagnostics/index.js';
import { RecommendationProjectionRegistry } from './projections/index.js';
import { RecommendationIntegrationHarness } from './testing/index.js';

export function createRecommendationFramework({ app }={}){ const c=app.container; const flags=c.resolve('featureFlagRegistry'); if(!flags.get(RECOMMENDATION_FRAMEWORK_FEATURE_FLAG)) flags.register({ flag_id:RECOMMENDATION_FRAMEWORK_FEATURE_FLAG, default_enabled:true, owner:'recommendation-framework', status:FlagStatus.active }); const modelRegistry=new RecommendationModelRegistry(); const versionRegistry=new RecommendationModelVersionRegistry(); const lifecycleManager=new RecommendationLifecycleManager(); const configurationRegistry=new RecommendationConfigurationRegistry(); const inputAdapterRegistry=new RecommendationInputAdapterRegistry(); const scoreAdapter=new ScoreArtifactRecommendationAdapter(); inputAdapterRegistry.register('scoreArtifact', scoreAdapter); inputAdapterRegistry.register('evidenceReference', new EvidenceReferenceRecommendationAdapter()); inputAdapterRegistry.register('methodologyReference', new MethodologyReferenceRecommendationAdapter()); inputAdapterRegistry.register('researchReference', new ResearchReferenceRecommendationAdapter()); inputAdapterRegistry.register('valuationReference', new ValuationReferenceRecommendationAdapter()); const policyRegistry=new RecommendationPolicyRegistry(); const policyEvaluator=new RecommendationPolicyEvaluator(); const rationaleBuilder=new RecommendationRationaleBuilder(); const artifactRegistry=new RecommendationArtifactRegistry(); const artifactVersionRegistry=new RecommendationArtifactVersionRegistry(); const auditTrail=new RecommendationAuditTrail(); const snapshotStore=new InMemorySnapshotStore(); const snapshotAdapter=new RecommendationSnapshotAdapter({ snapshotStore }); const replayAdapter=new RecommendationReplayAdapter(); const permissionRegistry=registerDefaultRecommendationPermissions(new RecommendationPermissionRegistry()); const permissionGate=new RecommendationPermissionGate({ registry:permissionRegistry }); const diagnostics=new RecommendationDiagnostics({ diagnostics:c.resolve('diagnostics') }); const projectionRegistry=new RecommendationProjectionRegistry().registerDefaults(); const runtime=Object.freeze({ createManifest:createPlaceholderRecommendationManifest, modelRegistry, versionRegistry, lifecycleManager, configurationRegistry, RecommendationInputPackage, inputAdapterRegistry, scoreAdapter, policyRegistry, policyEvaluator, rationaleBuilder, artifactRegistry, artifactVersionRegistry, auditTrail, snapshotStore, snapshotAdapter, replayAdapter, permissionRegistry, permissionGate, diagnostics, projectionRegistry }); const recommendationTestHarness=new RecommendationIntegrationHarness({ runtime }); const full=Object.freeze({ ...runtime, recommendationTestHarness }); for(const [key,value] of Object.entries(full)) if(!c.has(key)) c.register(key,value); return full; }
