import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const EvidenceReviewDecisions=Object.freeze(['approve-evidence-certification','reject-evidence-certification','request-evidence-correction','archive-evidence']);
const forbidden=Object.freeze(['approve-investment','reject-investment','recommend-buy','recommend-sell','assign-rating']);
export class EvidenceReviewLifecycle { transition(from,to){ const allowed={ NotStarted:['InProgress'], InProgress:['Approved','Rejected','CorrectionRequested'], Approved:['Completed'], Rejected:['Completed'], CorrectionRequested:['Completed'], Completed:[] }; if(!(allowed[from]||[]).includes(to)) throw new Error(`Invalid evidence review transition: ${from} -> ${to}`); return to; } }
export class EvidenceReviewRegistry { constructor(){ this.reviews=new Map(); this.lifecycle=new EvidenceReviewLifecycle(); }
  start({ evidenceRecordId, reviewerUserId='reviewer' }={}){ const r=Object.freeze({ evidenceReviewId:createOpaqueId('EREV'), evidenceRecordId, reviewerUserId, status:'InProgress', decisions:Object.freeze([]), createdAt:new Date().toISOString() }); this.reviews.set(r.evidenceReviewId,r); return r; }
  decide(id,decision){ if(forbidden.includes(decision)) throw new Error(`Forbidden investment decision: ${decision}`); if(!EvidenceReviewDecisions.includes(decision)) throw new Error(`Unsupported evidence review decision: ${decision}`); const r=this.get(id); const status=decision==='approve-evidence-certification'?'Approved':decision==='reject-evidence-certification'?'Rejected':decision==='request-evidence-correction'?'CorrectionRequested':'Completed'; this.lifecycle.transition(r.status,status); const next=Object.freeze({ ...r, status, decisions:Object.freeze([...r.decisions,{ decision, at:new Date().toISOString() }]) }); this.reviews.set(id,next); return next; }
  complete(id){ const r=this.get(id); const next=Object.freeze({ ...r, status:this.lifecycle.transition(r.status,'Completed') }); this.reviews.set(id,next); return next; } get(id){ const r=this.reviews.get(id); if(!r) throw new Error(`Review not found: ${id}`); return r; }}
export const EvidenceReview = Object.freeze({}); export const EvidenceReviewerAssignment = Object.freeze({}); export const EvidenceReviewDecisionRecord = Object.freeze({});
