import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';
import { ResearchTemplateType, assertNoInvestmentAnalysis, assertRequired, validateVersioned, ResearchIntelligenceEventType } from '../contracts/index.js';

export class ResearchTemplateValidator { validate(template){ assertRequired(template, ['researchTemplateId','templateType','name','sectionDefinitions','checklistDefinitions','owner','version','status','createdAt','ResearchTemplateVersion','ResearchChecklistVersion'], 'researchTemplate'); if(!Object.values(ResearchTemplateType).includes(template.templateType)) throw new Error(`Invalid template type: ${template.templateType}`); validateVersioned(template,'ResearchTemplateVersion','researchTemplate'); assertNoInvestmentAnalysis(template,'Research template'); return true; } }
export class ResearchTemplateRegistry { constructor({ eventBus, diagnostics }={}){ this.templates=new Map(); this.validator=new ResearchTemplateValidator(); this.eventBus=eventBus; this.diagnostics=diagnostics; }
  register(template){ const record=Object.freeze({ researchTemplateId:createOpaqueId('RTPL'), description:'', status:'active', createdAt:new Date().toISOString(), ResearchTemplateVersion:template.version, ResearchChecklistVersion:template.version, ...template }); this.validator.validate(record); const key=`${record.researchTemplateId}@${record.version}`; if(this.templates.has(key)) throw new Error(`Research template already registered: ${key}`); this.templates.set(key, deepFreeze(record)); this.diagnostics?.record?.('researchIntelligence.template.registered', { researchTemplateId:record.researchTemplateId }); return this.get(record.researchTemplateId, record.version); }
  get(id,version){ return this.templates.get(`${id}@${version}`)||null; } list(){ return Object.freeze([...this.templates.values()]); }}
export class ResearchTemplateApplicator { constructor({ sectionRegistry, checklistService, diagnostics }={}){ this.sectionRegistry=sectionRegistry; this.checklistService=checklistService; this.diagnostics=diagnostics; }
  apply({ template, researchDocumentId, workflowInstanceId, userId='system' }){ assertNoInvestmentAnalysis(template,'Research template application'); const sections=(template.sectionDefinitions||[]).map(def=>this.sectionRegistry.create({ researchDocumentId, sectionType:def.sectionType, title:def.title, workflowInstanceId, authorUserId:userId })); const checklistItems=(template.checklistDefinitions||[]).map(def=>this.checklistService.createItem({ researchDocumentId, label:def.label, required:!!def.required, version:template.ResearchChecklistVersion })); this.diagnostics?.record?.('researchIntelligence.template.applied', { researchTemplateId:template.researchTemplateId, researchDocumentId }); return Object.freeze({ type:ResearchIntelligenceEventType.ResearchTemplateApplied, researchDocumentId, sections:Object.freeze(sections), checklistItems:Object.freeze(checklistItems) }); }}
export function createDefaultResearchTemplate(overrides={}){ return Object.freeze({ researchTemplateId:'RTPL_DEFAULT_RESEARCH_PROCESS', templateType:ResearchTemplateType.companyResearchStructure, name:'Research Process Structure', description:'Structured research process template without analytical methodology.', sectionDefinitions:Object.freeze([{ sectionType:'overview', title:'Overview' }, { sectionType:'key-questions', title:'Key Questions' }, { sectionType:'source-notes', title:'Source Notes' }, { sectionType:'open-items', title:'Open Items' }, { sectionType:'references', title:'References' }]), checklistDefinitions:Object.freeze([{ label:'Document structure prepared', required:true }, { label:'Source references linked', required:true }, { label:'Open questions recorded', required:false }]), owner:'research-intelligence', version:'1.0.0', ResearchTemplateVersion:'1.0.0', ResearchChecklistVersion:'1.0.0', status:'active', createdAt:new Date().toISOString(), ...overrides }); }
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
