import { FlagStatus } from '../../../../packages/feature-flags/src/index.js';
import { InMemorySnapshotStore } from '../../../../packages/snapshot-engine/src/index.js';
import { VALUATION_PLUGIN_FEATURE_FLAG } from './contracts/index.js';
import { ValuationPluginRegistry, ValuationPluginVersionRegistry } from './registry/index.js';
import { ValuationPluginLifecycleManager } from './lifecycle/index.js';
import { ValuationPluginCompatibilityValidator } from './compatibility/index.js';
import { ValuationPluginLoader } from './loading/index.js';
import { ValuationPluginExecutionAdapter } from './execution/index.js';
import { ValuationPluginOutputNormalizerShell } from './outputs/index.js';
import { ValuationPluginAuditTrail } from './audit/index.js';
import { ValuationPluginSnapshotAdapter } from './snapshots/index.js';
import { ValuationPluginReplayAdapter } from './replay/index.js';
import { ValuationPluginPermissionRegistry, ValuationPluginPermissionGate, registerDefaultPluginPermissions } from './permissions/index.js';
import { ValuationPluginDiagnostics } from './diagnostics/index.js';
import { ValuationPluginProjectionRegistry } from './projections/index.js';
import { ValuationPluginContributionRegistry } from './contributions/index.js';
import { ValuationPluginIntegrationHarness } from './testing/index.js';
export function createValuationPluginFoundation({ app }={}){
  const c=app.container;
  const flags=c.resolve('featureFlagRegistry');
  if(!flags.get(VALUATION_PLUGIN_FEATURE_FLAG)) flags.register({ flag_id:VALUATION_PLUGIN_FEATURE_FLAG, default_enabled:true, owner:'valuation-plugin-foundation', status:FlagStatus.active });
  const diagnostics=new ValuationPluginDiagnostics({ diagnostics:c.resolve('diagnostics') });
  const pluginRegistry=new ValuationPluginRegistry();
  const versionRegistry=new ValuationPluginVersionRegistry();
  const lifecycleManager=new ValuationPluginLifecycleManager();
  const compatibilityValidator=new ValuationPluginCompatibilityValidator();
  const loader=new ValuationPluginLoader({ compatibilityValidator });
  const executionAdapter=new ValuationPluginExecutionAdapter();
  const outputNormalizer=new ValuationPluginOutputNormalizerShell();
  const auditTrail=new ValuationPluginAuditTrail();
  const snapshotStore=new InMemorySnapshotStore();
  const snapshotAdapter=new ValuationPluginSnapshotAdapter({ snapshotStore });
  const replayAdapter=new ValuationPluginReplayAdapter();
  const permissionRegistry=registerDefaultPluginPermissions(new ValuationPluginPermissionRegistry());
  const permissionGate=new ValuationPluginPermissionGate({ registry:permissionRegistry });
  const projectionRegistry=new ValuationPluginProjectionRegistry().registerDefaults();
  const contributionRegistry=new ValuationPluginContributionRegistry({ featureFlagRegistry:flags, permissionGate });
  contributionRegistry.register({ contributionId:'register-valuation-plugin', permission:'registerValuationPlugin' });
  contributionRegistry.register({ contributionId:'load-valuation-plugin', permission:'loadValuationPlugin' });
  contributionRegistry.register({ contributionId:'run-valuation-plugin-validation', permission:'runValuationPluginValidation' });
  const runtime=Object.freeze({ diagnostics, pluginRegistry, versionRegistry, lifecycleManager, compatibilityValidator, loader, executionAdapter, outputNormalizer, auditTrail, snapshotStore, snapshotAdapter, replayAdapter, permissionRegistry, permissionGate, projectionRegistry, contributionRegistry });
  const pluginTestHarness=new ValuationPluginIntegrationHarness({ runtime });
  const full=Object.freeze({ ...runtime, pluginTestHarness });
  for(const [key,value] of Object.entries(full)) if(!c.has(key)) c.register(key,value);
  return full;
}
