import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';
import { ResearchSectionType, assertNoInvestmentAnalysis, assertRequired } from '../contracts/index.js';
export const ResearchSectionLifecycleState = Object.freeze({ Draft:'Draft', InReview:'InReview', Accepted:'Accepted', NeedsRevision:'NeedsRevision', Archived:'Archived' });
export class ResearchSectionLifecycle { transition(from,to){ if(!Object.values(ResearchSectionLifecycleState).includes(to)) throw new Error(`Invalid section state: ${to}`); if(from===ResearchSectionLifecycleState.Archived) throw new Error('Archived section cannot transition'); return to; } }
export class ResearchSectionRegistry { constructor({ diagnostics }={}){ this.sections=new Map(); this.lifecycle=new ResearchSectionLifecycle(); this.diagnostics=diagnostics; }
  create({ researchDocumentId, sectionType, title, workflowInstanceId, authorUserId='system' }={}){ assertRequired({ researchDocumentId, sectionType, title, workflowInstanceId }, ['researchDocumentId','sectionType','title','workflowInstanceId'], 'researchSection'); if(!Object.values(ResearchSectionType).includes(sectionType)) throw new Error(`Invalid section type: ${sectionType}`); assertNoInvestmentAnalysis({ title, sectionType }, 'Research section'); const now=new Date().toISOString(); const s=deepFreeze({ researchSectionId:createOpaqueId('RSEC'), researchDocumentId, sectionType, title, workflowInstanceId, authorUserId, status:ResearchSectionLifecycleState.Draft, createdAt:now, updatedAt:now }); this.sections.set(s.researchSectionId,s); this.diagnostics?.record?.('researchIntelligence.section.created', { researchSectionId:s.researchSectionId }); return s; }
  transition(id,to){ const s=this.get(id); const status=this.lifecycle.transition(s.status,to); const next=deepFreeze({ ...s, status, updatedAt:new Date().toISOString() }); this.sections.set(id,next); return next; }
  get(id){ const s=this.sections.get(id); if(!s) throw new Error(`Research section not found: ${id}`); return s; } byDocument(id){ return Object.freeze([...this.sections.values()].filter(s=>s.researchDocumentId===id)); }}
export class AnalystNoteRegistry { constructor({ diagnostics }={}){ this.notes=new Map(); this.diagnostics=diagnostics; }
  create({ researchDocumentId, researchSectionId, authorUserId='system', noteText, linkedArtifactIds=[] }={}){ assertRequired({ researchDocumentId, researchSectionId, noteText }, ['researchDocumentId','researchSectionId','noteText'], 'analystNote'); assertNoInvestmentAnalysis({ noteText }, 'Analyst note'); const now=new Date().toISOString(); const note=deepFreeze({ analystNoteId:createOpaqueId('ANOTE'), researchDocumentId, researchSectionId, authorUserId, noteText, linkedArtifactIds:Object.freeze(linkedArtifactIds.slice()), status:'Draft', createdAt:now, updatedAt:now }); this.notes.set(note.analystNoteId,note); this.diagnostics?.record?.('researchIntelligence.note.created', { analystNoteId:note.analystNoteId }); return note; }
  update(id,{ noteText, linkedArtifactIds }={}){ const n=this.get(id); const next=deepFreeze({ ...n, noteText:noteText??n.noteText, linkedArtifactIds:Object.freeze((linkedArtifactIds??n.linkedArtifactIds).slice()), updatedAt:new Date().toISOString() }); assertNoInvestmentAnalysis(next,'Analyst note'); this.notes.set(id,next); return next; }
  get(id){ const n=this.notes.get(id); if(!n) throw new Error(`Analyst note not found: ${id}`); return n; }}
export const ResearchSection = Object.freeze({});
export const AnalystNote = Object.freeze({});
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
