import { DCF_FORMULA_VERSION, TerminalValueAssumptionType, finiteNumber } from '../contracts/index.js';
export class DCFFormulaTrace { constructor(){ this.steps=[]; } record(step, value, meta={}){ const r=Object.freeze({ step, value, meta:Object.freeze({ ...meta }) }); this.steps.push(r); return r; } list(){ return Object.freeze(this.steps.slice()); }}
export class PresentValueCalculator { discountFactor(rate, period){ return 1/Math.pow(1+rate, period); } presentValue(cashFlow, rate, period){ return cashFlow*this.discountFactor(rate, period); }}
export class TerminalValueCalculator { calculate(input){ const last=input.forecastCashFlows[input.forecastCashFlows.length-1]; if(input.terminalValueAssumption.type===TerminalValueAssumptionType.explicitTerminalValue) return input.terminalValueAssumption.terminalValue; if(input.terminalValueAssumption.type===TerminalValueAssumptionType.perpetualGrowth){ const g=input.terminalValueAssumption.terminalGrowthRate; return last.cashFlow*(1+g)/(input.discountRate-g); } throw new Error('Unsupported terminal value assumption for calculation'); }}
export class EnterpriseValueCalculator { calculate(explicitPv, terminalPv){ return explicitPv+terminalPv; }}
export class EquityValueBridge { calculate({ enterpriseValue, netDebt=0, minorityInterest=0, investmentsAndCash=0 }){ return enterpriseValue - netDebt - minorityInterest + investmentsAndCash; }}
export class PerShareValueCalculator { calculate(equityValue, shares){ if(shares===undefined) return null; if(shares<=0) throw new Error('Division by zero or negative shares'); return equityValue/shares; }}
export class DCFFormulaEngine { constructor(){ this.pv=new PresentValueCalculator(); this.tv=new TerminalValueCalculator(); this.ev=new EnterpriseValueCalculator(); this.bridge=new EquityValueBridge(); this.perShare=new PerShareValueCalculator(); }
  execute(input){ const trace=new DCFFormulaTrace(); let explicitPv=0; input.forecastCashFlows.forEach((cf, idx)=>{ const period=idx+1; const df=this.pv.discountFactor(input.discountRate, period); const pv=this.pv.presentValue(cf.cashFlow, input.discountRate, period); explicitPv+=pv; trace.record('forecast-cash-flow', cf.cashFlow, { period }); trace.record('discount-factor', df, { period }); trace.record('present-value', pv, { period }); }); const terminalValue=this.tv.calculate(input); trace.record('terminal-value', terminalValue); const terminalPv=this.pv.presentValue(terminalValue, input.discountRate, input.forecastCashFlows.length); trace.record('present-value-terminal-value', terminalPv); const enterpriseValue=this.ev.calculate(explicitPv, terminalPv); trace.record('enterprise-value', enterpriseValue); const equityValue=this.bridge.calculate({ enterpriseValue, netDebt:input.netDebt, minorityInterest:input.minorityInterest, investmentsAndCash:input.investmentsAndCash }); trace.record('equity-value', equityValue); const perShareValue=this.perShare.calculate(equityValue, input.dilutedSharesOutstanding); trace.record('per-share-value', perShareValue); return Object.freeze({ dcfFormulaVersion:DCF_FORMULA_VERSION, enterpriseValue, equityValue, perShareValue, currency:input.currency, formulaTrace:trace.list() }); }}
