import { ProductCommandContribution, ProductNavigationContribution, ProductNotificationContribution, ProductActivityContribution } from '../../../product/index.js';
import { ResearchPermissionAction, assertNoResearchIntelligence } from '../contracts/index.js';
import { RESEARCH_FEATURE_FLAG, RESEARCH_MODULE_ID } from '../manifest/index.js';
export const forbiddenResearchPermissions = Object.freeze(['approveInvestment','recommendInvestment','calculateValuation','scoreCompany','assignRating','rebalancePortfolio']);
export function registerResearchPermissions(permissionRegistry) { for (const action of Object.values(ResearchPermissionAction)) if (!permissionRegistry.get?.(RESEARCH_MODULE_ID, action)) permissionRegistry.register({ productModuleId:RESEARCH_MODULE_ID, action, effect:'allow' }); return permissionRegistry; }
export function validateResearchPermission(action){ if(forbiddenResearchPermissions.includes(action)) throw new Error(`Forbidden Research permission: ${action}`); if(!Object.values(ResearchPermissionAction).includes(action)) throw new Error(`Unsupported Research permission: ${action}`); return true; }
export function createResearchCommandContributions() { const commands=[['open-research-workspace','openResearchWorkspace'],['create-research-document','createResearchDocument'],['register-research-artifact','registerResearchArtifact'],['link-research-artifact','linkResearchArtifact'],['archive-research-artifact','archiveResearchArtifact']]; return Object.freeze(commands.map(([contributionId, permission])=>ProductCommandContribution({ productModuleId:RESEARCH_MODULE_ID, contributionId, featureFlag:RESEARCH_FEATURE_FLAG, permission, execute:()=>Object.freeze({ status:'research-placeholder-command', businessLogic:false }) }))); }
export function createResearchNavigationContributions(){ return Object.freeze([ProductNavigationContribution({ productModuleId:RESEARCH_MODULE_ID, contributionId:'nav-research-foundation', featureFlag:RESEARCH_FEATURE_FLAG, permission:'openResearchWorkspace', label:'Research' })]); }
export function createResearchNotificationContributions(){ return Object.freeze([ProductNotificationContribution({ productModuleId:RESEARCH_MODULE_ID, contributionId:'notify-research-foundation', featureFlag:RESEARCH_FEATURE_FLAG, permission:'viewResearch' })]); }
export function createResearchActivityContributions(){ return Object.freeze([ProductActivityContribution({ productModuleId:RESEARCH_MODULE_ID, contributionId:'activity-research-foundation', featureFlag:RESEARCH_FEATURE_FLAG, permission:'viewResearch' })]); }
export function registerResearchContributions(contributionRegistry){ const all=[...createResearchCommandContributions(), ...createResearchNavigationContributions(), ...createResearchNotificationContributions(), ...createResearchActivityContributions()]; all.forEach(c=>{ assertNoResearchIntelligence(c, 'Research contribution'); if (!contributionRegistry.contributions?.some?.(existing => existing.contributionId === c.contributionId)) contributionRegistry.register(c); }); return Object.freeze(all); }
export const ResearchPermissionDefinitions = ResearchPermissionAction;
export const ResearchCommandContributions = createResearchCommandContributions;
export const ResearchNavigationContributions = createResearchNavigationContributions;
export const ResearchNotificationContributions = createResearchNotificationContributions;
export const ResearchActivityContributions = createResearchActivityContributions;
