import { assertNoInvestmentAnalysis } from '../contracts/index.js';
class BaseEvidenceProjection { constructor({ projectionId, supportedEvents }){ this.definition=Object.freeze({ projectionId, snapshotCompatible:true, projectionVersion:'1.0.0', supportedEvents:Object.freeze(supportedEvents) }); this.state=Object.freeze({}); } apply(event){ if(!this.definition.supportedEvents.includes(event.type)) throw new Error(`Unsupported evidence event: ${event.type}`); assertNoInvestmentAnalysis(event,'Evidence projection'); this.state=deepFreeze({ ...this.state, lastEventType:event.type, payload:event.payload||{}, updatedAt:new Date().toISOString() }); return this.state; } snapshot(){ return deepFreeze({ definition:this.definition, state:this.state }); }}
export class EvidenceRegistryProjection extends BaseEvidenceProjection { constructor(){ super({ projectionId:'evidence.registry', supportedEvents:['EvidenceRecordCreated','EvidenceVersionCreated','EvidenceArchived'] }); }}
export class EvidenceCertificationProjection extends BaseEvidenceProjection { constructor(){ super({ projectionId:'evidence.certification', supportedEvents:['EvidenceSubmittedForReview','EvidenceApproved','EvidenceRejected','EvidenceCertified'] }); }}
export class EvidenceReviewProjection extends BaseEvidenceProjection { constructor(){ super({ projectionId:'evidence.review', supportedEvents:['EvidenceReviewStarted','EvidenceApproved','EvidenceRejected','EvidenceCorrectionRequested'] }); }}
export class EvidenceTraceabilityProjection extends BaseEvidenceProjection { constructor(){ super({ projectionId:'evidence.traceability', supportedEvents:['EvidenceTraceLinked'] }); }}
export class EvidenceAuditProjection extends BaseEvidenceProjection { constructor(){ super({ projectionId:'evidence.audit', supportedEvents:['EvidenceAuditRecorded'] }); }}
export class EvidenceSnapshotProjection extends BaseEvidenceProjection { constructor(){ super({ projectionId:'evidence.snapshot', supportedEvents:['EvidenceSnapshotCreated'] }); }}
export class EvidenceProjectionRegistry { constructor(){ this.projections=new Map(); } register(p){ if(this.projections.has(p.definition.projectionId)) throw new Error(`Projection exists: ${p.definition.projectionId}`); this.projections.set(p.definition.projectionId,p); return p; } registerDefaults(){ [new EvidenceRegistryProjection(),new EvidenceCertificationProjection(),new EvidenceReviewProjection(),new EvidenceTraceabilityProjection(),new EvidenceAuditProjection(),new EvidenceSnapshotProjection()].forEach(p=>{ if(!this.projections.has(p.definition.projectionId)) this.register(p); }); return this; } get(id){ const p=this.projections.get(id); if(!p) throw new Error(`Projection not found: ${id}`); return p; } update(id,event){ return this.get(id).apply(event); }}
function deepFreeze(obj){ Object.freeze(obj); for(const v of Object.values(obj)) if(v&&typeof v==='object'&&!Object.isFrozen(v)) deepFreeze(v); return obj; }
