import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const PORTFOLIO_SCHEMA_VERSION='PORTFOLIO_SCHEMA_VERSION_1.0';
export const PORTFOLIO_FRAMEWORK_FEATURE_FLAG='portfolio_framework_foundation';
export const PortfolioFrameworkEventType=Object.freeze({ PortfolioRegistered:'PortfolioRegistered', PortfolioAccountRegistered:'PortfolioAccountRegistered', HoldingRegistered:'HoldingRegistered', HoldingUpdated:'HoldingUpdated', AllocationCreated:'AllocationCreated', AllocationUpdated:'AllocationUpdated', PortfolioIntentCreated:'PortfolioIntentCreated', PortfolioPolicyRegistered:'PortfolioPolicyRegistered', PortfolioConstraintRegistered:'PortfolioConstraintRegistered', PortfolioConstraintEvaluated:'PortfolioConstraintEvaluated', PortfolioExposureCalculated:'PortfolioExposureCalculated', PortfolioCompositionProjected:'PortfolioCompositionProjected', PortfolioChangeProposalCreated:'PortfolioChangeProposalCreated', PortfolioAuditRecorded:'PortfolioAuditRecorded', PortfolioSnapshotCreated:'PortfolioSnapshotCreated', PortfolioReplayCompleted:'PortfolioReplayCompleted' });
export const PortfolioFrameworkCommandType=Object.freeze({ RegisterPortfolio:'RegisterPortfolio', RegisterPortfolioAccount:'RegisterPortfolioAccount', RegisterHolding:'RegisterHolding', UpdateHolding:'UpdateHolding', CreateAllocation:'CreateAllocation', UpdateAllocation:'UpdateAllocation', CreatePortfolioIntent:'CreatePortfolioIntent', RegisterPortfolioPolicy:'RegisterPortfolioPolicy', RegisterPortfolioConstraint:'RegisterPortfolioConstraint', EvaluatePortfolioConstraint:'EvaluatePortfolioConstraint', CalculatePortfolioExposure:'CalculatePortfolioExposure', ProjectPortfolioComposition:'ProjectPortfolioComposition', CreatePortfolioChangeProposal:'CreatePortfolioChangeProposal', RecordPortfolioAudit:'RecordPortfolioAudit', CreatePortfolioSnapshot:'CreatePortfolioSnapshot', ReplayPortfolioArtifact:'ReplayPortfolioArtifact' });
export const PortfolioStatus=Object.freeze({ Active:'Active', Archived:'Archived', Watch:'Watch', Paper:'Paper', Model:'Model' });
export const PortfolioType=Object.freeze({ modelPortfolio:'model-portfolio', paperPortfolio:'paper-portfolio', watchPortfolio:'watch-portfolio', clientPortfolioPlaceholder:'client-portfolio-placeholder', fundPortfolioPlaceholder:'fund-portfolio-placeholder' });
export const PortfolioLifecycleState=Object.freeze({ Draft:'Draft', Registered:'Registered', Active:'Active', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const PortfolioArtifactStatus=Object.freeze({ Draft:'Draft', Active:'Active', Archived:'Archived' });
export const HoldingStatus=Object.freeze({ Active:'Active', Closed:'Closed', Archived:'Archived' });
export const AllocationStatus=Object.freeze({ Active:'Active', Archived:'Archived' });
export const PortfolioIntentStatus=Object.freeze({ Draft:'Draft', Active:'Active', Closed:'Closed' });
export const PortfolioChangeProposalStatus=Object.freeze({ Draft:'Draft', Proposed:'Proposed', Archived:'Archived' });
export const PortfolioPermissionAction=Object.freeze({ viewPortfolio:'viewPortfolio', registerPortfolio:'registerPortfolio', registerHolding:'registerHolding', createAllocation:'createAllocation', createPortfolioIntent:'createPortfolioIntent', evaluatePortfolioConstraint:'evaluatePortfolioConstraint', createPortfolioChangeProposal:'createPortfolioChangeProposal', readPortfolioAudit:'readPortfolioAudit', replayPortfolioState:'replayPortfolioState' });
export const ConstraintSeverity=Object.freeze({ info:'info', warning:'warning', breach:'breach' });
export const ExposureDimension=Object.freeze({ security:'security', company:'company', sector:'sector', industry:'industry', currency:'currency', exchange:'exchange' });
export const PortfolioIntentType=Object.freeze({ reviewPosition:'review-position', considerInclusion:'consider-inclusion', considerReduction:'consider-reduction', considerExit:'consider-exit', monitor:'monitor', noAction:'no-action' });
const forbidden=Object.freeze(['order','broker','trade','execution','exchange connectivity','settlement','clearing','custody','live market','routing','transaction cost','capital deployment','capital allocation','tax-lot','slippage','market impact','var','tracking error','beta','volatility','stress testing','scenario analysis','rebalance-now']);
export function assertRequired(record,fields,label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoExecutionLogic(value,label='portfolio'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z -]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden execution logic: ${term}`); } return true; }
export function validatePortfolioCommand(type){ if(!Object.values(PortfolioFrameworkCommandType).includes(type)) throw new Error(`Unsupported portfolio command: ${type}`); assertNoExecutionLogic(type,'portfolio command'); return true; }
export function createPortfolioAuditIdentity({ portfolioId=null, portfolioArtifactId=null, userId='system', correlationId }={}){ assertRequired({ userId, correlationId },['userId','correlationId'],'portfolioAudit'); return Object.freeze({ portfolioActionId:createOpaqueId('PACT'), portfolioId, portfolioArtifactId, userId, correlationId, timestamp:new Date().toISOString() }); }
