import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';

export const COMPANY_SECURITY_FEATURE_FLAG = 'company_security_domain_foundation';
export const DOMAIN_SCHEMA_VERSION = 'COMPANY_SECURITY_DOMAIN_1.0';
export const DomainCapability = Object.freeze({ identity:'identity', listing:'listing', classification:'classification', corporateActionMetadata:'corporate-action-metadata', validation:'validation' });
export const EntityOrigin = Object.freeze({ manual:'manual', import:'import', migration:'migration', testFixture:'test-fixture', futureProvider:'future-provider' });
export const MappingConfidence = Object.freeze({ authoritative:'authoritative', manual:'manual', unknown:'unknown' });
export const CompanySecurityEventType = Object.freeze({ CompanyRegistered:'CompanyRegistered', CompanyUpdated:'CompanyUpdated', CompanyStatusChanged:'CompanyStatusChanged', SecurityRegistered:'SecurityRegistered', SecurityUpdated:'SecurityUpdated', SecurityStatusChanged:'SecurityStatusChanged', ExchangeRegistered:'ExchangeRegistered', ListingRegistered:'ListingRegistered', ListingStatusChanged:'ListingStatusChanged', IdentifierRegistered:'IdentifierRegistered', IdentifierMapped:'IdentifierMapped', ClassificationAssigned:'ClassificationAssigned', CorporateActionMetadataRecorded:'CorporateActionMetadataRecorded', DomainValidationCompleted:'DomainValidationCompleted', DomainSnapshotCreated:'DomainSnapshotCreated' });
export const CompanySecurityCommandType = Object.freeze({ RegisterCompany:'RegisterCompany', UpdateCompany:'UpdateCompany', ChangeCompanyStatus:'ChangeCompanyStatus', RegisterSecurity:'RegisterSecurity', UpdateSecurity:'UpdateSecurity', ChangeSecurityStatus:'ChangeSecurityStatus', RegisterExchange:'RegisterExchange', RegisterListing:'RegisterListing', ChangeListingStatus:'ChangeListingStatus', RegisterIdentifier:'RegisterIdentifier', MapIdentifier:'MapIdentifier', AssignClassification:'AssignClassification', RecordCorporateActionMetadata:'RecordCorporateActionMetadata', ValidateDomainRecord:'ValidateDomainRecord', CreateDomainSnapshot:'CreateDomainSnapshot' });
export const CompanyStatus = Object.freeze({ Draft:'Draft', Active:'Active', Inactive:'Inactive', Delisted:'Delisted', Merged:'Merged', Archived:'Archived' });
export const SecurityStatus = Object.freeze({ Draft:'Draft', Active:'Active', Inactive:'Inactive', Delisted:'Delisted', Matured:'Matured', Archived:'Archived' });
export const SecurityType = Object.freeze({ equity:'equity', preferenceShare:'preference-share', depositoryReceipt:'depository-receipt', bond:'bond', convertible:'convertible', fundUnit:'fund-unit', other:'other' });
export const ListingStatus = Object.freeze({ Draft:'Draft', Active:'Active', Suspended:'Suspended', Delisted:'Delisted', Archived:'Archived' });
export const ExchangeStatus = Object.freeze({ Active:'Active', Inactive:'Inactive', Archived:'Archived' });
export const IdentifierType = Object.freeze({ IIPS_COMPANY_ID:'IIPS_COMPANY_ID', IIPS_SECURITY_ID:'IIPS_SECURITY_ID', ISIN:'ISIN', CUSIP:'CUSIP', SEDOL:'SEDOL', NSE_SYMBOL:'NSE_SYMBOL', BSE_CODE:'BSE_CODE', EXCHANGE_TICKER:'EXCHANGE_TICKER', LEI:'LEI', CIN:'CIN', FIGI:'FIGI', OTHER:'OTHER' });
export const CorporateActionType = Object.freeze({ split:'split', reverseSplit:'reverse-split', dividend:'dividend', bonus:'bonus', rightsIssue:'rights-issue', merger:'merger', spinOff:'spin-off', delist:'delist', nameChange:'name-change', tickerChange:'ticker-change', other:'other' });
export const ClassificationScheme = Object.freeze({ GICS:'GICS', ICB:'ICB', NAICS:'NAICS', IIPS_INTERNAL:'IIPS_INTERNAL', OTHER:'OTHER' });
export const DomainPermissionAction = Object.freeze({ viewCompany:'viewCompany', registerCompany:'registerCompany', updateCompany:'updateCompany', viewSecurity:'viewSecurity', registerSecurity:'registerSecurity', updateSecurity:'updateSecurity', registerExchange:'registerExchange', registerListing:'registerListing', mapIdentifier:'mapIdentifier', assignClassification:'assignClassification', recordCorporateActionMetadata:'recordCorporateActionMetadata', readDomainAudit:'readDomainAudit' });
const forbidden = Object.freeze(['valuation','discounted cash flow','dcf','relative valuation','multiple','factor model','financial statement','forecast','score','rating','buy','sell','hold','recommendation','target price','market data','provider integration','price','volume','revenue','profit','marketcap','portfolio','decision automation','investment opinion']);
export function assertRequired(record, fields, label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoInvestmentAnalysis(value,label='domain'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pattern=/^[a-z ]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pattern?pattern.test(text):text.includes(term)) throw new Error(`${label} contains forbidden investment analysis: ${term}`); } return true; }
export function validateDomainCommand(type){ if(!Object.values(CompanySecurityCommandType).includes(type)) throw new Error(`Unsupported domain command: ${type}`); assertNoInvestmentAnalysis(type,'domain command'); return true; }
export function createDomainAuditIdentity({ companyId=null, securityId=null, listingId=null, userId='system', correlationId }={}){ assertRequired({ userId, correlationId }, ['userId','correlationId'], 'domainAudit'); return Object.freeze({ domainActionId:createOpaqueId('DACT'), companyId, securityId, listingId, userId, correlationId, timestamp:new Date().toISOString() }); }
