import { createOpaqueId } from '../../../../../../packages/shared-types/src/index.js';
export const RELATIVE_VALUATION_PLUGIN_ID='relative-valuation-plugin';
export const RELATIVE_VALUATION_FORMULA_VERSION='RELATIVE_VALUATION_FORMULA_VERSION_1.0';
export const RELATIVE_VALUATION_SNAPSHOT_SCHEMA_VERSION='RELATIVE_VALUATION_SNAPSHOT_1.0';
export const RelativeValuationMethod=Object.freeze({ EV_EBITDA:'EV_EBITDA', EV_EBIT:'EV_EBIT', EV_SALES:'EV_SALES', PE:'PE', PB:'PB', PCFO:'PCFO', PEG:'PEG', CUSTOM_MULTIPLE:'CUSTOM_MULTIPLE' });
export const RelativeValuationOutlierPolicy=Object.freeze({ none:'none', median:'median', trimmedMean:'trimmedMean', winsorized:'winsorized', manual:'manual' });
export const RelativeValuationStatisticMethod=Object.freeze({ mean:'mean', median:'median', trimmedMean:'trimmedMean', winsorized:'winsorized', manual:'manual' });
export const MissingMetricPolicy=Object.freeze({ reject:'reject', skip:'skip', manualOverride:'manualOverride' });
export const StructuralConfidence=Object.freeze({ completeInputs:'complete-inputs', incompleteInputs:'incomplete-inputs', manualOverride:'manual-override' });
export const RelativeValuationPluginEventType=Object.freeze({ RelativeValuationPluginRegistered:'RelativeValuationPluginRegistered', RelativeValuationInputsValidated:'RelativeValuationInputsValidated', RelativeValuationExecutionStarted:'RelativeValuationExecutionStarted', RelativeValuationExecutionCompleted:'RelativeValuationExecutionCompleted', RelativeValuationStatisticRecorded:'RelativeValuationStatisticRecorded', RelativeValuationResultCreated:'RelativeValuationResultCreated', RelativeValuationAuditRecorded:'RelativeValuationAuditRecorded', RelativeValuationSnapshotCreated:'RelativeValuationSnapshotCreated', RelativeValuationReplayCompleted:'RelativeValuationReplayCompleted' });
export const RelativeValuationPluginCommandType=Object.freeze({ RegisterRelativeValuationPlugin:'RegisterRelativeValuationPlugin', ValidateRelativeValuationInputs:'ValidateRelativeValuationInputs', StartRelativeValuationExecution:'StartRelativeValuationExecution', CompleteRelativeValuationExecution:'CompleteRelativeValuationExecution', RecordRelativeValuationStatistic:'RecordRelativeValuationStatistic', CreateRelativeValuationResult:'CreateRelativeValuationResult', RecordRelativeValuationAudit:'RecordRelativeValuationAudit', CreateRelativeValuationSnapshot:'CreateRelativeValuationSnapshot', ReplayRelativeValuationExecution:'ReplayRelativeValuationExecution' });
export const RelativeValuationValidationStatus=Object.freeze({ Passed:'Passed', Failed:'Failed' });
export const RelativeValuationPermissionAction=Object.freeze({ viewRelativeValuationPlugin:'viewRelativeValuationPlugin', runRelativeValuationDryRun:'runRelativeValuationDryRun', runRelativeValuationValidation:'runRelativeValuationValidation', runRelativeValuationCalculation:'runRelativeValuationCalculation', readRelativeValuationAudit:'readRelativeValuationAudit', replayRelativeValuationExecution:'replayRelativeValuationExecution' });
export const RelativeValuationErrorCode=Object.freeze({ MISSING_PEER_SET:'MISSING_PEER_SET', MISSING_PEER_PROVENANCE:'MISSING_PEER_PROVENANCE', UNSUPPORTED_METHOD:'UNSUPPORTED_METHOD', MIXED_CURRENCY:'MIXED_CURRENCY', MISSING_METRIC:'MISSING_METRIC', INVALID_MULTIPLE:'INVALID_MULTIPLE', NEGATIVE_SHARE_COUNT:'NEGATIVE_SHARE_COUNT', FORBIDDEN_DATA_SOURCE:'FORBIDDEN_DATA_SOURCE' });
const forbidden=Object.freeze(['recommendation','rating','score','ranking','screening','peer selection','market data','provider integration','buy','sell','hold','portfolio action','decision automation']);
export function assertRequired(r,fields,label='record'){ for(const f of fields) if(r?.[f]===undefined||r?.[f]===null||r?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoRelativeDecisionLogic(v,label='relative valuation'){ const text=JSON.stringify(v||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z ]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden decision/ranking logic: ${term}`); } return true; }
export function validateRelativeValuationCommand(type){ if(!Object.values(RelativeValuationPluginCommandType).includes(type)) throw new Error(`Unsupported relative valuation command: ${type}`); assertNoRelativeDecisionLogic(type,'relative valuation command'); return true; }
export function createRelativeValuationAuditIdentity({ relativeValuationPluginId=RELATIVE_VALUATION_PLUGIN_ID, pluginVersion, formulaVersion=RELATIVE_VALUATION_FORMULA_VERSION, valuationExecutionId, valuationInputPackageId, companyId, securityId, userId='system', correlationId }={}){ assertRequired({ relativeValuationPluginId, pluginVersion, formulaVersion, valuationExecutionId, valuationInputPackageId, userId, correlationId }, ['relativeValuationPluginId','pluginVersion','formulaVersion','valuationExecutionId','valuationInputPackageId','userId','correlationId'], 'relativeAudit'); return Object.freeze({ relativeValuationActionId:createOpaqueId('RVALACT'), relativeValuationPluginId, pluginVersion, formulaVersion, valuationExecutionId, valuationInputPackageId, companyId, securityId, userId, correlationId, timestamp:new Date().toISOString() }); }
