import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';
export const LIVE_ENABLEMENT_SCHEMA_VERSION='LIVE_ENABLEMENT_SCHEMA_VERSION_1.0';
export const LIVE_READINESS_FEATURE_FLAG='live_trading_readiness_foundation';
export const ReadinessFrameworkEventType=Object.freeze({ ReadinessEvaluationStarted:'ReadinessEvaluationStarted', ReadinessEvaluationCompleted:'ReadinessEvaluationCompleted', ReadinessCheckPassed:'ReadinessCheckPassed', ReadinessCheckFailed:'ReadinessCheckFailed', FeatureGateEvaluated:'FeatureGateEvaluated', AuthorizationRequested:'AuthorizationRequested', AuthorizationRecorded:'AuthorizationRecorded', ApprovalArtifactCreated:'ApprovalArtifactCreated', KillSwitchActivated:'KillSwitchActivated', KillSwitchReleased:'KillSwitchReleased', ReadinessAuditRecorded:'ReadinessAuditRecorded', ReadinessSnapshotCreated:'ReadinessSnapshotCreated', ReadinessReplayCompleted:'ReadinessReplayCompleted' });
export const ReadinessFrameworkCommandType=Object.freeze({ StartReadinessEvaluation:'StartReadinessEvaluation', CompleteReadinessEvaluation:'CompleteReadinessEvaluation', EvaluateReadinessCheck:'EvaluateReadinessCheck', EvaluateFeatureGate:'EvaluateFeatureGate', RequestAuthorization:'RequestAuthorization', RecordAuthorization:'RecordAuthorization', CreateApprovalArtifact:'CreateApprovalArtifact', ActivateKillSwitch:'ActivateKillSwitch', ReleaseKillSwitch:'ReleaseKillSwitch', RecordReadinessAudit:'RecordReadinessAudit', CreateReadinessSnapshot:'CreateReadinessSnapshot', ReplayReadinessArtifact:'ReplayReadinessArtifact' });
export const ReadinessStatus=Object.freeze({ Eligible:'Eligible', Ineligible:'Ineligible' });
export const ReadinessCheckStatus=Object.freeze({ Passed:'Passed', Failed:'Failed', Warning:'Warning' });
export const ReadinessGateType=Object.freeze({ platform:'platform', environment:'environment', provider:'provider', operator:'operator', artifact:'artifact' });
export const AuthorizationLevel=Object.freeze({ technical:'Technical Approval', policy:'Policy Approval', operator:'Operator Approval', emergency:'Emergency Override' });
export const ApprovalArtifactStatus=Object.freeze({ Draft:'Draft', Approved:'Approved', Rejected:'Rejected', Archived:'Archived' });
export const KillSwitchScope=Object.freeze({ platform:'platform', environment:'environment', provider:'provider', portfolio:'portfolio', strategy:'strategy', transmission:'transmission' });
export const ReadinessPermissionAction=Object.freeze({ viewReadinessArtifact:'viewReadinessArtifact', evaluateReadiness:'evaluateReadiness', recordAuthorization:'recordAuthorization', createApprovalArtifact:'createApprovalArtifact', activateKillSwitch:'activateKillSwitch', releaseKillSwitch:'releaseKillSwitch', readReadinessAudit:'readReadinessAudit', replayReadinessArtifact:'replayReadinessArtifact' });
const forbidden=Object.freeze(['credential','secret','live endpoint','broker api','production order','order transmission','real-money','settlement','clearing','custdn','capital deployment','capital movement','regulatory reporting','go-live','transmit order','trade execution']);
export function assertRequired(r,fields,label='record'){ for(const f of fields) if(r?.[f]===undefined||r?.[f]===null||r?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoLiveReadinessLeak(v,label='readiness'){ const text=JSON.stringify(v||{}).toLowerCase(); for(const term of forbidden){ const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const pat=/^[a-z -]+$/.test(term)?new RegExp(`(^|[^a-z])${esc}([^a-z]|$)`):null; if(pat?pat.test(text):text.includes(term)) throw new Error(`${label} contains forbidden live enablement data: ${term}`); } return true; }
export function validateReadinessCommand(type){ if(!Object.values(ReadinessFrameworkCommandType).includes(type)) throw new Error(`Unsupported readiness command: ${type}`); assertNoLiveReadinessLeak(type,'readiness command'); return true; }
export function createReadinessAuditIdentity({ readinessId=null, integrationArtifactId=null, executionArtifactId=null, userId='system', correlationId }={}){ assertRequired({ userId, correlationId },['userId','correlationId'],'readinessAudit'); return Object.freeze({ readinessActionId:createOpaqueId('RDACT'), readinessId, integrationArtifactId, executionArtifactId, userId, correlationId, timestamp:new Date().toISOString() }); }
export function canonicalSerialize(value){ if(value===null||typeof value!=='object') return JSON.stringify(value); if(Array.isArray(value)) return `[${value.map(canonicalSerialize).join(',')}]`; return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonicalSerialize(value[k])}`).join(',')}}`; }
export function decisionHash(value){ const text=canonicalSerialize(value); let h=0; for(let i=0;i<text.length;i++) h=(Math.imul(31,h)+text.charCodeAt(i))|0; return `RDHASH_${(h>>>0).toString(16).toUpperCase()}`; }
