import { createOpaqueId } from '../../../../../packages/shared-types/src/index.js';

export const METHODOLOGY_FRAMEWORK_FEATURE_FLAG = 'methodology_framework_foundation';
export const METHODOLOGY_EXECUTION_ENVIRONMENT_VERSION = 'METHODOLOGY_EXECUTION_ENVIRONMENT_1.0';
export const MethodologyFrameworkEventType = Object.freeze({ MethodologyDefinitionRegistered:'MethodologyDefinitionRegistered', MethodologyVersionCreated:'MethodologyVersionCreated', MethodologyActivated:'MethodologyActivated', MethodologyDeprecated:'MethodologyDeprecated', MethodologyRetired:'MethodologyRetired', MethodologyConfigurationRegistered:'MethodologyConfigurationRegistered', MethodologyEvidenceRequirementDeclared:'MethodologyEvidenceRequirementDeclared', MethodologyEvidenceLinked:'MethodologyEvidenceLinked', MethodologyDryRunStarted:'MethodologyDryRunStarted', MethodologyDryRunCompleted:'MethodologyDryRunCompleted', MethodologyValidationStarted:'MethodologyValidationStarted', MethodologyValidationCompleted:'MethodologyValidationCompleted', MethodologyExecutionAudited:'MethodologyExecutionAudited', MethodologySnapshotCreated:'MethodologySnapshotCreated', MethodologyReplayCompleted:'MethodologyReplayCompleted' });
export const MethodologyFrameworkCommandType = Object.freeze({ RegisterMethodologyDefinition:'RegisterMethodologyDefinition', CreateMethodologyVersion:'CreateMethodologyVersion', ActivateMethodology:'ActivateMethodology', DeprecateMethodology:'DeprecateMethodology', RetireMethodology:'RetireMethodology', RegisterMethodologyConfiguration:'RegisterMethodologyConfiguration', DeclareEvidenceRequirement:'DeclareEvidenceRequirement', LinkEvidenceToMethodology:'LinkEvidenceToMethodology', StartMethodologyDryRun:'StartMethodologyDryRun', CompleteMethodologyDryRun:'CompleteMethodologyDryRun', StartMethodologyValidation:'StartMethodologyValidation', CompleteMethodologyValidation:'CompleteMethodologyValidation', RecordMethodologyAudit:'RecordMethodologyAudit', CreateMethodologySnapshot:'CreateMethodologySnapshot', ReplayMethodologyExecution:'ReplayMethodologyExecution' });
export const MethodologyDefinitionStatus = Object.freeze({ draft:'draft', active:'active', deprecated:'deprecated', retired:'retired' });
export const MethodologyLifecycleState = Object.freeze({ Draft:'Draft', Registered:'Registered', Validated:'Validated', Active:'Active', Deprecated:'Deprecated', Retired:'Retired', Failed:'Failed' });
export const MethodologyExecutionStatus = Object.freeze({ Prepared:'Prepared', DryRunStarted:'DryRunStarted', DryRunCompleted:'DryRunCompleted', ValidationStarted:'ValidationStarted', ValidationCompleted:'ValidationCompleted', Failed:'Failed' });
export const MethodologyInputType = Object.freeze({ certifiedEvidence:'certified-evidence' });
export const MethodologyValidationStatus = Object.freeze({ NotRun:'NotRun', Passed:'Passed', Failed:'Failed' });
export const MethodologyPermissionAction = Object.freeze({ viewMethodology:'viewMethodology', registerMethodology:'registerMethodology', activateMethodology:'activateMethodology', deprecateMethodology:'deprecateMethodology', retireMethodology:'retireMethodology', configureMethodology:'configureMethodology', runMethodologyDryRun:'runMethodologyDryRun', runMethodologyValidation:'runMethodologyValidation', readMethodologyAudit:'readMethodologyAudit', replayMethodology:'replayMethodology' });
export const MethodologyConfigurationScope = Object.freeze({ global:'global', module:'module', workflow:'workflow', user:'user', execution:'execution' });
export const MethodologyCapability = Object.freeze({ validation:'validation', sufficiency:'sufficiency', replay:'replay', audit:'audit' });

export const forbiddenMethodologyTerms = Object.freeze(['valuation','discounted cash flow','dcf','relative valuation','pe multiple','pb multiple','ev multiple','factor model','financial statement','forecast','stock scoring','score','rating','buy','sell','hold','recommendation','recommend','target price','decision','portfolio','market data','provider integration','investment thesis','investment opinion']);
export function assertRequired(record, fields, label='record'){ for(const f of fields) if(record?.[f]===undefined||record?.[f]===null||record?.[f]==='') throw new Error(`${label}.${f} is required`); return true; }
export function assertNoInvestmentAnalysis(value,label='Methodology'){ const text=JSON.stringify(value||{}).toLowerCase(); for(const term of forbiddenMethodologyTerms) { const escaped=term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); const pattern=/^[a-z ]+$/.test(term) ? new RegExp(`(^|[^a-z])${escaped}([^a-z]|$)`) : null; if(pattern ? pattern.test(text) : text.includes(term)) throw new Error(`${label} contains forbidden investment analysis: ${term}`); } return true; }
export function validateMethodologyCommand(type){ if(!Object.values(MethodologyFrameworkCommandType).includes(type)) throw new Error(`Unsupported Methodology command: ${type}`); assertNoInvestmentAnalysis(type,'Methodology command'); return true; }
export function createMethodologyAuditIdentity({ methodologyId, methodologyVersion, executionId=null, workflowInstanceId=null, evidenceRecordIds=[], userId='system', correlationId }={}){ assertRequired({ methodologyId, methodologyVersion, userId, correlationId }, ['methodologyId','methodologyVersion','userId','correlationId'], 'methodologyAudit'); return Object.freeze({ methodologyActionId:createOpaqueId('MACT'), methodologyId, methodologyVersion, executionId, workflowInstanceId, evidenceRecordIds:Object.freeze(evidenceRecordIds.slice()), userId, correlationId, timestamp:new Date().toISOString() }); }
export function stableMethodologyFingerprint({ methodologyVersion, configurationVersion, evidenceVersionIds=[], executionEnvironmentVersion=METHODOLOGY_EXECUTION_ENVIRONMENT_VERSION }={}){ const text=JSON.stringify({ methodologyVersion, configurationVersion, evidenceVersionIds:evidenceVersionIds.slice().sort(), executionEnvironmentVersion }); let h=0; for(let i=0;i<text.length;i++) h=(Math.imul(31,h)+text.charCodeAt(i))|0; return `MFPR_${(h>>>0).toString(16).toUpperCase().padStart(8,'0')}`; }
